### ISSUE TITLE
influx db2 is working?

### ISSUE THREAD

**Issue by hilleke-dirk** [jomjol/AI-on-the-edge-device#1160] opened 2022-10-11 12:51 UTC
V12.0.1
I tried to activate the influxdb setting, but i am not sure, if it works with the V2 Database
No entries in my database until now and no error in the log only: 2022-10-11T14:45:28: 	FlowControll.doFlow - ClassFlowInfluxDB

Influxdb
Uri   http://x.x.x.x:8086
database  daten
measurement gas
user  username
password yes_set

I can open the influxdb-gui with these parameters without any problem. The database should work.

**Comment by jomjol** [comment] 2022-10-12 17:43
InfluxDB has not been tested intensively and was implemented by a supporter additionally. To my knowledge most of the users are taking the data over the MQTT interface.

I would need to test the influxdb (setup a server etc.). As my main computer is down, this will take quite some time. But I leave this issue open for the time being.

**Comment by infa-presales** [comment] 2022-10-12 22:57
Actually it does not work with influxdb v1 either. I have configured the connection but neither measurement or data in existing measurements are created. In addition, even with full log enabled I cannot see any traces in the logs according to failed or successful write attempt. 
The connection with MQTT works, albeit there are multiple shipments of different pieces of the data on different topics under given topic/main  (like single shipments in raw payload such as freeMem, wifiRSSI, CPUtemp, but one main/json with a set of the meter data

**Comment by dstoianov** [comment] 2022-10-15 10:09
It works with such config 

```bash
{22-10-15 11:42}pi-unifi:~ pi% influxd version
InfluxDB v1.8.10 (git: 1.8 688e697c51fd)
```
<img width="460" alt="image" src="https://user-images.githubusercontent.com/4168915/195980805-a2ead7db-3e9c-4286-865c-329cb70ba394.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/4168915/195980687-22868539-23ca-419d-b59f-27e25e23cca0.png">


Measurements

```sql
> select * from gas LIMIT 4;
name: gas
time                main/value
----                ----------
1665824667000000000 1907002
1665824847000000000 1907002
1665825027000000000 1907002
1665825207000000000 1907002
```

**Comment by jomjol** [comment] 2022-10-15 14:44
I can confirm, that InfluxDB is also working with the version 12.x.y

Configuration:
![grafik](https://user-images.githubusercontent.com/30766535/195992471-76c37059-2eb1-461f-a079-453d8fb78365.png)

Version:
![grafik](https://user-images.githubusercontent.com/30766535/195992500-cd707bda-9cae-4424-90df-722b7227d990.png)
(Version with respect to InfluxDB identical with 12.x.y)

But it can be, that this is only working up to InfluxDB 1.8 and NOT with InfluxDB 2.x.

**Comment by caco3** [comment] 2022-10-15 20:49
The original question is about InfluxDB2! Since it was implemented for InfluxDB 1, it most likely will not work for influx DB2 as there are changes on the API from 1 to 2! I have such a DB running for my Homeassistant and can try it out sometimes.

In any way, pull requests to extend support to InfluxDB 2 are welcome!

**Comment by jomjol** [comment] 2022-10-16 06:34
I think, INfluxDB v2 is rather a new feature than an issue. Because the API changed quite a lot and is not downwards compatible (neither in the interface, nor in the db itself).
I suggest to make a remark in the configuration page (done) and put this to the feature request list (done).

**Comment by caco3** [comment] 2022-10-16 18:55
closing as I better spend my time on other issues

**Closed by caco3** 2022-10-16 18:55 UTC
