### ISSUE TITLE
MQTT Json Bug

### ISSUE THREAD

**Issue by peter-lueer** [jomjol/AI-on-the-edge-device#1544] opened 2022-12-11 10:16 UTC
### The Problem

MQTT published json has wrong format:
{"value": 251.466, "raw": "251.466, "pre": "251.466", "error": "no error", "rate": 0.000433, "timestamp": "2022-12-11T10:51:06+0100"}

code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp line 300 missing "
wrong:          json += ", \"pre\": \"" + resultpre;
should be:     json += "**\"**, \"pre\": \"" + resultpre;

### Version

Release: v13.0.5 (Commit: e23c89a)

### Logfile

```shell
no Log error on device.
```

### Expected Behavior

{"value": 251.466, "raw": "251.466", "pre": "251.466", "error": "no error", "rate": 0.000433, "timestamp": "2022-12-11T10:51:06+0100"}

**Comment by caco3** [comment] 2022-12-11 17:11
This is a duplicate of https://github.com/jomjol/AI-on-the-edge-device/issues/1514

**Closed by caco3** 2022-12-11 17:11 UTC
Labels: bug
