### ISSUE TITLE
Watermeter not working ([MAIN] Reset reason: Exception/panic)

### ISSUE THREAD

**Issue by SebSkarp** [jomjol/AI-on-the-edge-device#2356] opened 2023-04-27 19:59 UTC
### The Problem

Yesterday my watermeter stopped working. Noticed in HA since not giving values. When I got home I logged into the watermeter device interface to see it saying "Initializing (delayed) but nothing really happens.

Tried updating to the second latest version (due to seeing some people having issues with the latest version?), but still no change.
I am not a coding kinda guy, so any help would be much appreciated. What should I do to fix it?

See included log for ref. 

Thanks

### Version

Release: v15.1.1 (Commit: 03c84a1+)

### Logfile

```shell
[0d00h00m04s] 2023-04-27T19:51:01 <INF> [MAIN] =================================================
[0d00h00m04s] 2023-04-27T19:51:01 <INF> [MAIN] ==================== Start ======================
[0d00h00m04s] 2023-04-27T19:51:01 <INF> [MAIN] =================================================
[0d00h00m04s] 2023-04-27T19:51:01 <INF> [SDCARD] Basic R/W check started...
[0d00h00m04s] 2023-04-27T19:51:01 <INF> [SDCARD] Basic R/W check successful
[0d00h00m04s] 2023-04-27T19:51:01 <INF> [SNTP] TimeServer not defined, using default: pool.ntp.org
[0d00h00m04s] 2023-04-27T19:51:01 <INF> [SNTP] Configuring NTP Client...
[0d00h00m04s] 2023-04-27T21:51:01 <INF> [SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m04s] 2023-04-27T21:51:01 <INF> [SNTP] Time is already set: 2023-04-27 21:51:01
[0d00h00m04s] 2023-04-27T21:51:01 <INF> [MAIN] CPU frequency: 160 MHz
[0d00h00m05s] 2023-04-27T21:51:01 <INF> [SDCARD] Folder/file presence check started...
[0d00h00m05s] 2023-04-27T21:51:01 <INF> [SDCARD] Folder/file presence check successful
[0d00h00m05s] 2023-04-27T21:51:01 <INF> [MAIN] Tag: 'v15.1.1', Release: v15.1.1 (Commit: 03c84a1+), Date/Time: 2023-03-23 20:40, Web UI: Release: v15.1.1 (Commit: 03c84a1+)
[0d00h00m05s] 2023-04-27T21:51:01 <INF> [MAIN] Reset reason: Via esp_restart
[0d00h00m05s] 2023-04-27T21:51:01 <INF> [WLANINI] SSID: ILS
[0d00h00m05s] 2023-04-27T21:51:01 <INF> [WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2023-04-27T21:51:02 <INF> [WLANINI] Hostname: watermeter
[0d00h00m05s] 2023-04-27T21:51:02 <INF> [MAIN] WLAN config loaded, init WIFI...
[0d00h00m05s] 2023-04-27T21:51:02 <INF> [WIFI] Automatic interface config --> Use DHCP service
[0d00h00m05s] 2023-04-27T21:51:02 <INF> [WIFI] Set hostname to: watermeter
[0d00h00m05s] 2023-04-27T21:51:02 <INF> [WIFI] Init successful
[0d00h00m07s] 2023-04-27T21:51:04 <INF> [MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m07s] 2023-04-27T21:51:04 <INF> [MAIN] Total heap: 4175358 byte
[0d00h00m08s] 2023-04-27T21:51:04 <INF> [MAIN] Camera info: PID: 0x26, VER: 0x42, MIDL: 0x7f, MIDH: 0xa2
[0d00h00m08s] 2023-04-27T21:51:04 <INF> [MAIN] Device info: CPU cores: 2, Chip revision: 1
[0d00h00m08s] 2023-04-27T21:51:04 <INF> [MAIN] SD card info: Name: SU02G, Capacity: 1886MB, Free: 1860MB
[0d00h00m09s] 2023-04-27T21:51:05 <INF> [WIFI] Connected to: ILS, RSSI: -65
[0d00h00m09s] 2023-04-27T21:51:06 <INF> [WIFI] Assigned IP: 192.168.1.201
[0d00h00m10s] 2023-04-27T21:51:07 <INF> [MAIN] Initialization completed successfully! Starting flow task ...
[0d00h00m10s] 2023-04-27T21:50:52 <INF> [SNTP] Time is synced with NTP Server pool.ntp.org: 2023-04-27 21:50:52
[0d00h00m04s] 2023-04-27T19:50:39 <INF> [MAIN] =================================================
[0d00h00m04s] 2023-04-27T19:50:39 <INF> [MAIN] ==================== Start ======================
[0d00h00m04s] 2023-04-27T19:50:39 <INF> [MAIN] =================================================
[0d00h00m04s] 2023-04-27T19:50:39 <INF> [SDCARD] Basic R/W check started...
[0d00h00m04s] 2023-04-27T19:50:39 <INF> [SDCARD] Basic R/W check successful
[0d00h00m04s] 2023-04-27T19:50:39 <INF> [SNTP] TimeServer not defined, using default: pool.ntp.org
[0d00h00m04s] 2023-04-27T19:50:39 <INF> [SNTP] Configuring NTP Client...
[0d00h00m04s] 2023-04-27T21:50:39 <INF> [SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m04s] 2023-04-27T21:50:39 <INF> [SNTP] Time is already set: 2023-04-27 21:50:39
[0d00h00m04s] 2023-04-27T21:50:39 <INF> [MAIN] CPU frequency: 160 MHz
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [SDCARD] Folder/file presence check started...
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [SDCARD] Folder/file presence check successful
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [MAIN] Tag: 'v15.1.1', Release: v15.1.1 (Commit: 03c84a1+), Date/Time: 2023-03-23 20:40, Web UI: Release: v15.1.1 (Commit: 03c84a1+)
[0d00h00m05s] 2023-04-27T21:50:40 <WRN> [MAIN] Reset reason: Exception/panic
[0d00h00m05s] 2023-04-27T21:50:40 <WRN> [MAIN] Device was rebooted due to a software exception! Log level is set to DEBUG until the next reboot. Flow init is delayed by 5 minutes to check the logs or do an OTA update
[0d00h00m05s] 2023-04-27T21:50:40 <WRN> [MAIN] Keep device running until crash occurs again and check logs after device is up again
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [LOGFILE] Set log level to DEBUG
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [WLANINI] SSID: ILS
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [WLANINI] Hostname: watermeter
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [MAIN] WLAN config loaded, init WIFI...
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [WIFI] Automatic interface config --> Use DHCP service
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [WIFI] Set hostname to: watermeter
[0d00h00m05s] 2023-04-27T21:50:40 <INF> [WIFI] Init successful
[0d00h00m07s] 2023-04-27T21:50:42 <INF> [MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m07s] 2023-04-27T21:50:42 <INF> [MAIN] Total heap: 4175458 byte
[0d00h00m07s] 2023-04-27T21:50:42 <INF> [MAIN] Camera info: PID: 0x26, VER: 0x42, MIDL: 0x7f, MIDH: 0xa2
[0d00h00m07s] 2023-04-27T21:50:42 <INF> [MAIN] Device info: CPU cores: 2, Chip revision: 1
[0d00h00m07s] 2023-04-27T21:50:42 <INF> [MAIN] SD card info: Name: SU02G, Capacity: 1886MB, Free: 1860MB
[0d00h00m08s] 2023-04-27T21:50:43 <INF> [WIFI] Connected to: ILS, RSSI: -63
[0d00h00m08s] 2023-04-27T21:50:43 <INF> [WIFI] Assigned IP: 192.168.1.201
[0d00h00m09s] 2023-04-27T21:51:06 <INF> [SNTP] Time is synced with NTP Server pool.ntp.org: 2023-04-27 21:51:06
[0d00h00m09s] 2023-04-27T21:51:06 <INF> [MAIN] Initialization completed successfully! Starting flow task ...
[0d00h00m38s] 2023-04-27T21:51:35 <WRN> [WIFI] Disconnected (34)
[0d00h00m40s] 2023-04-27T21:51:37 <INF> [WIFI] Connected to: ILS, RSSI: -61
[0d00h00m42s] 2023-04-27T21:51:39 <INF> [WIFI] Assigned IP: 192.168.1.201
[0d00h00m43s] 2023-04-27T21:51:40 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m43s] 2023-04-27T21:51:40 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m43s] 2023-04-27T21:51:40 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m43s] 2023-04-27T21:51:40 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m47s] 2023-04-27T21:51:44 <DBG> [OTA FILE] log_get_last_part_handler
```

### Screenshots

<img width="997" alt="Skärmavbild 2023-04-27 kl  21 58 50" src="https://user-images.githubusercontent.com/79046817/234977242-e05a82d6-c4a5-476d-90e4-69169ffc2e5b.png">

**Comment by fakenius** [comment] 2023-04-28 11:25
The same for me.

**Comment by SebSkarp** [comment] 2023-04-28 18:00
So some updates from my end. I downgraded back to latest 14.x.x version and then it got up and running again. I then tried upgrading to 15.1.1 and fingers crossed but it seems to be working for me again.
For the time being I will not go to to the latest version, since it seems to be working again.

**Comment by Eldarion85** [comment] 2023-04-29 14:16
I have the same problem. First I did the OTA update to version v15.2.1.
Then I completely erased the ESP32, formatted the SD card and re-flashed and set everything up again.
When that didn't work either, I took a completely new ESP32 and set it up again.
In the beginning it runs reasonably well, but already after 15 minutes I get into an error loop and the ESP32 restarts every minute with the error "Reset reason: Exception/panic".
In the Overview screen, only "Initializing (delayed)" is continuously displayed.

**Comment by AseKarlsson** [comment] 2023-04-29 14:38
Same here with 14.X version. Could OTA update to 15.2.1 but still the same

**Comment by boverhae** [comment] 2023-04-29 16:02
same here. I've toggled logs to DEBUG then reboot. so toggled to ERROR again. It works now... Strange

**Comment by AseKarlsson** [comment] 2023-04-29 17:08
An other ESP32-Cam did not solve it and not the same config on an other SD-Card.
Now I am back on the same ESP32-Cam board with new fresh files and new alignment etc. seems to work.
Some kind of corruption of files on the SD

**Comment by Eldarion85** [comment] 2023-04-29 17:38
I've been looking for the problem again and found something.

I fetch the following data every 3 minutes via API with Node Red.
   http://192.168.xx.xx/json
   http://192.168.xx.xx/sysinfo
   http://192.168.xx.xx/rssi
   http://192.168.xx.xx/statusflow
It has always worked great in the past.

Since my new ESP is up and running this afternoon, it restarts automatically every 3 minutes (at the same interval as my API query) with the error "Reset reason: Exception/panic". That struck me as suspicious :).
In my experiments, I found out that this always happens when I retrieve "sysinfo" via the API. Even if I open "http://192.168.xx.xx/sysinfo" in the browser, the ESP crashes immediately. The other two (rssi and statusflow) are still working fine.

For an hour now I've disabled polling of "sysinfo" in Node Red and everything works fine.
However, I always have to restart the ESP manually after it crashes. The automatic restart after the crash does not directly lead to it running again.

**Comment by Eldarion85** [comment] 2023-04-29 17:51
> An other ESP32-Cam did not solve it and not the same config on an other SD-Card. Now I am back on the same ESP32-Cam board with new fresh files and new alignment etc. seems to work. Some kind of corruption of files on the SD

That didn't help me either. I took a new ESP and a new SD card, re-downloaded the files from GitHub and didn't restore any backups either.
I completely reinstalled and set up everything. With the same result that it crashed again and again.

**Comment by SebSkarp** [comment] 2023-04-29 17:53
Men has actually been working great since I first downgraded then upgraded again. Still kind of waiting for it to crash but for now that seems to have done the trick for me 🤞🏻

**Comment by AseKarlsson** [comment] 2023-04-29 17:54
> > An other ESP32-Cam did not solve it and not the same config on an other SD-Card. Now I am back on the same ESP32-Cam board with new fresh files and new alignment etc. seems to work. Some kind of corruption of files on the SD
> 
> That didn't help me either. I took a new ESP and a new SD card, re-downloaded the files from GitHub and didn't restore any backups either. I completely reinstalled and set up everything. With the same result that it crashed again and again.

Mine up for 45 minutes now, lets see.

**Comment by Eldarion85** [comment] 2023-04-29 17:59
Can someone try whether calling "sysinfo" via the API still works for you?
I assume that as soon as you call up "http://192.168.xx.xx/sysinfo" in the browser, you will have the same error again in the log.

**Comment by AseKarlsson** [comment] 2023-04-29 19:07
Going to the IP and using menus to get to see System/Info work fine

**Comment by Eldarion85** [comment] 2023-04-29 19:18
> Going to the IP and using menus to get to see System/Info work fine

What kind of answer is that?
Of course you can use the website, but that doesn't change the fact that "sysinfo" no longer works via the API.
I only use the web interface for setup and get all the data via the API into the home automation for visualization.

**Comment by AseKarlsson** [comment] 2023-04-29 19:24
Sorry, dumb answer then!

**Comment by HundKatzeMaus** [comment] 2023-05-01 04:25
Hi,

this is also one of the problems I have. I also can´t take a new reference image etc. My version is also v15.2.1', Release: v15.2.1 (Commit: b24b7d5).

[0d00h02m14s] 2023-05-01T06:12:25 <INF> [OTA] !!! System will restart within 5 sec!!!
[0d00h02m14s] 2023-05-01T06:12:25 <INF> [OTA] Reboot triggered by Software (5s)
[0d00h02m14s] 2023-05-01T06:12:25 <WRN> [OTA] Reboot in 5sec
[0d00h00m00s] 2023-05-01T04:12:33 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-01T04:12:33 <INF> [MAIN] ==================== Start ======================
[0d00h00m00s] 2023-05-01T04:12:33 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-01T04:12:33 <INF> [MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m00s] 2023-05-01T04:12:33 <INF> [MAIN] Total heap: 4377075 byte
[0d00h00m04s] 2023-05-01T04:12:37 <INF> [MAIN] Camera info: PID: 0x26, VER: 0x42, MIDL: 0x7f, MIDH: 0xa2
[0d00h00m04s] 2023-05-01T04:12:37 <INF> [SDCARD] Basic R/W check started...
[0d00h00m04s] 2023-05-01T04:12:37 <INF> [SDCARD] Basic R/W check successful
[0d00h00m04s] 2023-05-01T04:12:37 <INF> [SNTP] TimeServer not defined, using default: pool.ntp.org
[0d00h00m04s] 2023-05-01T04:12:37 <INF> [SNTP] Configuring NTP Client...
[0d00h00m04s] 2023-05-01T06:12:37 <INF> [SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m04s] 2023-05-01T06:12:37 <INF> [SNTP] Time is already set: 2023-05-01 06:12:37
[0d00h00m04s] 2023-05-01T06:12:37 <INF> [MAIN] CPU frequency: 160 MHz
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [SDCARD] Folder/file presence check started...
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [SDCARD] Folder/file presence check successful
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [MAIN] Tag: 'v15.2.1', Release: v15.2.1 (Commit: b24b7d5), Date/Time: 2023-04-27 20:44, Web UI: Release: v15.2.1 (Commit: b24b7d5)
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [MAIN] Reset reason: Via esp_restart
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [WLANINI] SSID: Gateway
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [WLANINI] Hostname: Wasserzaehler
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [WLANINI] RSSIThreshold: 0
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [MAIN] WLAN config loaded, init WIFI...
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [WIFI] Automatic interface config --> Use DHCP service
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [WIFI] Set hostname to: Wasserzaehler
[0d00h00m05s] 2023-05-01T06:12:38 <INF> [WIFI] Init successful
[0d00h00m07s] 2023-05-01T06:12:41 <INF> [WIFI] Connected to: Gateway, RSSI: -44
[0d00h00m08s] 2023-05-01T06:12:42 <INF> [WIFI] Assigned IP: 192.168.180.212
[0d00h00m10s] 2023-05-01T06:12:43 <INF> [SNTP] Time is synced with NTP Server pool.ntp.org: 2023-05-01 06:12:43
[0d00h00m11s] 2023-05-01T06:12:44 <INF> [MAIN] Device info: CPU cores: 2, Chip revision: 300
[0d00h00m11s] 2023-05-01T06:12:44 <INF> [MAIN] SD card info: Name: SD32G, Capacity: 30436MB, Free: 30386MB
[0d00h00m13s] 2023-05-01T06:12:46 <INF> [MAIN] Initialization completed successfully! Starting flow task ...
**[0d00h00m13s] 2023-05-01T06:12:46 <ERR> [C IMG BASIS] /sdcard/img_tmp/raw.jpg is empty!**
[0d00h00m00s] 2023-05-01T04:12:48 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-01T04:12:48 <INF> [MAIN] ==================== Start ======================
[0d00h00m00s] 2023-05-01T04:12:48 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-01T04:12:48 <INF> [MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m00s] 2023-05-01T04:12:48 <INF> [MAIN] Total heap: 4377075 byte
[0d00h00m04s] 2023-05-01T04:12:52 <INF> [MAIN] Camera info: PID: 0x26, VER: 0x42, MIDL: 0x7f, MIDH: 0xa2
[0d00h00m04s] 2023-05-01T04:12:52 <INF> [SDCARD] Basic R/W check started...
[0d00h00m04s] 2023-05-01T04:12:52 <INF> [SDCARD] Basic R/W check successful
[0d00h00m04s] 2023-05-01T04:12:52 <INF> [SNTP] TimeServer not defined, using default: pool.ntp.org
[0d00h00m04s] 2023-05-01T04:12:52 <INF> [SNTP] Configuring NTP Client...
[0d00h00m04s] 2023-05-01T06:12:52 <INF> [SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m04s] 2023-05-01T06:12:52 <INF> [SNTP] Time is already set: 2023-05-01 06:12:52
[0d00h00m04s] 2023-05-01T06:12:52 <INF> [MAIN] CPU frequency: 160 MHz
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [SDCARD] Folder/file presence check started...
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [SDCARD] Folder/file presence check successful
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [MAIN] Tag: 'v15.2.1', Release: v15.2.1 (Commit: b24b7d5), Date/Time: 2023-04-27 20:44, Web UI: Release: v15.2.1 (Commit: b24b7d5)
[0d00h00m05s] 2023-05-01T06:12:53 <WRN> [MAIN] Reset reason: Exception/panic
**[0d00h00m05s] 2023-05-01T06:12:53 <WRN> [MAIN] Device was rebooted due to a software exception! Log level is set to DEBUG until the next reboot. Flow init is delayed by 5 minutes to check the logs or do an OTA update**
**[0d00h00m05s] 2023-05-01T06:12:53 <WRN> [MAIN] Keep device running until crash occurs again and check logs after device is up again**
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [LOGFILE] Set log level to DEBUG
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [WLANINI] SSID: Gateway
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [WLANINI] Hostname: Wasserzaehler
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [WLANINI] RSSIThreshold: 0
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [MAIN] WLAN config loaded, init WIFI...
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [WIFI] Automatic interface config --> Use DHCP service
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [WIFI] Set hostname to: Wasserzaehler
[0d00h00m05s] 2023-05-01T06:12:53 <INF> [WIFI] Init successful
[0d00h00m07s] 2023-05-01T06:12:55 <DBG> [SNTP] Waiting for system time to be set... 1/10
[0d00h00m07s] 2023-05-01T06:12:56 <WRN> [WIFI] Disconnected (202, Auth fail)
[0d00h00m09s] 2023-05-01T06:12:57 <DBG> [SNTP] Waiting for system time to be set... 2/10
[0d00h00m10s] 2023-05-01T06:12:58 <WRN> [WIFI] Disconnected (205)
[0d00h00m11s] 2023-05-01T06:12:59 <DBG> [SNTP] Waiting for system time to be set... 3/10
[0d00h00m12s] 2023-05-01T06:13:01 <INF> [WIFI] Connected to: Gateway, RSSI: -46
[0d00h00m13s] 2023-05-01T06:13:01 <DBG> [SNTP] Waiting for system time to be set... 4/10
[0d00h00m13s] 2023-05-01T06:13:02 <INF> [WIFI] Assigned IP: 192.168.180.212
[0d00h00m15s] 2023-05-01T06:13:03 <DBG> [SNTP] Waiting for system time to be set... 5/10
[0d00h00m17s] 2023-05-01T06:13:05 <DBG> [SNTP] Waiting for system time to be set... 6/10
[0d00h00m19s] 2023-05-01T06:13:07 <DBG> [SNTP] Waiting for system time to be set... 7/10
[0d00h00m21s] 2023-05-01T06:13:10 <DBG> [SNTP] Waiting for system time to be set... 8/10
[0d00h00m23s] 2023-05-01T06:13:12 <DBG> [SNTP] Waiting for system time to be set... 9/10
**[0d00h00m25s] 2023-05-01T06:13:14 <DBG> [MAIN] Manual Time Sync failed during startup**
[0d00h00m25s] 2023-05-01T06:13:14 <INF> [MAIN] Device info: CPU cores: 2, Chip revision: 300
[0d00h00m25s] 2023-05-01T06:13:14 <INF> [MAIN] SD card info: Name: SD32G, Capacity: 30436MB, Free: 30386MB
[0d00h00m27s] 2023-05-01T06:13:16 <INF> [MAIN] Initialization completed successfully! Starting flow task ...
[0d00h00m27s] 2023-05-01T06:13:16 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m27s] 2023-05-01T06:13:16 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m29s] 2023-05-01T06:13:18 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m35s] 2023-05-01T06:13:23 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m35s] 2023-05-01T06:13:23 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m35s] 2023-05-01T06:13:23 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m35s] 2023-05-01T06:13:24 <DBG> [MAIN SERVER] info_get_handler
[0d00h00m41s] 2023-05-01T06:13:29 <DBG> [OTA FILE] log_get_last_part_handler
[0d00h00m41s] 2023-05-01T06:13:30 <INF> [SNTP] Time is synced with NTP Server pool.ntp.org: 2023-05-01 06:13:30
[0d00h01m17s] 2023-05-01T06:14:06 <DBG> [MAIN SERVER] info_get_handler
[0d00h01m27s] 2023-05-01T06:14:16 <DBG> [OTA FILE] download_get_handler
[0d00h01m27s] 2023-05-01T06:14:16 <DBG> [OTA FILE] download_get_handler
[0d00h02m23s] 2023-05-01T06:15:12 <DBG> [MAIN SERVER] info_get_handler
[0d00h02m28s] 2023-05-01T06:15:16 <DBG> [OTA FILE] download_get_handler
[0d00h02m28s] 2023-05-01T06:15:17 <DBG> [OTA FILE] download_get_handler
[0d00h02m42s] 2023-05-01T06:15:31 <DBG> [MAIN SERVER] info_get_handler
[0d00h02m47s] 2023-05-01T06:15:36 <DBG> [OTA FILE] log_get_last_part_handler
[0d00h05m09s] 2023-05-01T06:17:58 <DBG> [MAIN SERVER] info_get_handler
[0d00h05m21s] 2023-05-01T06:18:10 <DBG> [MAIN SERVER] info_get_handler
[0d00h05m21s] 2023-05-01T06:18:10 <DBG> [MAIN SERVER] info_get_handler
[0d00h05m21s] 2023-05-01T06:18:10 <DBG> [MAIN SERVER] info_get_handler
[0d00h05m22s] 2023-05-01T06:18:11 <DBG> [MAIN SERVER] info_get_handler
[0d00h05m27s] 2023-05-01T06:18:16 <DBG> [PSRAM] Allocated 128004 bytes in PSRAM for 'ALIGN->AlgROI'
**[0d00h05m27s] 2023-05-01T06:18:16 <ERR> [C IMG BASIS] /sdcard/img_tmp/raw.jpg is empty!**
[0d00h05m27s] 2023-05-01T06:18:16 <DBG> [PSRAM] Allocating Tensor Arena (819200 bytes, use shared memory in PSRAM)...
[0d00h05m27s] 2023-05-01T06:18:16 <DBG> [TFLITE] CTfLiteClass::LoadModel
[0d00h05m27s] 2023-05-01T06:18:16 <DBG> [TFLITE] CTfLiteClass::ReadFileToModel: /sdcard
[0d00h05m27s] 2023-05-01T06:18:16 <DBG> [TFLITE] Loading Model /sdcard /size: 0 bytes...
[0d00h05m27s] 2023-05-01T06:18:16 <DBG> [PSRAM] Allocating Model memory (1363148 bytes, use shared memory in PSRAM)...
[0d00h05m27s] 2023-05-01T06:18:16 <DBG> [TFLITE] CTfLiteClass::MakeAllocate
[0d00h00m00s] 2023-05-01T04:18:18 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-01T04:18:18 <INF> [MAIN] ==================== Start ======================
[0d00h00m00s] 2023-05-01T04:18:18 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-01T04:18:18 <INF> [MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m00s] 2023-05-01T04:18:18 <INF> [MAIN] Total heap: 4377075 byte
[0d00h00m04s] 2023-05-01T04:18:22 <INF> [MAIN] Camera info: PID: 0x26, VER: 0x42, MIDL: 0x7f, MIDH: 0xa2
[0d00h00m04s] 2023-05-01T04:18:22 <INF> [SDCARD] Basic R/W check started...
[0d00h00m04s] 2023-05-01T04:18:22 <INF> [SDCARD] Basic R/W check successful
[0d00h00m04s] 2023-05-01T04:18:22 <INF> [SNTP] TimeServer not defined, using default: pool.ntp.org
[0d00h00m04s] 2023-05-01T04:18:22 <INF> [SNTP] Configuring NTP Client...
[0d00h00m04s] 2023-05-01T06:18:22 <INF> [SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m04s] 2023-05-01T06:18:22 <INF> [SNTP] Time is already set: 2023-05-01 06:18:22
[0d00h00m04s] 2023-05-01T06:18:22 <INF> [MAIN] CPU frequency: 160 MHz
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [SDCARD] Folder/file presence check started...
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [SDCARD] Folder/file presence check successful
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [MAIN] Tag: 'v15.2.1', Release: v15.2.1 (Commit: b24b7d5), Date/Time: 2023-04-27 20:44, Web UI: Release: v15.2.1 (Commit: b24b7d5)
**[0d00h00m05s] 2023-05-01T06:18:23 <WRN> [MAIN] Reset reason: Exception/panic
[0d00h00m05s] 2023-05-01T06:18:23 <WRN> [MAIN] Device was rebooted due to a software exception! Log level is set to DEBUG until the next reboot. Flow init is delayed by 5 minutes to check the logs or do an OTA update
[0d00h00m05s] 2023-05-01T06:18:23 <WRN> [MAIN] Keep device running until crash occurs again and check logs after device is up again**
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [LOGFILE] Set log level to DEBUG
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [WLANINI] SSID: Gateway
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [WLANINI] Hostname: Wasserzaehler
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [WLANINI] RSSIThreshold: 0
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [MAIN] WLAN config loaded, init WIFI...
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [WIFI] Automatic interface config --> Use DHCP service
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [WIFI] Set hostname to: Wasserzaehler
[0d00h00m05s] 2023-05-01T06:18:23 <INF> [WIFI] Init successful
[0d00h00m07s] 2023-05-01T06:18:25 <DBG> [SNTP] Waiting for system time to be set... 1/10
[0d00h00m07s] 2023-05-01T06:18:26 <WRN> [WIFI] Disconnected (202, Auth fail)
[0d00h00m09s] 2023-05-01T06:18:27 <DBG> [SNTP] Waiting for system time to be set... 2/10
[0d00h00m10s] 2023-05-01T06:18:28 <WRN> [WIFI] Disconnected (205)
[0d00h00m11s] 2023-05-01T06:18:29 <DBG> [SNTP] Waiting for system time to be set... 3/10
[0d00h00m12s] 2023-05-01T06:18:31 <INF> [WIFI] Connected to: Gateway, RSSI: -46
[0d00h00m13s] 2023-05-01T06:18:31 <DBG> [SNTP] Waiting for system time to be set... 4/10
[0d00h00m13s] 2023-05-01T06:18:32 <INF> [WIFI] Assigned IP: 192.168.180.212
[0d00h00m15s] 2023-05-01T06:18:33 <DBG> [SNTP] Waiting for system time to be set... 5/10
[0d00h00m17s] 2023-05-01T06:18:35 <DBG> [SNTP] Waiting for system time to be set... 6/10
[0d00h00m19s] 2023-05-01T06:18:37 <DBG> [SNTP] Waiting for system time to be set... 7/10
[0d00h00m21s] 2023-05-01T06:18:39 <DBG> [SNTP] Waiting for system time to be set... 8/10
[0d00h00m23s] 2023-05-01T06:18:41 <DBG> [SNTP] Waiting for system time to be set... 9/10
[0d00h00m25s] 2023-05-01T06:18:43 <DBG> [MAIN] Manual Time Sync failed during startup
[0d00h00m25s] 2023-05-01T06:18:43 <INF> [MAIN] Device info: CPU cores: 2, Chip revision: 300
[0d00h00m25s] 2023-05-01T06:18:43 <INF> [MAIN] SD card info: Name: SD32G, Capacity: 30436MB, Free: 30386MB
[0d00h00m27s] 2023-05-01T06:18:45 <INF> [MAIN] Initialization completed successfully! Starting flow task ...
[0d00h00m39s] 2023-05-01T06:18:57 <INF> [SNTP] Time is synced with NTP Server pool.ntp.org: 2023-05-01 06:18:57
[0d00h01m54s] 2023-05-01T06:20:12 <DBG> [OTA FILE] download_get_handler
**[0d00h01m57s] 2023-05-01T06:20:15 <ERR> [OTA FILE] File sending failed!**
[0d00h01m57s] 2023-05-01T06:20:16 <DBG> [MAIN SERVER] info_get_handler
[0d00h02m02s] 2023-05-01T06:20:21 <DBG> [OTA FILE] log_get_last_part_handler
[0d00h02m19s] 2023-05-01T06:20:38 <DBG> [MAIN SERVER] info_get_handler
[0d00h02m24s] 2023-05-01T06:20:42 <DBG> [OTA FILE] log_get_last_part_handler

**Comment by caco3** [comment] 2023-05-01 21:05
> "http://192.168.xx.xx/sysinfo" in the browser, the ESP crashes immediately

I can confirm this! We will have a look on it in https://github.com/jomjol/AI-on-the-edge-device/issues/2380

**Comment by caco3** [comment] 2023-05-01 21:07
> I also can´t take a new reference image

This just got fixed in v15.2.2

**Comment by caco3** [comment] 2023-05-01 21:35
> > "http://192.168.xx.xx/sysinfo" in the browser, the ESP crashes immediately
> 
> I can confirm this! We will have a look on it in #2380

Fixed in https://github.com/jomjol/AI-on-the-edge-device/pull/2381

**Comment by caco3** [comment] 2023-05-01 21:44
We just released [v15.2.3](https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v15.2.3) which contains some bug fixes.

I think this bug report here covers more than one issues, some or all might be fixed by now. Please test the latest release and create a **new** bug report (separate for each issue) if you still have issues!

This issue gets closed now.

**Closed by caco3** 2023-05-01 21:44 UTC
Labels: bug

**Comment by caco3** [comment] 2023-05-08 17:30
> Still got the same error on v15.2.4

>> Please test the latest release and create a new bug report (separate for each issue) if you still have issues!

**Comment by juhnu1** [comment] 2024-05-10 12:20
did you solve this?

**Comment by juhnu1** [comment] 2024-05-10 12:20
I just got the same...

**Comment by SybexX** [comment] 2024-05-10 13:28
@juhnu1 which version are you using or which version do you want to install?
