### ISSUE TITLE
SD-Card is locked

### ISSUE THREAD

**Issue by Gnocci1** [jomjol/AI-on-the-edge-device#312] opened 2021-08-13 11:52 UTC
Hi,

we're still facing the problem, that our ESP32-Cam is not able to read the Wifi data from Wlan.ini.
The serial monitor prints an error-code "File is locked" which we found in the directory jomjol_helper helper.cpp. Our Problem now is, that we don't understand what the code is doing beginning from line 80. 

FILE* OpenFileAndWait(const char* nm, char* _mode, int _waitsec)
{
	FILE *pfile = fopen(nm, _mode);

	if (pfile == NULL)
	{
		TickType_t xDelay;
		xDelay = _waitsec * 1000 / portTICK_PERIOD_MS;
		std::string zw = "File is locked: " + std::string(nm) + " - wait for " + std::to_string(_waitsec);
	    printf(zw.c_str());
		printf("\n");
		LogFile.WriteToFile(zw);      
		vTaskDelay( xDelay );
		pfile = fopen(nm, _mode);
	}
	return pfile;
}

We don't know why the code sees our data from Wlan.ini as "NULL". 
We adapted the Wlan.ini as requested here.
Our SD Card is formatted as FAT32 and we copied the SD-Card folder on it, changing the Wlan.ini.

Please don't delete this issue again without solving the Problem.

Greetings

[seriell.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6982241/seriell.txt)

**Comment by jomjol** [comment] 2021-08-13 15:18
Hi, 
let me give some informations:
The error message and the serial log tells, that the sd-card can be initiated, but the very first attempt to open a file (wlan.ini) fails. The part of code you cited does nothing else, than opening a file with name "_nm" in the mode "_mode". If this fails (pFile == NULL), it waits for "_waitsec" and tries it a second time. If this also fails, it returns a "NULL". Then the software fails, because without "wlan.ini" nothing will work.

Clearly the problem is a hardware related problem of the combination of ESP32 and SD-card in your specific case. It could be:
- incompatibily of sd-card type and ESP32 - common problem, no other solution, than trying different sd-card types.
Reported several times from different users.
- defect of file system --> format sd-card and try again - I assume, you have testet it already
- defect of sd-card reader - never heared of that, but not impossible

I can only recommend to test one of these. From the software code I do not know or see any change to solve it. 

**Therefore I will keep this issue open for some days for further disussion, but later on close it again.**

**Comment by Gnocci1** [comment] 2021-08-14 14:41
Hi,

thank you for your response. 
We did try 3 different SD-Cards already without success. 
You assumed correct, that we also tried formatting the SD-Cards many times.

We have no other idea, but try buying new ESP32-Cams...

**Comment by Gnocci1** [comment] 2021-08-14 14:45
I just saw in the main.cpp, that there are options for initializing the SD-Card in 1-line mode and / or without card detect and write protect signals. Could this have something to do with our issue?

Greetings and thanks in advance

**Comment by jomjol** [comment] 2021-08-14 14:56
You can use the sd-card also in the 4-wire connection. But this limits the use of other GPIOs. Therefore I don't use it. But you could make a fork and test, if another mode is helping in your case.

**Comment by Gnocci1** [comment] 2021-08-17 12:21
Hi again,

we tried to check, if the SD-Cards would work with an Arduino sketch and we had full success. We were able to take pictures and save them onto the SD-Card. So I guess that it is not a hardware related problem anymore... 

The Arduino sketch we used, was a standard sketch from the library.
Any ideas?

**Comment by jomjol** [comment] 2021-08-17 15:40
Hi @Gnocci1,

thanks for sharing your result. Unfortunatly I have to tell, that this is not surprising to me. There are different ways and modes to access the sd card. In the watermeter I need to use the one wire mode, because a lot of the GPIOs are used by: OV2640, LED-flash and external GPIO. Therefore I cannot use the 4 wire mode, which would be more stable and could maybe handle more kinds of cards.

I have tested about a dozen sd-cards with the 1- and the 4-wire mode and can confirm, that some of these cards are only working in 4-wire mode and some of them are not at all! Unfortunately I have not figured out, what is the parameter.

That the Arduiono sketch is working is also not supring from another point of view:  I assume, you did not integrate the OV2640, flash LED and GPIO12/13 for external access in the test code? Also the Arduino library might use different sd-card drivers in the background, than the espressif32 environment.

Therefore thanks for you further investigation, but I still don't see, how I could solve this within my code. Solutions are very welcome, but I'm running out of ideas!

Best regards,
  jomjol

**Comment by jomjol** [comment] 2021-08-20 05:48
@Gnocci1: do you have further results? Otherwise I tend to put this issue to closed?

**Closed** 2021-08-29 19:04 UTC
