### ISSUE TITLE
<ERR> [OTA FILE] File sending failed!

### ISSUE THREAD

**Issue by A380Coding** [jomjol/AI-on-the-edge-device#2939] opened 2024-02-19 13:24 UTC
### The Problem

I'm trying to capture a new reference image but the device restarts. In the logs I get the entry "<ERR> [OTA FILE] File sending failed!" But I'm not performing an OTA update.

### Version

15.7.0

### Logfile

```shell
<WRN> [MAIN] Reset reason: Exception/panic
<WRN> [MAIN] Device was rebooted due to a software exception! Log level is set to DEBUG until the next reboot. Flow init is delayed by 5 minutes to check the logs or do an OTA update
<WRN> [MAIN] Keep device running until crash occurs again and check logs after device is up again

and then:
<ERR> [OTA FILE] File sending failed!
```

### Additional Context

When hitting "create new reference" button, the black screen saying "Taking image" shows up but the device restarts.

**Comment by SybexX** [comment] 2024-02-19 15:46
Did you also put the SD-card files from v15.7.0 on it?
There is a certain dependency between the firmware and the SD-card files and if the two do not match, it can lead to errors.

**Comment by A380Coding** [comment] 2024-02-19 16:04
I updated to 15.7.0 via OTA Updater and the *update.zip file as usual. As far as I know this is fine.
I checked the SD-Card which is also fine.

**Comment by pipip** [comment] 2024-02-19 22:00
Same issue here. After the update to 15.7.0 the alignment of my ROI where messed up. Taking a nenew reference image caused the device to crash.

I downgraded to 15.6.0 and everything (including taking a new reference image) works fine.

**Comment by caco3** [comment] 2024-02-20 18:51
Duplicate of https://github.com/jomjol/AI-on-the-edge-device/issues/2940

**Closed by caco3** 2024-02-20 18:51 UTC
Labels: bug
