### ISSUE TITLE
digit position ok but Thumbnail not correct, no results

### ISSUE THREAD

**Issue by martinpeterbauer** [jomjol/AI-on-the-edge-device#1140] opened 2022-10-06 20:30 UTC
Using:
HEAD, dfe2c46, v12.0.1
v12.0.1

the problem:

The Thumbnail of a digit is trash ... see picture

![2022-10-06 22 21 43](https://user-images.githubusercontent.com/31488767/194412119-64efdd3c-e36a-4a4e-a010-60df728a2275.jpg)

![2022-10-06 22 21 50](https://user-images.githubusercontent.com/31488767/194412288-2687bf34-0f08-496d-a183-6e73002fdec3.jpg)

Hint: i am a newbie - very first try ...

**Comment by martinpeterbauer** [comment] 2022-10-06 20:44
here a more sharper example

![2022-10-06 22 42 23](https://user-images.githubusercontent.com/31488767/194414961-fdfcc5c9-ff76-4610-80c8-534be0ca32ad.jpg)

**Comment by bseibold** [comment] 2022-10-07 22:30
I can confirm, same commit, same issue.
![image](https://user-images.githubusercontent.com/383851/194671249-6d76f830-4bbb-4894-a56d-fab16c9e5d71.png)
![image](https://user-images.githubusercontent.com/383851/194671175-1c8ea5ec-f314-4cf3-a8c9-8fc92f2471d7.png)

**Comment by martinpeterbauer** [comment] 2022-10-08 08:26
I think the real issue is the "reference" markers - not been recognised - as seen the small red dots which should be a rectangle ...

**Comment by jomjol** [comment] 2022-10-08 08:59
please post your `config.ini` to check the settings for the references.

**Comment by martinpeterbauer** [comment] 2022-10-08 09:22
Here is the latest config and the latest 'reference' picture... 

![raw_20221008-111544](https://user-images.githubusercontent.com/31488767/194700270-937d016b-26f5-4f4c-b0b9-01738705c975.jpg)

and the config:

[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 100
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 0
InitialMirror = false
SearchFieldX = 200
SearchFieldY = 200
AlignmentAlgo = highAccuracy
FlipImageSize = false
/config/ref0.jpg 28 151
/config/ref1.jpg 13 404

[Digits]
Model = /config/dig-class100-0130_s2_q.tflite
CNNGoodThreshold = 0.5
LogImageLocation = /log/digit
LogfileRetentionInDays = 3
main.dig1 337 217 47 92 false
main.dig2 278 217 51 92 false
main.dig3 224 216 46 94 false
main.dig4 168 217 46 95 0
main.dig5 109 219 46 94 0

;[Analog]
Model = /config/ana-cont_11.3.0_s2.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.ana1 432 230 92 92 false
main.ana2 379 332 92 92 false
main.ana3 283 374 92 92 false
main.ana4 155 328 92 92 false

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
;main.MaxRateType = AbsoluteChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false

;[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD
;SetRetainFlag = true

;[InfluxDB]
;Uri = undefined
;Database = 
;Measurement = undefined
;user = undefined
;password = undefined

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false

**Comment by martinpeterbauer** [comment] 2022-10-08 09:24
and the two ref ... 

![ref0](https://user-images.githubusercontent.com/31488767/194700367-25085c6a-d879-4fc5-8073-f016807c2c04.jpg)
![ref1](https://user-images.githubusercontent.com/31488767/194700371-242d1ce5-3035-46ac-8172-5fa9f1e7de30.jpg)

**Comment by martinpeterbauer** [comment] 2022-10-08 09:33
and this is a picture which fails ... 

![raw_20221008-113106](https://user-images.githubusercontent.com/31488767/194700773-eaf862f5-d433-4d71-8ba5-377df2eb4e7d.jpg)

**Comment by martinpeterbauer** [comment] 2022-10-08 11:40
I have done some more tests - its defenitly the reference - if the reference is not found it is not working despite the fact that the digits frame is perfectly allinged in the picture ... 

Why does it nee such a 'reference' ? The cameras position is fixed - no need for such a reference. Maybe this reference feature cold be made optional for people with moving cameras ...

**Comment by caco3** [comment] 2022-10-08 12:06
I can't tell you why it is is needed,but I added a task to add some validation: https://github.com/jomjol/AI-on-the-edge-device/issues/1148

**Comment by jomjol** [comment] 2022-10-08 13:19
The reference is used to correct for minor movements of the camera. Usually you need to remove it from time to time, e.g. if somebody officially comes to read the meter, or if you remove it because you need to flash something or read out the sd-card.

If we would not need a reference, than you would be forced to teach the whole system from the beginning again every time you mvoe it (even a slight changes alignment of about 2-3 pixel can cause already misreadings).

I close this image and we can discuss possible checks in the issue made by caco3.

**Closed by jomjol** 2022-10-08 13:19 UTC
