### ISSUE TITLE
Incorrect combined readout when using Digital + Analog ROIs, individual numbers recognized correctly

### ISSUE THREAD

**Issue by Plawasan** [jomjol/AI-on-the-edge-device#921] opened 2022-08-19 07:02 UTC
First of all let me say that the last update (running master - v11.0.0 - 2022-08-13) is a massive improvement, for me it made a difference between getting a result maybe in 1 out of 5 readings to pretty much perfect results everytime. I did notice one issue though:

If I only use digital ROIs, I get a correct result, down to the last decimal implied from the rotation of the digits:

![image](https://user-images.githubusercontent.com/73796046/185560609-b12edc1f-96d1-491c-b3b1-beb40e000f42.png)

However, when I add the analog ROI to this to make it even more precise, I get wrong results even though each digits is still recognized correctly:

![image](https://user-images.githubusercontent.com/73796046/185561928-1c334996-505d-448a-aa24-1a1fe335b1af.png)

![image](https://user-images.githubusercontent.com/73796046/185561688-fb7ef840-8c17-42b3-97db-95883c625b94.png)

Looks to me like the issue is not in the OCR but rather in the logic of combining the inputs from Digital and Analog ROIs.

Thanks!

**Comment by Plawasan** [comment] 2022-08-19 07:54
For the record, same thing happens on my other meter:

all digits recognized correctly:

![image](https://user-images.githubusercontent.com/73796046/185570812-1be3c323-23b3-4e76-b426-597b8228d80b.png)
(Value should be: 167.73462)

however the last digital ROI is then 1 higher than it should be when the inputs are combined:

![image](https://user-images.githubusercontent.com/73796046/185570999-565811b5-a94e-4765-bb7a-5dc381cc9ef7.png)

**Comment by haverland** [comment] 2022-08-19 13:54
@jomjol ClassFlowCNNGenerial.cpp:195

if ((zahl_vorgaenger >= 0.5 ) && (zahl_vorgaenger < 9.0))
    {
        // kein Ziffernwechsel, da Vorkomma weit genug weg ist (0+/-0.5) --> zahl wird gerundet
        return ((int) round(zahl) + 10) % 10;
    }  
    
Im wondering if a 
  return ((int) trunc(zahl) + 10) % 10;
  
  would be better. But I'am not sure on side effects.

**Comment by caco3** [comment] 2022-08-20 14:55
I see exactly the same issue on my last digital digit: https://github.com/jomjol/AI-on-the-edge-device/issues/923

**Comment by jomjol** [comment] 2022-08-21 15:34
Implemted in version 11.1.0

**Comment by Plawasan** [comment] 2022-08-21 19:03
Sorry to be a pest... upgraded to 11.1.0 but still no bueno, the problem seems to have shifted one digit up:

all ROIs correct, RAW number is incorrect:
![image](https://user-images.githubusercontent.com/73796046/185806709-88f923ba-ba90-47f0-bd8a-1d873e7b0ead.png)

![image](https://user-images.githubusercontent.com/73796046/185806698-aeb556d4-0875-4058-a15e-88e3aca4f6fd.png)

This time with/without the Analog ROI makes no difference, this is with it disabled:

![image](https://user-images.githubusercontent.com/73796046/185806796-a5d7457b-32e6-4c17-bf68-c7afd587e06b.png)

![image](https://user-images.githubusercontent.com/73796046/185806808-4550ca38-79eb-4f35-a9af-514f4100b2e5.png)

**Comment by jomjol** [comment] 2022-08-21 19:15
I agree, problem is still present. Quick fix did not solve the problem.
I'm working on it, but maybe might take a bit more time.

**Comment by jomjol** [comment] 2022-08-21 19:35
Just uploaded one last rolling version for today - with a new algo (analog brand new and digital partially).

@haverland: fyi

Please use and test. It has also an extended logging switch on. This will help to debug the algo.
'
afk for next 20h

**Comment by haverland** [comment] 2022-08-21 20:40
Im working on it currently. The readout needs another variable of the last ROI->float_result and reducing to <9.0 was not a good idea. 
The fix will take a bit. I add testing cases for post-process too.

**Comment by Plawasan** [comment] 2022-08-22 17:27
I hate to be that guy.... but....11.1.1 still doesn't get it quite right:

![image](https://user-images.githubusercontent.com/73796046/185982385-fc8a0be0-504b-4f00-95de-3d4c86c2e6da.png)


![image](https://user-images.githubusercontent.com/73796046/185982526-139a3a09-3fd9-4026-8629-5426f7ff59f1.png)

**Comment by haverland** [comment] 2022-08-22 18:14
I've not see the failure. 
Smale differences like 96 97 is another issue, but it's ok. Is in the fault tolerance of the neuronal network models.

**Comment by haverland** [comment] 2022-08-22 18:23
@Plawasan What kind of model you use for analog pointer? It's a 9.0 and not 9.7. It should not so much differences.

**Comment by Plawasan** [comment] 2022-08-22 18:24
That I'm not worried about however the result in the screenshot above should be 377.08397, not 377.08497 - it's off by 1 on the last digital ROI.

**Comment by haverland** [comment] 2022-08-22 18:43
OK, now I know what you mean.

**Comment by jomjol** [comment] 2022-08-22 18:53
What kind of firmware do you use? 

In the version 11.0.0 and 11.1.0 is a bug in the transition from analog pointers to digital values. It is improved in the today released version 11.1.1

**Comment by Plawasan** [comment] 2022-08-22 19:14
> What kind of firmware do you use?
> 
> In the version 11.0.0 and 11.1.0 is a bug in the transition from analog pointers to digital values. It is improved in the today released version 11.1.1

That's what I'm on:

![image](https://user-images.githubusercontent.com/73796046/186000523-e5f686ff-f096-4342-ad90-2c1b93fc3a04.png)

**Comment by jomjol** [comment] 2022-08-22 19:28
then you found a bug :-). Needs to be tested.

**Comment by Plawasan** [comment] 2022-08-28 20:58
Just installed 11.2.0... got another bad result from a good recognition:

![image](https://user-images.githubusercontent.com/73796046/187094261-0f7039c9-8f52-4e4c-a70d-ab3d1667d2cb.png)


![image](https://user-images.githubusercontent.com/73796046/187094226-33ca2bfc-1f49-4525-ac44-1f8baf221726.png)

**Comment by cbho** [comment] 2022-08-29 05:26
Unfortunately also here:
![image](https://user-images.githubusercontent.com/29979509/187128572-573f90b3-e63f-493e-a6f3-0c2a00f0d251.png)

Version: master - v11.2.0 - 2022-08-28
HTML version 15.1.0

(Parts of the) Config:
[Digits]
Model = /config/dig-cont_0570_s3.tflite
CNNGoodThreshold = 0.5

[Analog]
Model = /config/ana-class100_0120_s1_q.tflite

[PostProcessing]
m3.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 3600
AllowNegativeRates = false
m3.MaxRateValue = 1
m3.MaxRateType = AbsoluteChange
;m3.ExtendedResolution = false
m3.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = true

**Comment by haverland** [comment] 2022-08-29 14:18
> Unfortunately also here: ![image](https://user-images.githubusercontent.com/29979509/187128572-573f90b3-e63f-493e-a6f3-0c2a00f0d251.png)
> 
> Version: master - v11.2.0 - 2022-08-28 HTML version 15.1.0
> 
> (Parts of the) Config: [Digits] Model = /config/dig-cont_0570_s3.tflite CNNGoodThreshold = 0.5
> 
> [Analog] Model = /config/ana-class100_0120_s1_q.tflite
> 
> [PostProcessing] m3.DecimalShift = 0 PreValueUse = true PreValueAgeStartup = 3600 AllowNegativeRates = false m3.MaxRateValue = 1 m3.MaxRateType = AbsoluteChange ;m3.ExtendedResolution = false m3.IgnoreLeadingNaN = true ErrorMessage = true CheckDigitIncreaseConsistency = true

Looks more like a recognition issue. The current raw is ok, but there was a previous read, that had set the 8.

**Comment by cbho** [comment] 2022-08-29 17:35
Absolutely possible, of course, although when I look at the graphs in Home Assistant, I think it's the other thing that's happening.
I'll make some additional sensors in Home Assitant and monitor Value, Previous Value and Raw and see if I can add anything of value :-)

**Comment by haverland** [comment] 2022-08-31 16:17
<img width="670" alt="image" src="https://user-images.githubusercontent.com/412645/187727756-389c4927-e8a1-4d47-a198-1a4a43ef0f39.png">

<img width="952" alt="image" src="https://user-images.githubusercontent.com/412645/187727886-3356036d-a305-461f-82dd-406526a11da5.png">

Should be a 78.99996, isn't it?

**Comment by jomjol** [comment] 2022-08-31 17:36
You are right. The problem is the various types of counters. I need 7-9 parameters to model the transition.
I decided to go for a model based algorithm for the transistion. But this will take quite some time.

**Comment by Wingsofcourage** [comment] 2022-09-03 13:20
I'm on version
<img width="509" alt="Screenshot 2022-09-03 at 15 17 12" src="https://user-images.githubusercontent.com/9435491/188272162-82ced097-94c8-4c4f-893c-cff415a110e5.png">

And things getting better. 
But now the first number is a "2" even if the recognition tells me a "3.1"
<img width="305" alt="Screenshot 2022-09-03 at 15 18 27" src="https://user-images.githubusercontent.com/9435491/188272208-d39d54a1-1043-4a11-b303-65e107f181ff.png">
<img width="287" alt="Screenshot 2022-09-03 at 15 18 44" src="https://user-images.githubusercontent.com/9435491/188272217-8389e138-c73a-42b5-876a-39f0f49f5bf7.png">

Any thoughts ?

**Comment by jomjol** [comment] 2022-09-03 13:52
The problem is the 9.1 in the previous value. Therefore the algo thinks, that the next number is already in the moving situation and has not crossed "0" yet.
This is really a problem as almost every counter is starting to rotate the next number at a different value. It needs to be parametrized, but this is quite some modeling effort (not programming, but finding a general and easy to adjust model).

**Comment by haverland** [comment] 2022-09-03 14:08
But 3.1 is over 0. Here should not be an incomplete transition detected. I make a test case.

**Comment by jomjol** [comment] 2022-09-03 16:09
@Haverland: there are also digits, that have an offset. In this case the unrotated number is e.g. 3.2. Therefore a 3.1 can still be before "0" crossing.

**Comment by pos-ei-don** [comment] 2022-09-03 16:18
> @haverland: there are also digits, that have an offset. In this case the unrotated number is e.g. 3.2. Therefore a 3.1 can still be before "0" crossing.

I have such a Meter, which is my early rotator. I have an late rotator as well which still Shows 9.0 in the Digital when the analog already crossed the "0".therefore I suggest a cobfigurable "offset" value which could be just added/subtracted to the recognised value

**Comment by haverland** [comment] 2022-09-03 17:49
> > @haverland: there are also digits, that have an offset. In this case the unrotated number is e.g. 3.2. Therefore a 3.1 can still be before "0" crossing.
> 
> I have such a Meter, which is my early rotator. I have an late rotator as well which still Shows 9.0 in the Digital when the analog already crossed the "0".therefore I suggest a cobfigurable "offset" value which could be just added/subtracted to the recognised value

Your case should be calculated properly. I hope we do not need a configurable value for it. It should be easy to use for Users.

**Comment by dl6dbh** [comment] 2022-09-08 18:16
How did you get such a razor sharp picture? My pictures don't turn out that well.

**Comment by Plawasan** [comment] 2022-09-08 18:28
> How did you get such a razor sharp picture? My pictures don't turn out that well.

Did you adjust the focus of the camera lens? It needs a bit of force to rotate it ccw a get it to focus closer.

**Comment by stefanbode** [comment] 2022-09-09 05:31
Regarding rotate of the digital values: The mechanic of these meters are finally connected to the LAST digit. That means if the last digit is still at 8 or 7 all other digits before will NOT start to move. As soon as the LAST digit is at 9 or further all digits before start moving too. Therefore a 19998.5 is stable at the first 4 digits. every 8.9 or 9.2 is a 9.
If the last digit is a 9 the movement will start. If you take this into consideration I believe you will get away from some of your problems.

**Comment by stefanbode** [comment] 2022-09-09 05:46
I take a look at process_doFlow() and I assume this is where you generate the final number. As a human you would not start with the largest value and then go to the smaller ones. You would do it quite vise versa. Because if the lower value is as 2.5 then you KNOW that the next higher must be something at x.0 to x.4 (+-0.2 deviation). If the reading is 8.8 or 8.9 you're 100% sure it must be a 9. This will also solve your 9 problem. If the before reading is a 0.9 and the digit is 7.8 you're now even sure this must be a 8.9 and not a 7.9.

**Comment by stefanbode** [comment] 2022-09-09 09:44
Another comment on the analog wheels of the water-meter. These are connected through gears. That means the movement of ALL gears is continuous. Therefore the evaluation of these ones is different to the digital ones.

**Comment by stefanbode** [comment] 2022-09-10 13:34
![image](https://user-images.githubusercontent.com/16225290/189485734-26feebf5-0b07-438a-8053-5b794263f967.png)
Something for regression. Used current development build form yesterday. All digits correctly scanned but value is wrong: 32290.420. should be 32289.420

**Comment by haverland** [comment] 2022-09-10 15:11
Mhh.. with current rolling it should run fine. Did you set CheckDigitIncreaseConsistency = true?

**Comment by stefanbode** [comment] 2022-09-10 20:01
CheckDigitIncreaseConsistency is new to me. I can check for it. Anyhow my assumption is that we calculate the rolling false. Only the 9er rolls and the digit before the last 9. all other values are not touched by the rolling. I find the code where this is calculated. Maybe can send a PR soon. 
Im this case the rolling stops at the 2. the 8 and the 9 will never be effected by rolling because the digit changing is 1 to a 2.

**Comment by jomjol** [comment] 2022-09-10 20:56
@stefanbode : please be very careful with adopting the changing the code for the rolling calculation. There are a variety of counters out there. E.g. 
* early runner, late runner (roll over of number earlier or later than expected) 
* or a larger spread while rolling (start rolling with previous number only at 7/8 and rolling until 2/3) 
* zero point not beeing at x.0, but (x-1).8 or x.1

This is still part of some work and a more sophisticated modelling is in my head, but needs some more time and then extensive testing to be transfered in code.

**Comment by caco3** [comment] 2022-09-10 21:07
@stefanbode Thats odd. I also have a BK-G4 and I never see half digits:
![grafik](https://user-images.githubusercontent.com/1783586/189501732-767a7a70-e915-439d-a5ef-140d6e5120ef.png)

There seem to be different implementations of the counter (mine gauge is from a swiss vendor).

**Closed** 2022-09-17 08:11 UTC
