### ISSUE TITLE
Content-Length weirdness

### ISSUE THREAD

**Issue by RobThree** [jomjol/AI-on-the-edge-device#2338] opened 2023-04-19 20:08 UTC
### The Problem

When retrieving JSON from the REST API with PHP the request hangs/freezes. After some trial and error I can reproduce it and have a workaround.

This fails:
```php
// "Hangs":
$reading = file_get_contents('http://watermeter.example.com/json');
```

This works:
```php
$url = 'http://watermeter.example.com/json';
$headers = get_headers($url, true);
$content_length = intval($headers["Content-Length"]);
// Works by specifying the exact length to read:
$reading =file_get_contents($url, NULL, NULL, NULL, $content_length);
```

### Version

v15.1.1 (Commit: 03c84a1+)

### Logfile

```shell
N/A
```

### Expected Behavior

I'm not sure what the issue is but I use `file_get_contents` on dozens of hosts; this is the only one (reproducibly) failing every time. I'm running PHP 8.1.13 by the way. I suspect the ESP32 not closing the connection (correctly)?

### Additional Context

Since the [InfluxDB1 appears to be broken currently](https://github.com/jomjol/AI-on-the-edge-device/issues/2203) I was trying to implement a (temporary) workaround by scheduling a PHP script as a cronjob to retrieve the reading and insert the values into InfluxDB from PHP. This is when I ran into the problem described above.

**Comment by caco3** [comment] 2023-04-23 13:53
I can confirm this issue. And our project seems not to be the only one with this issue.
According to https://bugs.php.net/bug.php?id=80931 this is an issue of `file_get_contents()` in PHP 8.

The suggested workaround by applying a timeout worked for me:
```php
<?php

$context = stream_context_create(array(
    "http" => array(
        "timeout" => 2
    )
));

$reading = file_get_contents('http://192.168.1.151/json', 0, $context);

echo($reading);
?>
```

PHP 8 seems not to be able to handle the way the internal webserver closes the connection.
Since it works with older PHPs and the common webbrowser s and CURL, I am closing this issue as it is minor and should be improved in PHP.

**Closed by caco3** 2023-04-23 13:53 UTC
Labels: bug
