### ISSUE TITLE
Store daily raw images instead of all of them

### ISSUE THREAD

**Issue by pgrm** [jomjol/AI-on-the-edge-device#3378] opened 2024-11-07 22:30 UTC
Great product, setup of the water meter was straightforward. Currently, I'm exporting the data to HA, but I'd like to keep once a day a raw image on the device for potential sanity checks in the future.

I understand the current config only allows keeping all the images or none of them. Instead, I'd like the option to keep a daily image. I don't really care when it was taken, and in case the info is only stored in memory and after a reboot it keeps another image, I'd be fine with that as well.

**Comment by caco3** [comment] 2024-12-01 22:46
Duplicate of https://github.com/jomjol/AI-on-the-edge-device/issues/3326

**Closed** 2024-12-01 22:47 UTC
Labels: enhancement
