### ISSUE TITLE
Memory leak in latest FW (15.4.0)

### ISSUE THREAD

**Issue by Henkeh** [jomjol/AI-on-the-edge-device#2823] opened 2024-01-24 09:59 UTC
### The Problem

After upgrading to the latest FW (15.4.0) I noticed some readout issues after some time running it. This could possibly be related to https://github.com/jomjol/AI-on-the-edge-device/issues/2811.

When I did some digging on my own to investigate what was going on, I noticed that the amount of free memory was stadily decreasing. This can be seen in the attached image, which is a screenshot from my HA history regarding the "Free Memory" propery of the sensor that is exposed of MQTT. Here one can clearly see that the "Free Memory" shows a steady decline over time until it reaches a certain minimum and either crashes and reboots or the FW decides to reboot (unsure if that is implemented; did not dig into this yet).

The FW was installed during the Christmas holidays (the log suggest on the evening of 25th of December around 10:00 PM as that is when this undesired behavior starts). Before the upgrade the free memory was more or less stable over long periods of time.

### Version

15.4.0

### Logfile

https://www.dropbox.com/scl/fi/2dx9236oqlw3r1d8vjv1g/MemoryIssueLogs.7z?rlkey=z0anabue0rf0fahgvwgh1heno&dl=0

### Expected Behavior

"Free Memory" should stay stable over time. This now looks like a memory leak somewhere to me.

### Screenshots

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/1482861/85f0a25f-2dbb-44d7-8637-61814946e5be)

**Comment by Hootie81** [comment] 2024-01-26 04:03
Noticing the same thing with mine. I've also had 2 corrupt SD cards and I'm wondering if there is something in that too
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/7753214/3b622920-4ffe-4378-b31f-9376d9717e9a)
I replaced the corrupt SD card with a different one on the night of the 15th when i noticed there was no watermeter reading. 
i also loaded a new tflite file on the early morning of the 16th and notice a small jump in free mem after. but at midnight the meter went offline.
today is the first chance I've had to look at it.. the SD card is corrupt again

**Comment by nliaudat** [comment] 2024-01-26 16:11
I confirm memory leak on my 2 devices : 
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/6782613/95620d18-c16d-4831-b909-ebc72f1e5224)
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/6782613/82e8b675-21cf-485a-9258-75a72377214f)

**Comment by friedpa** [comment] 2024-01-26 17:44
I also confirm. I was wondering since a couple of weeks, why the two ESPs are freezing periodically. After your post I did also turn on the recording of he free memory value and I can see the same behaviour.

**Comment by nliaudat** [comment] 2024-01-26 22:57
We have to confirm that's the memory leak was introduced with  v15.4.0 (Commit: 74d4f20),

Can someone graph the memory with older release < 15.4.0 ?

It's crucial to  find the cause.

**Comment by nliaudat** [comment] 2024-01-26 23:06
Can someone test the https://github.com/VioletGiraffe/cppcheck-vs-addin plugin to find memory leak ?
I have no more a dev env - sry

**Comment by Henkeh** [comment] 2024-01-27 05:31
> We have to confirm that's the memory leak was introduced with v15.4.0 (Commit: [74d4f20](https://github.com/jomjol/AI-on-the-edge-device/commit/74d4f2085808317fc4594e1aa5892223a210c93f)),
> 
> Can someone graph the memory with older release < 15.4.0 ?
> 
> It's crucial to find the cause.
> 
> I created a discussions to find more people sharing their graph
> 
> #2829

The first part of the graph , before 26th of December, shows exactly this. I was on the previous FW version then (15.3.0), since I always keep it up-to-date.

Or are you looking for something else?

**Comment by nliaudat** [comment] 2024-01-27 09:26
> The first part of the graph , before 26th of December, shows exactly this. I was on the previous FW version then (15.3.0), since I always keep it up-to-date.
> 
> Or are you looking for something else?

This is exactly the proof that it was introduced in 15.4.0 release. 
Thanks.

Now need to review the code changes. 
Regards

**Comment by nliaudat** [comment] 2024-01-27 09:42
https://github.com/jomjol/AI-on-the-edge-device/compare/v15.3.0...v15.4.0

The mains changes are in submodules : 

code/components/esp-nn
code/components/esp32-camera

and in new MakeStaticResolver() function in code/components/jomjol_tfliteclass/CTfLiteClass.cpp

**Comment by spanzetta** [comment] 2024-01-28 17:38
Same problem here.. frequent reboot after few hours (due to memory leak)
I suspect (but not 100% sure) that the problem started when I enabled MQTT..

**Comment by friedpa** [comment] 2024-01-28 19:36
See picture below:
![grafik](https://github.com/jomjol/AI-on-the-edge-device/assets/42890695/e8f67961-9194-41eb-8b2a-0d526398904e)
Decreasing Free Memory of 15.4.0, stable Free Memory after OTA to 15.3.0

**Comment by caco3** [comment] 2024-01-28 22:22
I can confirm that there are issues with 15.4!
As a workaround, until we can find and solve it, simply revert to the 15.3 release.

**Comment by caco3** [comment] 2024-01-28 22:28
I once wrote a memory usage visualizer: https://github.com/caco3/psram-usage-visualizer

I will see if i can find something...

**Comment by caco3** [comment] 2024-01-28 23:57
Between 15.3 and 15.4 we updated 3 ESP modules.

I tried to revert them, but it does not build anymore.
This would need deeper investigation but I don't have the time atm, sry.

**Comment by caco3** [comment] 2024-01-29 17:46
Attempt to find leak: https://github.com/jomjol/AI-on-the-edge-device/pull/2837

**Comment by MihaiKrieger** [comment] 2024-01-31 19:07
I have not upgraded to 15.4. I am still on 15.3 and this is how my graph looks like.

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/52798790/91638f93-878e-412c-ae55-96f484d2ce49)

**Comment by JanHBade** [comment] 2024-02-01 13:09
My 15.4 is running for 6d without a restart... so i have not a memory leak ?!

![grafik](https://github.com/jomjol/AI-on-the-edge-device/assets/3524802/5eb0b318-8316-4216-ab88-bb3f4346c987)

**Comment by spanzetta** [comment] 2024-02-01 19:23
This is my memory situation with 15.4
I have 4 digital and 3 analog 

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/49818743/dde4d76a-c683-4368-a09a-e3c1f79c8318)

**Comment by matze338** [comment] 2024-02-02 04:18
Also with me. The internal memory decreases hour by hour until there is no more space. Then the ESP restarts.
![IMG_20240202_051717](https://github.com/jomjol/AI-on-the-edge-device/assets/54413820/069c0eb8-0b53-4b77-8473-2b8ac9fa3458)

**Comment by caco3** [comment] 2024-02-02 07:37
The memory leak will be fixed with https://github.com/jomjol/AI-on-the-edge-device/pull/2842

You can already use the image from https://github.com/jomjol/AI-on-the-edge-device/actions/runs/7731455511?pr=2842 or wait until it is in rolling or until we created the next release.

> My 15.4 is running for 6d without a restart... so i have not a memory leak ?!

It depends on your configuration. I also have one device with only digits where the leak did not occur.

**Comment by friedpa** [comment] 2024-02-02 10:28
The above picture is taken after loading the latest rolling:

![grafik](https://github.com/jomjol/AI-on-the-edge-device/assets/42890695/4e8bbb3f-ff48-4fb8-99dc-9567b3357018)

**Comment by caco3** [comment] 2024-02-02 10:42
because it is not in rolling yet! see my post!

**Comment by caco3** [comment] 2024-02-02 22:03
There is a new release 15.5.0 which fixes this.

**Closed by caco3** 2024-02-02 22:03 UTC
Labels: bug

**Comment by Henkeh** [comment] 2024-02-02 22:05
It seems to work indeed. Tnx for the quick fix!

**Comment by spanzetta** [comment] 2024-02-04 12:15
> This is my memory situation with 15.4 I have 4 digital and 3 analog
> 
> ![image](https://private-user-images.githubusercontent.com/49818743/301621293-dde4d76a-c683-4368-a09a-e3c1f79c8318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDkxNzcsIm5iZiI6MTcwNzA0ODg3NywicGF0aCI6Ii80OTgxODc0My8zMDE2MjEyOTMtZGRlNGQ3NmEtYzY4My00MzY4LWEwOWEtZTNjMWY3OWM4MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDEyMTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjU4NDgyZTExMmU5ZDEzNTQ5NDlkNWU2NDA3NWVmZDkzMjI1ODRjNmViNmRlMDAyZWY2N2Y0ZjM1NzFjOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bIT5LESFOw-tl7NgPFHYRVXESURdr-4qMoLdaivA88)

With 15.5 the situation is completelly changed..

Now it's completelly stable

**Comment by caco3** [comment] 2024-02-04 12:24
@spanzetta Please stop spreading the wrong thing about the power usage. Your issue is an insufficient power supply! Else I wonder why you are the only one with this issue!

**Comment by spanzetta** [comment] 2024-02-04 15:35
Removed comment about power supply

**Comment by spanzetta** [comment] 2024-02-04 16:31
> @spanzetta Please stop spreading the wrong thing about the power usage. Your issue is an insufficient power supply! Else I wonder why you are the only one with this issue!

Apparently it's not only me..
https://github.com/jomjol/AI-on-the-edge-device/discussions/2863

**Comment by caco3** [comment] 2024-02-04 18:10
> Apparently it's not only me..
https://github.com/jomjol/AI-on-the-edge-device/discussions/2863

Please point me to the comment there regarding **power issues!**

**Comment by friedpa** [comment] 2024-02-04 21:37
@spanzetta Hi Stefano, please don´t make your problems with this Open Source SW to ours. You are spreading wrong facts out because your skills unfortunately is not guiding you in the right direction. We are glad to support anyone with issues here, but please don´t go on our nerves. If you have something to report, collect all the facts and report, as it is common in a Bug Fix forum. If you don´t have facts please report to the comment forum, maybe someone can help you there.

**Comment by spanzetta** [comment] 2024-02-05 06:00
> @spanzetta Hi Stefano, please don´t make your problems with this Open Source SW to ours. You are spreading wrong facts out because your skills unfortunately is not guiding you in the right direction. We are glad to support anyone with issues here, but please don´t go on our nerves. If you have something to report, collect all the facts and report, as it is common in a Bug Fix forum. If you don´t have facts please report to the comment forum, maybe someone can help you there.

Ok I will stop reporting my experience.. 
I thought that sharing experience was/could be useful ..

**Comment by nliaudat** [comment] 2024-02-05 17:29
@spanzetta 
Feel free to open a [discussion](https://github.com/jomjol/AI-on-the-edge-device/discussions) and I'll try to help you. 
Regards
