### ISSUE TITLE
GPIO Settings - Enabling GPIO handler

### ISSUE THREAD

**Issue by wokkeltje13** [jomjol/AI-on-the-edge-device#761] opened 2022-04-07 08:34 UTC
I want to use external leds but the moment I enable "GPIO Settings - Enabling GPIO handler" no led is working, even if I select to use GPIO4 (built in led) this is not working. When I disable GPIO settings, the interna led is working correctly.

Am I  doing something wrong? or is this an issue?

**Comment by wokkeltje13** [comment] 2022-04-07 08:36
forgot to mention, I am using latest build: master - v10.5.2

**Comment by jomjol** [comment] 2022-04-07 17:22
The settings for 2 external WS2812 LEDs looks like the following:

![grafik](https://user-images.githubusercontent.com/30766535/162260965-dba2d896-77ba-4282-a098-7aba141be3a0.png)

It is working on 3 devices w/o any problems.

**Comment by wokkeltje13** [comment] 2022-04-07 17:45
This is how I tested
![image](https://user-images.githubusercontent.com/57153640/162264742-4d8d33f2-1989-4394-8c26-dbac1bd2ce1e.png)
, but the leds are not working, even just enabling GPIO4 does not work with only the build in led.

**Comment by jomjol** [comment] 2022-04-07 18:12
I assume you have connected the WS2812 to GPIO12. Then I assume a hardware failure. With this setting my systems are working without any problems.

**Comment by wokkeltje13** [comment] 2022-04-07 18:16
but should this config not just work with the build in led? Same as without the GPIO settings enabled.
![image](https://user-images.githubusercontent.com/57153640/162269871-a1c9b904-7fe4-400e-99a5-6d008ba56478.png)

**Comment by jomjol** [comment] 2022-04-07 18:19
It should work, but there is no reason to use this. The normal setting is okay for this. Therefore I have not testet it.

**Comment by wokkeltje13** [comment] 2022-04-07 18:44
as a troubleshooting step, I tried the GPIO4 way to be sure and this is also not working. So I was thinking something is wrong in my config.

**Comment by EmmanuelP** [comment] 2022-04-10 10:16
I had the same issue.

I guess it was because I have edited the configuration in expert mode, and saved it. When you edit the configuration the first time, PWM duty resolution entry is blank. May be a wrong value is written in config.ini.

I have manually entered 8 as PWM duty resolution, and that made the external LEDs work.

**Comment by wokkeltje13** [comment] 2022-04-10 16:24
> I had the same issue.
> 
> I guess it was because I have edited the configuration in expert mode, and saved it. When you edit the configuration the first time, PWM duty resolution entry is blank. May be a wrong value is written in config.ini.
> 
> I have manually entered 8 as PWM duty resolution, and that made the external LEDs work.

tnx, the PWM value did the trick.
For other users it would probably be nice if this value had a correct default value or if you could see this value in the normal config window (without the need for advance config)

**Comment by westfalenyeti** [comment] 2022-04-13 16:44
Oh my goodness, that made my day!
Thank you so much @EmmanuelP  for the hint to the PWM Value, and thanks @wokkeltje13  for asking the question!
Since about 4 weeks i was searching for a reason, why the external LEDs stopped working, even after exchange of the LEDs and the ESPCam, but using the same SD-card :)

**Comment by jomjol** [comment] 2022-04-15 12:29
Create, that you found the topic. The default value is "10". I just tested different savings and configurations, but could not reproduce this problem. Maybe a manual change for some unkonw reason. I close this issue.

**Closed by jomjol** 2022-04-15 12:29 UTC
