### ISSUE TITLE
stopped sending MQTT Messages

### ISSUE THREAD

**Issue by msmthng** [jomjol/AI-on-the-edge-device#709] opened 2022-02-28 07:32 UTC
2022-02-27T09:39:51: sent publish successful in MQTTPublish, msg_id=52269, watermetermain/main/timestamp, 2022-02-27T09:24:36
**2022-02-27T09:39:51: sent publish successful in MQTTPublish, msg_id=4964, watermetermain/main/json, {"value":"","raw":"00805.4994","error":"Neg. Rate - Read:  - Raw: 00805.4994 - Pre: 835.4873 ","rate":"","timestamp":"2022-02-27T09:24:36"}
2022-02-27T09:39:51: task_autodoFlow - round done
2022-02-27T09:39:51: CPU Temperature: 48.3**
2022-02-27T09:43:55: task_autodoFlow - next round - Round #245
2022-02-27T09:43:56: 	FlowControll.doFlow - ClassFlowMakeImage
2022-02-27T09:43:58: 	handler_wasserzaehler - Start
2022-02-27T09:43:58: 	handler_wasserzaehler - Start
2022-02-27T09:43:58: 	handler_wasserzaehler - Start
2022-02-27T09:43:58: 	handler_prevalue - Start
2022-02-27T09:43:59: 	handler_prevalue - Start
2022-02-27T09:43:59: 	handler_wasserzaehler - Start
2022-02-27T09:44:01: 	FlowControll.doFlow - ClassFlowAlignment
2022-02-27T09:44:13: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-02-27T09:44:14: =============================================================================================
2022-02-27T09:44:14: =================================== Main Started ============================================
2022-02-27T09:44:14: =============================================================================================
2022-02-27T09:44:18: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-02-27T09:44:19: task_autodoFlow - next round - Round #1
2022-02-27T09:44:19: 	FlowControll.doFlow - ClassFlowMakeImage
2022-02-27T09:44:20: 	handler_wasserzaehler - Start
2022-02-27T09:44:24: 	FlowControll.doFlow - ClassFlowAlignment
2022-02-27T09:44:47: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:44:55: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:45:04: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-02-27T09:45:04: PostProcessing - Raw: 00835.5093 Value: 835.5093 Error: no error
2022-02-27T09:45:04: 	FlowControll.doFlow - ClassFlowMQTT
2022-02-27T09:45:04: task_autodoFlow - round done
2022-02-27T09:45:04: CPU Temperature: 48.9
2022-02-27T09:48:59: 	handler_prevalue - Start
2022-02-27T09:48:59: 	handler_prevalue - Start
2022-02-27T09:48:59: 	handler_wasserzaehler - Start
2022-02-27T09:48:59: 	handler_wasserzaehler - Start
2022-02-27T09:48:59: 	handler_wasserzaehler - Start
2022-02-27T09:48:59: 	handler_wasserzaehler - Start
2022-02-27T09:48:59: 	handler_wasserzaehler - Start
2022-02-27T09:48:59: 	handler_wasserzaehler - Start
2022-02-27T09:48:59: 	handler_wasserzaehler - Start
2022-02-27T09:49:01: 	handler_wasserzaehler - Start
2022-02-27T09:49:01: 	handler_prevalue - Start
2022-02-27T09:49:02: 	handler_prevalue - Start
2022-02-27T09:49:02: 	handler_prevalue - Start
2022-02-27T09:49:02: 	handler_prevalue - Start
2022-02-27T09:49:02: 	handler_prevalue - Start
2022-02-27T09:49:02: 	handler_prevalue - Start
2022-02-27T09:49:10: task_autodoFlow - next round - Round #2
2022-02-27T09:49:10: 	FlowControll.doFlow - ClassFlowMakeImage
2022-02-27T09:49:15: 	FlowControll.doFlow - ClassFlowAlignment
2022-02-27T09:49:37: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:49:45: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:49:54: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-02-27T09:49:54: 	FlowControll.doFlow - ClassFlowMQTT
2022-02-27T09:49:54: task_autodoFlow - round done
2022-02-27T09:49:54: CPU Temperature: 48.9
2022-02-27T09:54:00: 	handler_prevalue - Start
2022-02-27T09:54:00: 	handler_prevalue - Start
2022-02-27T09:54:00: 	handler_wasserzaehler - Start
2022-02-27T09:54:01: task_autodoFlow - next round - Round #3
2022-02-27T09:54:01: 	FlowControll.doFlow - ClassFlowMakeImage
2022-02-27T09:54:01: 	handler_wasserzaehler - Start
2022-02-27T09:54:01: 	handler_wasserzaehler - Start
2022-02-27T09:54:01: 	handler_prevalue - Start
2022-02-27T09:54:01: 	handler_prevalue - Start
2022-02-27T09:54:02: 	handler_wasserzaehler - Start
2022-02-27T09:54:02: 	handler_wasserzaehler - Start
2022-02-27T09:54:02: 	handler_wasserzaehler - Start
2022-02-27T09:54:02: 	handler_wasserzaehler - Start
2022-02-27T09:54:03: 	handler_prevalue - Start
2022-02-27T09:54:03: 	handler_prevalue - Start
2022-02-27T09:54:03: 	handler_prevalue - Start
2022-02-27T09:54:03: 	handler_prevalue - Start
2022-02-27T09:54:06: 	FlowControll.doFlow - ClassFlowAlignment
2022-02-27T09:54:29: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:54:37: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:54:45: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-02-27T09:54:45: 	FlowControll.doFlow - ClassFlowMQTT
2022-02-27T09:54:45: task_autodoFlow - round done
2022-02-27T09:54:46: CPU Temperature: 48.3
2022-02-27T09:58:52: task_autodoFlow - next round - Round #4
2022-02-27T09:58:52: 	FlowControll.doFlow - ClassFlowMakeImage
2022-02-27T09:58:57: 	FlowControll.doFlow - ClassFlowAlignment
2022-02-27T09:59:01: 	handler_prevalue - Start
2022-02-27T09:59:01: 	handler_prevalue - Start
2022-02-27T09:59:01: 	handler_wasserzaehler - Start
2022-02-27T09:59:01: 	handler_wasserzaehler - Start
2022-02-27T09:59:01: 	handler_wasserzaehler - Start
2022-02-27T09:59:01: 	handler_wasserzaehler - Start
2022-02-27T09:59:01: 	handler_wasserzaehler - Start
2022-02-27T09:59:01: 	handler_wasserzaehler - Start
2022-02-27T09:59:01: 	handler_wasserzaehler - Start
2022-02-27T09:59:04: 	handler_wasserzaehler - Start
2022-02-27T09:59:04: 	handler_prevalue - Start
2022-02-27T09:59:04: 	handler_prevalue - Start
2022-02-27T09:59:04: 	handler_prevalue - Start
2022-02-27T09:59:04: 	handler_prevalue - Start
2022-02-27T09:59:04: 	handler_prevalue - Start
2022-02-27T09:59:04: 	handler_prevalue - Start
2022-02-27T09:59:20: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:59:28: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-02-27T09:59:37: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-02-27T09:59:37: PostProcessing - Raw: 00835.5098 Value: 835.5098 Error: no error
2022-02-27T09:59:37: 	FlowControll.doFlow - ClassFlowMQTT
2022-02-27T09:59:37: task_autodoFlow - round done
2022-02-27T09:59:37: CPU Temperature: 49.4
2022-02-27T10:03:43: task_autodoFlow - next round - Round #5
2022-02-27T10:03:43: 	FlowControll.doFlow - ClassFlowMakeImage
2022-02-27T10:03:48: 	FlowControll.doFlow - ClassFlowAlignment
2022-02-27T10:04:02: 	handler_prevalue - Start

**Comment by msmthng** [comment] 2022-02-28 07:33
![image](https://user-images.githubusercontent.com/40269445/155942387-fec400b0-8a8a-4c0e-901d-8e437f2428a8.png)

**Comment by jomjol** [comment] 2022-02-28 17:09
I cannot see any problems out of the log file. If you have changed noting, but only a reboot, than the problem is most likely not the ESP32!
Most propably there is a weak internet connection. If the MQTT Client cannot connect to the broker at the startup it stops sending until the next reboot.

**Comment by ckoeber83** [comment] 2022-03-03 14:27
Same for me.

It looks like after update to v10.5.2 the `mqtt.0.<name>.main.value` will not more updated after a successful read (raw value is higher than pre value)

`Neg. Rate - Read:  - Raw: 00456.5461 - Pre: 456.6091 `
![image](https://user-images.githubusercontent.com/52466072/156583399-09bdfd39-b131-4d59-b57e-3596e8b09e0d.png)

**Comment by jomjol** [comment] 2022-03-05 11:34
Not sending the value is due to the detection of an not okay value (new since version 10).
Why there is a discrepancy between the previous value shown above and and in the error message, I need to check.

**Comment by ckoeber83** [comment] 2022-03-09 09:18
Going back to v10.3.0 and still have the issue that the `mqtt.0.<name>.main.value` will not more updated in case of no errors in Consistency checks.
How can I get this back working?

**Comment by Nobbynews** [comment] 2022-03-09 14:57
Same thing here:

2022-03-09T10:23:48: task_autodoFlow - next round - Round #895
2022-03-09T10:23:48: 	FlowControll.doFlow - ClassFlowMakeImage
2022-03-09T10:23:56: 	FlowControll.doFlow - ClassFlowAlignment
2022-03-09T10:24:12: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T10:24:27: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T10:24:36: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-03-09T10:24:36: PostProcessing - Raw: 00679.2415 Value: 679.2415 Error: no error
2022-03-09T10:24:36: 	FlowControll.doFlow - ClassFlowMQTT
2022-03-09T10:24:36: sent publish successful in MQTTPublish, msg_id=27998, wasserzaehler/connection, connected
2022-03-09T10:24:36: sent publish successful in MQTTPublish, msg_id=13352, wasserzaehler/uptime, 214623
2022-03-09T10:24:36: sent publish successful in MQTTPublish, msg_id=1950, wasserzaehler/freeMem, 3075671
2022-03-09T10:24:36: sent publish successful in MQTTPublish, msg_id=63084, wasserzaehler/wifiRSSI, -42
**2022-03-09T10:24:36: sent publish successful in MQTTPublish, msg_id=20386, wasserzaehler/main/value, 679.2415**
2022-03-09T10:24:36: sent publish successful in MQTTPublish, msg_id=40809, wasserzaehler/main/error, no error
2022-03-09T10:24:37: sent publish successful in MQTTPublish, msg_id=59459, wasserzaehler/main/rate, 0.000824
2022-03-09T10:24:37: sent publish successful in MQTTPublish, msg_id=58621, wasserzaehler/main/raw, 00679.2415
2022-03-09T10:24:37: sent publish successful in MQTTPublish, msg_id=34517, wasserzaehler/main/timestamp, 2022-03-09T10:23:56
2022-03-09T10:24:37: sent publish successful in MQTTPublish, msg_id=45282, wasserzaehler/main/json, {"value":679.2415,"raw":"00679.2415","error":"no error","rate":0.000824,"timestamp":"2022-03-09T10:23:56"}
2022-03-09T10:24:37: task_autodoFlow - round done
[.....]
2022-03-09T10:27:48: task_autodoFlow - next round - Round #896
2022-03-09T10:27:48: 	FlowControll.doFlow - ClassFlowMakeImage
2022-03-09T10:27:56: 	FlowControll.doFlow - ClassFlowAlignment
2022-03-09T10:28:13: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T10:28:27: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T10:28:36: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-03-09T10:28:36: PostProcessing - Raw: 00679.3415 Value: 679.3415 Error: no error
2022-03-09T10:28:36: 	FlowControll.doFlow - ClassFlowMQTT
2022-03-09T10:28:36: sent publish successful in MQTTPublish, msg_id=21590, wasserzaehler/connection, connected
2022-03-09T10:28:36: sent publish successful in MQTTPublish, msg_id=25393, wasserzaehler/uptime, 214863
2022-03-09T10:28:36: sent publish successful in MQTTPublish, msg_id=31966, wasserzaehler/freeMem, 3075863
2022-03-09T10:28:37: sent publish successful in MQTTPublish, msg_id=48239, wasserzaehler/wifiRSSI, -45
2022-03-09T10:28:37: sent publish successful in MQTTPublish, msg_id=42481, wasserzaehler/main/value, 679.3415
2022-03-09T10:28:37: sent publish successful in MQTTPublish, msg_id=46720, wasserzaehler/main/error, no error
2022-03-09T10:28:37: sent publish successful in MQTTPublish, msg_id=3684, wasserzaehler/main/rate, 0.024994
2022-03-09T10:28:37: sent publish successful in MQTTPublish, msg_id=54457, wasserzaehler/main/raw, 00679.3415
2022-03-09T10:28:37: sent publish successful in MQTTPublish, msg_id=38735, wasserzaehler/main/timestamp, 2022-03-09T10:27:56
2022-03-09T10:28:37: sent publish successful in MQTTPublish, msg_id=43678, wasserzaehler/main/json, {"value":679.3415,"raw":"00679.3415","error":"no error","rate":0.024994,"timestamp":"2022-03-09T10:27:56"}
2022-03-09T10:28:37: task_autodoFlow - round done

The value 679.3415 is wrong. After manual set PreValue:

2022-03-09T13:47:49: task_autodoFlow - next round - Round #946
2022-03-09T13:47:49: 	FlowControll.doFlow - ClassFlowMakeImage
2022-03-09T13:47:57: 	FlowControll.doFlow - ClassFlowAlignment
2022-03-09T13:48:14: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T13:48:28: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T13:48:38: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-03-09T13:48:38: PostProcessing - Raw: 00679.2415 Value: 679.2415 Error: no error
2022-03-09T13:48:38: 	FlowControll.doFlow - ClassFlowMQTT
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=27585, wasserzaehler/connection, connected
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=457, wasserzaehler/uptime, 226865
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=17108, wasserzaehler/freeMem, 3075863
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=55297, wasserzaehler/wifiRSSI, -47
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=59645, wasserzaehler/main/value, 679.2415
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=37605, wasserzaehler/main/error, no error
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=47897, wasserzaehler/main/rate, 0.000000
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=8476, wasserzaehler/main/raw, 00679.2415
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=9948, wasserzaehler/main/timestamp, 2022-03-09T13:47:57
2022-03-09T13:48:38: sent publish successful in MQTTPublish, msg_id=49149, wasserzaehler/main/json, {"value":679.2415,"raw":"00679.2415","error":"no error","rate":0.000000,"timestamp":"2022-03-09T13:47:57"}
2022-03-09T13:48:38: task_autodoFlow - round done
2022-03-09T13:48:38: CPU Temperature: 33.3
2022-03-09T13:49:33: info_get_handler
2022-03-09T13:49:36: 	handler_wasserzaehler - Start
2022-03-09T13:49:36: 	handler_wasserzaehler - Start
2022-03-09T13:49:36: 	handler_wasserzaehler - Start
2022-03-09T13:49:36: 	handler_wasserzaehler - Start
2022-03-09T13:49:36: 	handler_prevalue - Start
2022-03-09T13:49:36: 	handler_prevalue - Start
2022-03-09T13:49:37: 	handler_prevalue - Start
2022-03-09T13:49:38: 	handler_prevalue - Start
2022-03-09T13:51:49: task_autodoFlow - next round - Round #947
2022-03-09T13:51:49: 	FlowControll.doFlow - ClassFlowMakeImage
2022-03-09T13:51:57: 	FlowControll.doFlow - ClassFlowAlignment
2022-03-09T13:52:13: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T13:52:17: 	handler_prevalue - Start
2022-03-09T13:52:17: 	handler_prevalue - Start
2022-03-09T13:52:29: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T13:52:38: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-03-09T13:52:38: PostProcessing - Raw: 00679.2415 Value: 679.2415 Error: no error
2022-03-09T13:52:38: 	FlowControll.doFlow - ClassFlowMQTT
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=62308, wasserzaehler/connection, connected
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=48360, wasserzaehler/uptime, 227105
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=37862, wasserzaehler/freeMem, 3075847
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=27347, wasserzaehler/wifiRSSI, -40
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=5683, wasserzaehler/main/value, 679.2415
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=13441, wasserzaehler/main/error, no error
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=121, wasserzaehler/main/rate, 0.000000
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=15718, wasserzaehler/main/raw, 00679.2415
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=18907, wasserzaehler/main/timestamp, 2022-03-09T13:51:57
2022-03-09T13:52:38: sent publish successful in MQTTPublish, msg_id=60383, wasserzaehler/main/json, {"value":679.2415,"raw":"00679.2415","error":"no error","rate":0.000000,"timestamp":"2022-03-09T13:51:57"}
2022-03-09T13:52:38: task_autodoFlow - round done
2022-03-09T13:52:38: CPU Temperature: 33.9
2022-03-09T13:55:49: task_autodoFlow - next round - Round #948
2022-03-09T13:55:49: 	FlowControll.doFlow - ClassFlowMakeImage
2022-03-09T13:55:57: 	FlowControll.doFlow - ClassFlowAlignment
2022-03-09T13:56:14: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T13:56:28: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T13:56:38: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-03-09T13:56:38: 	FlowControll.doFlow - ClassFlowMQTT
2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=56475, wasserzaehler/connection, connected
2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=45533, wasserzaehler/uptime, 227345
2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=18245, wasserzaehler/freeMem, 3077491
2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=22511, wasserzaehler/wifiRSSI, -43
**2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=52492, wasserzaehler/main/error, Rate too high - Read: 679.3431 - Pre: 679.2415**
2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=58017, wasserzaehler/main/raw, 00679.3431
2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=46020, wasserzaehler/main/timestamp, 2022-03-09T13:51:57
2022-03-09T13:56:38: sent publish successful in MQTTPublish, msg_id=35743, wasserzaehler/main/json, {"value":"","raw":"00679.3431","error":"Rate too high - Read: 679.3431 - Pre: 679.2415","rate":"","timestamp":"2022-03-09T13:51:57"}
2022-03-09T13:56:38: task_autodoFlow - round done
[......]
2022-03-09T15:43:49: task_autodoFlow - next round - Round #975
2022-03-09T15:43:49: 	FlowControll.doFlow - ClassFlowMakeImage
2022-03-09T15:43:57: 	FlowControll.doFlow - ClassFlowAlignment
2022-03-09T15:44:14: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T15:44:29: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-03-09T15:44:38: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-03-09T15:44:38: 	FlowControll.doFlow - ClassFlowMQTT
2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=47993, wasserzaehler/connection, connected
2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=2199, wasserzaehler/uptime, 233825
2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=26560, wasserzaehler/freeMem, 3077491
2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=18112, wasserzaehler/wifiRSSI, -44
**2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=22047, wasserzaehler/main/error, Rate too high - Read: 679.3489 - Pre: 679.2415**
2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=59107, wasserzaehler/main/raw, 00679.3489
2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=27774, wasserzaehler/main/timestamp, 2022-03-09T13:51:57
**2022-03-09T15:44:38: sent publish successful in MQTTPublish, msg_id=23542, wasserzaehler/main/json, {"value":"","raw":"00679.3489","error":"Rate too high - Read: 679.3489 - Pre:** 679.2415","rate":"","timestamp":"2022-03-09T13:51:57"}
2022-03-09T15:44:38: task_autodoFlow - round done

The sending will stop.

**Comment by ckoeber83** [comment] 2022-03-10 12:19
How I get this log?

My log is just showing this and I turn on the extended logging in config:

```
2022-03-07T13:10:50: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-03-07T13:10:50: =============================================================================================
2022-03-07T13:10:50: =================================== Main Started ============================================
2022-03-07T13:10:50: =============================================================================================
2022-03-07T16:39:24: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-03-07T16:39:24: =============================================================================================
2022-03-07T16:39:24: =================================== Main Started ============================================
2022-03-07T16:39:24: =============================================================================================
```

**Comment by Nobbynews** [comment] 2022-03-10 15:19
Sure that you enabled extended logging??
![Screenshot_20220310-142059~3](https://user-images.githubusercontent.com/70503167/157693154-f95f57ff-11e5-4ca6-b381-5ef451e51b9b.png)
?

**Comment by friedpa** [comment] 2022-03-10 15:55
My guess is, that the ESP is constantly rebooting. You have to look at the serial interface to see exactly where the ESP stops.

**Comment by ckoeber83** [comment] 2022-03-10 16:19
no esp runs since 3.03 days

**Comment by friedpa** [comment] 2022-03-10 16:28
Doing what?

**Comment by jomjol** [comment] 2022-03-20 20:37
Currently no acitivies --> closing

**Closed by jomjol** 2022-03-20 20:37 UTC
