### ISSUE TITLE
RAW value is not updated, but Recognition value is right

### ISSUE THREAD

**Issue by sbeuchat** [jomjol/AI-on-the-edge-device#1143] opened 2022-10-07 08:23 UTC
### The Problem

Hello

I've checked into the existing issue, but I didn't find any similar issue / bug correction.

The recognition value is right (7472.759)
![image](https://user-images.githubusercontent.com/73058553/194508884-dffb374c-4a0d-4ed5-a4f0-e8d918dbc12b.png)

But the RAW value isn't updated
![image](https://user-images.githubusercontent.com/73058553/194508997-301d1066-f3c6-4902-a467-5667aff7b2b6.png)

I have played with CheckDigitalIncreaseConsistency, but it doens't help.

Did I missed something?

Thanks in advance for your support

### Version

11.3.0

**Comment by jomjol** [comment] 2022-10-07 18:23
Can you update to the newest version? 11.3.0 might have some bugs there.

**Comment by Hoovercraft** [comment] 2022-10-11 09:55
I have the same problem. It first appeared when my counter went from 576 to 577. The RAW Value remains static although the actual value is recognized.
My version is 12.0.1

**Comment by haverland** [comment] 2022-10-14 21:15
@Hoovercraft: I'm not sure, what kind of correct value it should be. 
dig3 = 6.8 and ana1=8.6 is on the most meters the digit = 6, because the digit is at ana3=0 on 7.0.
So the 576 should be correct. 
But it could be the meter digit switches very late (analog >9.x)

**Comment by haverland** [comment] 2022-10-14 21:18
> ### The Problem
> Hello
> 
> I've checked into the existing issue, but I didn't find any similar issue / bug correction.
> 
> The recognition value is right (7472.759) 
@sbeuchat: you problem should be fixed in 12.0.1. But I've tested on rolling.

**Comment by PetrMa** [comment] 2022-10-15 17:23
Hello,
I have similar issue after upgrading to 12.0.1.
My digital counter show correct number increased by + 1 but the RAW value show correct value.
Recognition show also correct value.
HA shows 345 instead of 344.
WHY? Whats  wrong?
![Snímek obrazovky 2022-10-15 191059](https://user-images.githubusercontent.com/24729480/195999577-56e25c78-9943-4f34-a24c-9b34f8c4af78.png)
![Snímek obrazovky 2022-10-15 191141](https://user-images.githubusercontent.com/24729480/195999581-53986556-9027-43cc-9fa6-36b60d300a34.png)

**Comment by jest01** [comment] 2022-10-17 17:44
Hello,

i have the same problem, the raw value dosn't updated

the ESP32 could not be reached and could only be reactivated by power on/off.
I am currently using version 12.0.1
 
![overview](https://user-images.githubusercontent.com/46645663/196246251-45a78127-f938-4977-a022-25895717227b.jpg)
![recognition](https://user-images.githubusercontent.com/46645663/196246255-e28652cc-5aeb-4b74-ba0b-c4f4c9df5f52.jpg)

**Comment by haverland** [comment] 2022-10-17 20:46
> Hello,
> 
> i have the same problem, the raw value dosn't updated
> 
Thanks. Any example is welcome. I've added it as test case. 
We working on it and currently all posted examples are test cases for the next change.

**Comment by Hoovercraft** [comment] 2022-10-20 15:21
another day, another wonder ... no idea what happened, didnt change anything, but its working again

**Comment by jest01** [comment] 2022-10-20 15:44
Hello,

after a second ESP32 didn't work either, I looked in the serial log and found that the brownout detection had responded...for whatever reason
I bet on the internal voltage regulator in the ESP and have solved the voltage supply with a 5V power supply and a LD33V3 with 3.3V. Since then everything has been going well again.
Could that possibly be a cause?

Best regards

**Comment by Hoovercraft** [comment] 2022-10-24 13:08
New day, new miracle. The problem is there again. Maybe a solution: if you go via the settings/set previous value menu, the value from the previous value is displayed for current value. Looks like a wrong mapping. Workaround: switch off the previous value in the config.

**Comment by caco3** [comment] 2022-11-29 10:22
Please re-open if issue still happens again

**Closed** 2022-11-29 10:22 UTC
