### ISSUE TITLE
Info Page no data

### ISSUE THREAD

**Issue by Crajs20** [jomjol/AI-on-the-edge-device#1425] opened 2022-11-28 21:51 UTC
### The Problem

With the new update, I dont see any information on the version page. I get the new values, but all details re empty.

### Version

13.0.1

### Logfile

```shell
Failed to read existing file
```

**Comment by caco3** [comment] 2022-11-29 07:25
That really looks like your SD-Card is bad or the file system on it.
Can you take the [Web Console](https://jomjol.github.io/AI-on-the-edge-device/index.html) and check the USB log?

**Comment by Duese123** [comment] 2022-11-29 15:09
Flash several times the Update.zip (before Flash Firmware.bin) but i habe the problem that 13.0.1 is extremely slow.

I had to Flash the Update several times and it was also slowly...

**Comment by caco3** [comment] 2022-11-29 15:44
slowly after the update or while the update?

please provide logs!

**Comment by Duese123** [comment] 2022-11-29 16:03
Slowly during the update. For example for upload not Max 60s... almost 400... and i had to Do this very often. After some times message appeared flashing successfull and restarting. Then Web Page was horrible slowly. I changed Pic quality to 50.. and check again after the night and the Response is faster. Changed back to 20 and for now it is running but sometimes slowly or with no repsonse.

I was updating from.version before trying with the zip it was not working several times. 
Then i took firmware file it worked. There were 2 errors for config no neural files found okay.. no files in dropdown menü... Info was also completly empty... so i flashed several times afterwards the whole zip again... sometimes nothing happened i tried to make it.with ota direct link no.response. After some Minutes webpage was working again and retried... After an hour i had a succeed message and all the Infos at Info.page were filled.. also dropdown is working... at the beginning Rotation from pic was not working and webpage was terrible slow. Sometimes not answering or went completely offline...

After the night it seems to be working now. Sometimes. Sometimes not.

**Comment by Duese123** [comment] 2022-11-29 16:05
[log_2022-11-28.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10114814/log_2022-11-28.txt)
[log_2022-11-29.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10114815/log_2022-11-29.txt)
Just downloaded the 2 files and no Response again...

**Comment by caco3** [comment] 2022-11-30 12:31
I guess it also could be an issue with the SD card!
It fails to read files from there.

Others had similar issues and solved it by formating the SD-Card with a different tool.

**Comment by Duese123** [comment] 2022-11-30 12:36
Thats strange it was working before since 6 months flawlessly.

**Comment by caco3** [comment] 2022-11-30 12:39
It does not make any sense that it is slow and suddenly is fast again!
Do you have a weak wifi connection?

**Comment by Duese123** [comment] 2022-11-30 12:49
It is working right now but took some hours. Maybe some overload cpu issues. Do not know. It is working but mqtt errors appearing some times.
Also i saw

2022-11-30T13:09:51 <INF> [MAIN] Reset reason: Exception/panic
2022-11-30T13:09:51 <WRN> [MAIN] Web UI version does not match firmware version!
2022-11-30T13:09:54 <INF> [MAIN] Initialization completed successfully!
2022-11-30T13:09:54 <WRN> [TFLITE] Restarted due to an Exception/panic! Postponing first round start by 5 minutes to allow for an OTA or to fetch the log!
2022-11-30T13:09:54 <WRN> [TFLITE] Setting logfile level to DEBUG until the next reboot!
2022-11-30T13:10:02 <DBG> [HEAP] handler_prevalue - Start Heap: 4123830

**Comment by caco3** [comment] 2022-11-30 12:57
It is not like a PC which does cleanup tasks in the background. After the ESP32 is fully started and initialized, the CPU usage is the same for each round.

> Web UI version does not match firmware version!

That will be fixed in the next release

> Reset reason: Exception/panic

To understand this better, I would need to know the log lines before the restart.

> It is working but mqtt errors appearing some times.

Yes, the MQTT client is not stable, but we do not understand why since it is directly provided by the ESP library.

**Comment by Crajs20** [comment] 2022-11-30 13:29
I think I found my issue.
It's not the as card. After the firmware update, the device didn't reboot. I had the new html file online but firmware.bin was not loaded.
It's writing reboot by the update but didn't it, rebooted manually over the Menü and it's now working.

**Comment by caco3** [comment] 2022-11-30 21:56
> After the firmware update, the device didn't reboot.

I never had an issue with a failing reboot.
Maybe you cancelled the reboot when the dialog box asked for it.

**Comment by Ingo-Knito** [comment] 2022-11-30 22:23
I also had this problem.
Out of four devices, one hang and did not restart on its own. So I waited a long time and did it from my side.

**Comment by caco3** [comment] 2022-12-01 06:54
the updater in 12.0.1 was still buggy, we hope that the new one is better.

The old one sometimes hang for unknown reasons

**Comment by parhedberg** [comment] 2022-12-05 10:29
I have similar problem with latest release (13.0.4).

The start page (ie watermeter.home.arpa/) presents with "Failed to read existing file".
![image](https://user-images.githubusercontent.com/13777521/205614224-1cb89370-2137-4903-90dd-817a97ad013d.png)

According to network log it is because a 500 response error to this URL:
`http://watermeter.home.arpa/_delighted_web={"FutSOUgy5edCcTk9":{"_delighted_fst":{"t":"1642595831509"},"_delighted_lst":{"t":"1642598498676","m":{"token":"K5F4yCXYvIrtpIjGgyjaju4P"}},"_delighted_lrt":{"t":"1642598518389","m":{"token":"K5F4yCXYvIrtpIjGgyjaju4P"}}}}; _ga=GA1.2.727264625.1643036437; info.html`

Although if i click on the "Overview" menu button, i get all the info that were on the startpage in my most recent version (v12.0.1)

I have rebooted several times after the uppgrade.

**Comment by caco3** [comment] 2022-12-05 11:30
`_delighted_web=` is not an URL the webserver on the device knows!

We had that also here: https://github.com/jomjol/AI-on-the-edge-device/issues/1424

The only issue I see here is that the webserver by default returns error 500 instead of 404. => I will look into that

**Comment by caco3** [comment] 2022-12-05 12:14
@parhedberg can you provide a network screenshot with the developer tools?

I would like to see what it tries to call when it shows "not found" in the lower iframe.

**Comment by parhedberg** [comment] 2022-12-05 12:17
No, sorry.. I have now deleted that cookie that presented itself in the URL and now the problem is gone, so I can't reproduce.. 

My guess is that this has something to do with this commit:

https://github.com/jomjol/AI-on-the-edge-device/commit/524d800a0aa637f8b6440c6ba8614dd425994376#diff-71d24da02d173de1f3bfcd7509920a1350de260e33e884b79ea81804e8a147b3R213

**Comment by parhedberg** [comment] 2022-12-05 12:22
Or maybe somewhere where that cookie is fetched to be used.. What i could see, the cookie that showed up in my faulty URL, was the "first" cookie in my browsers list of cookies.. Now, i only have one cookie, that has got no name:

![image](https://user-images.githubusercontent.com/13777521/205636300-03818216-889b-4f44-9c94-017f20f97735.png)

**Comment by parhedberg** [comment] 2022-12-05 12:40
Have searched the code now, and i think that this is the problem: 
1. When you update the firmware, you set a cookie to now where to return after reboot
2. When you load index.html you try to fetch "document.cookie" and navigate to that. 

My guess is that you should set a name on the cookie and then retrieve just that cookie for navigation in index.html?


Here is where you set the value:
https://github.com/jomjol/AI-on-the-edge-device/commit/524d800a0aa637f8b6440c6ba8614dd425994376#diff-71d24da02d173de1f3bfcd7509920a1350de260e33e884b79ea81804e8a147b3R213

Here is where you fetch the cookie value:
https://github.com/jomjol/AI-on-the-edge-device/commit/6e4df0ef878aae54ce4d5f19d00725b265c89b80#diff-d3c84aa9541ce06ae1e52760bf0a1e4c06e5dd4258124c36330824e9eb293539R95

**Comment by caco3** [comment] 2022-12-05 21:05
@parhedberg I not only set the cookie on OTA, but whenever you select another page. I use it so on a page reload it goes back to that selected page.

With our pull request it hopefully is ok again, thanks!

**Closed by caco3** 2022-12-05 21:05 UTC
Labels: bug, waiting for more input
