### ISSUE TITLE
ws2813 led strip gpio settings + stability issues

### ISSUE THREAD

**Issue by kdw2060** [jomjol/AI-on-the-edge-device#406] opened 2021-11-18 20:11 UTC
Hi, first and foremost thank you for this useful project.
I bought a ws2813 led strip and am trying to get it to work. Right now the leds constantly burn and the first one changes color every now and then. I tried fiddling around with the advanced settings, but don't get it to work for now.
What would be the required settings here?
![jomjol-AI-on-the-edge](https://user-images.githubusercontent.com/15030611/142487348-2ebee612-247f-42cc-85a5-5bf9f9e01256.png)

Also, since experimenting with the led strip the board is very unstable and the web interface not always accessible. When I disable GPIO in config again then the board performs stable again. 
I did not add those extra electronic bits that are visible in your scheme for the ws2812 led strip however. I read the 2813 has built in resistors for every led, so hoped i could skip adding that resistor and capacitor as I am a total noob when it comes to soldering.

**Comment by jomjol** [comment] 2021-11-18 20:39
Hi, I have not tested the library for the WS2813. With my WS2812B it is running relative stable.
You don't need the extended setting. My WS2812 is running with the follwing settings:
![grafik](https://user-images.githubusercontent.com/30766535/142493116-303e4e1d-b551-49ae-b141-6125dbb0f2a6.png)

It could be, that there are bugs in the WS2813 part?!

**Comment by jomjol** [comment] 2021-11-20 18:47
closing until further notice (please reopen in case new information available)

**Closed by jomjol** 2021-11-20 18:47 UTC

**Comment by kdw2060** [comment] 2021-11-21 11:44
Hi, I do have further info now.
I restored those extra settings to the initial state and cut down the led strip to 2 leds. This fixed the stability issue.
As for the constantly burning led, the behaviour is now as such:
- first led on strip is correctly controlled by your software and only lights up when a picture is taken.
- second led is constantly burning. lights op white together with first led when picture is taken, then turns green or red and stays on all the time.

I don't know if that behaviour sketch is enough for you to figure out what might be going on.

**Comment by jomjol** [comment] 2021-11-21 21:33
Are you still working with the WS281**3**?

I cannot reproduce the error currently with an WS281**2B**. I have connected up to 6 LEDs and the first two are working as expected.

**Comment by kdw2060** [comment] 2021-11-22 09:38
Yes, still the 2813, don't have any other version in my posession.

**Comment by jomjol** [comment] 2021-11-22 17:34
I don't have the 2813. If the problem is related to the drive, then I cannot debut it here.
