### ISSUE TITLE
Constant misreading

### ISSUE THREAD

**Issue by Kev0123** [jomjol/AI-on-the-edge-device#292] opened 2021-07-26 07:51 UTC
First of all: Congrats for this great project!

I got constant misreadings.
Precondition: Watermeter is at 113.058 
Recognized: 113.078
--> new value set 113.078
Next reading(same meter values): 113.NaN58
--> new value set 113.158

afterwards all values are wrong because of this wrong interpretation of the NaN shift.

Here is my meter:
![alg_roi](https://user-images.githubusercontent.com/19821853/126952435-00e9a229-0d2c-41ab-8b0e-596a624d53e2.jpg)

The other problem is the analog readout. Sometimes its totaly off (e.g. here 1.6)

![1 6_ana1_20210726-093847](https://user-images.githubusercontent.com/19821853/126952515-c2b91a23-8937-48de-b022-6672e80c114c.jpg)

Is it possible/necessary to teach the model with new pictures?

Regards

**Comment by jomjol** [comment] 2021-07-26 16:30
Hi,
first of all thanks for your feedback. I can incorporate new pictures into the next training. Therefore I need 1-2 images per digit number (0, 1, ... 9). Not more!
For the analog meter I need pictures, that are labeled "2.7_ARBITRATRY.jpg", so at first the exptected reading with one digit. Here about one picture per reading is okay, but less images will also work.

You could turn on the `CheckDigitIncreaseConsistency` to true. As you have an analog meter, this should work here and improve the replacement of the "N".

**Comment by Kev0123** [comment] 2021-07-26 16:35
Actually the `CheckDigitIncreaseConsistency` was true. After turning it off the digital readout seems to be a bit more reliable. (don't know it this is even affected by this)
I'll gather the picture for you.

**Comment by Kev0123** [comment] 2021-07-27 08:16
Here are the digit ones. For the analog I need more time to search them up
[Digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6883869/Digits.zip)

**Comment by Kev0123** [comment] 2021-07-28 04:08
Somehow the algorithm seems to mess the rading up.
It pushes the falues continiously higher, regardless of the actual reading:
`021-07-28T04:31:04: task_autodoFlow - next round - Round #238
2021-07-28T04:31:04: 	FlowControll.doFlow - ClassFlowMakeImage
2021-07-28T04:31:12: 	FlowControll.doFlow - ClassFlowAlignment
2021-07-28T04:31:29: 	FlowControll.doFlow - ClassFlowDigit
2021-07-28T04:31:35: 	FlowControll.doFlow - ClassFlowAnalog
2021-07-28T04:31:37: 	FlowControll.doFlow - ClassFlowPostProcessing
2021-07-28T04:31:37: 	FlowControll.doFlow - ClassFlowMQTT
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=21790, Wasseruhr/connection, connected
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=48146, Wasseruhr/uptime, 42700
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=24816, Wasseruhr/freeMem, 3009144
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=32203, Wasseruhr/main/value, 113.5943
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=57809, Wasseruhr/main/error, no error
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=58300, Wasseruhr/main/rate, 0.000008
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=12161, Wasseruhr/main/timestamp, 2021-07-28T04:31:12
2021-07-28T04:31:37: sent publish successful in MQTTPublish, msg_id=22649, Wasseruhr/main/json, {"value":113.5943,"error":"no error","rate":0.000008,"timestamp":"2021-07-28T04:31:12"}
2021-07-28T04:31:37: task_autodoFlow - round done
2021-07-28T04:31:37: CPU Temperature: 75.0
2021-07-28T04:34:04: task_autodoFlow - next round - Round #239
2021-07-28T04:34:04: 	FlowControll.doFlow - ClassFlowMakeImage
2021-07-28T04:34:12: 	FlowControll.doFlow - ClassFlowAlignment
2021-07-28T04:34:30: 	FlowControll.doFlow - ClassFlowDigit
2021-07-28T04:34:36: 	FlowControll.doFlow - ClassFlowAnalog
2021-07-28T04:34:37: 	FlowControll.doFlow - ClassFlowPostProcessing
2021-07-28T04:34:37: 	FlowControll.doFlow - ClassFlowMQTT
2021-07-28T04:34:37: sent publish successful in MQTTPublish, msg_id=53766, Wasseruhr/connection, connected
2021-07-28T04:34:37: sent publish successful in MQTTPublish, msg_id=21547, Wasseruhr/uptime, 42880
2021-07-28T04:34:37: sent publish successful in MQTTPublish, msg_id=51348, Wasseruhr/freeMem, 3009148
2021-07-28T04:34:38: sent publish successful in MQTTPublish, msg_id=14707, Wasseruhr/main/value, 113.6811
2021-07-28T04:34:38: sent publish successful in MQTTPublish, msg_id=43204, Wasseruhr/main/error, no error
2021-07-28T04:34:38: sent publish successful in MQTTPublish, msg_id=44776, Wasseruhr/main/rate, 0.028941
2021-07-28T04:34:38: sent publish successful in MQTTPublish, msg_id=43353, Wasseruhr/main/timestamp, 2021-07-28T04:34:12
2021-07-28T04:34:38: sent publish successful in MQTTPublish, msg_id=60692, Wasseruhr/main/json, {"value":113.6811,"error":"no error","rate":0.028941,"timestamp":"2021-07-28T04:34:12"}
2021-07-28T04:34:38: task_autodoFlow - round done`

The corresponding Pictures are:
04:31
![10_1_20210728-043104](https://user-images.githubusercontent.com/19821853/127261204-d50236b6-848f-4dfd-91f6-cce7d007a5b4.jpg)
![0_2_20210728-043104](https://user-images.githubusercontent.com/19821853/127261227-5a9c016e-4a87-4cd3-8969-e8bcbedd67f7.jpg)
![1_3_20210728-043104](https://user-images.githubusercontent.com/19821853/127261237-87ad62cd-f1a4-4399-805e-089d65a133b8.jpg)
![1_4_20210728-043104](https://user-images.githubusercontent.com/19821853/127261240-66eb6837-1595-4103-8a48-f67c8947f3d0.jpg)
![3_5_20210728-043104](https://user-images.githubusercontent.com/19821853/127261247-3628bba7-1a90-4def-b57d-61cd9ef77702.jpg)
![5_6_20210728-043104](https://user-images.githubusercontent.com/19821853/127261252-7a608522-231f-4df2-a7a5-6afc170b894d.jpg)
![10_7_20210728-043104](https://user-images.githubusercontent.com/19821853/127261259-7aaf9f8f-7337-4b21-85f1-2409dd50c25d.jpg)
![10_8_20210728-043104](https://user-images.githubusercontent.com/19821853/127261267-666e0e1d-4b53-4f40-961a-34825d0812e0.jpg)

04:34
![10_1_20210728-043404](https://user-images.githubusercontent.com/19821853/127261426-8fb08b94-0746-48de-bbf4-f6a06cbe5a18.jpg)
![0_2_20210728-043404](https://user-images.githubusercontent.com/19821853/127261438-6879fda6-006c-4753-a96f-2515dfeb6bd9.jpg)
![1_3_20210728-043404](https://user-images.githubusercontent.com/19821853/127261445-d4c5a9e1-40aa-4fb3-a0bd-6a84423f61e6.jpg)
![1_4_20210728-043404](https://user-images.githubusercontent.com/19821853/127261448-ffc3b855-e576-492a-9c63-594cbc2bbe93.jpg)
![3_5_20210728-043404](https://user-images.githubusercontent.com/19821853/127261455-ec0dc004-ee48-4996-9ca9-6f4be70aca9b.jpg)
![5_6_20210728-043404](https://user-images.githubusercontent.com/19821853/127261460-9f37683c-71bb-4620-a0c7-2a3ec18fb1ee.jpg)
![8_7_20210728-043404](https://user-images.githubusercontent.com/19821853/127261470-8dc58005-e1db-43d7-9de8-582917bb8abc.jpg)
![1_8_20210728-043404](https://user-images.githubusercontent.com/19821853/127261480-9cd36261-52d6-4b60-acf0-c6a2d4b6b6e7.jpg)


I don't get why the shift is made from 113.5943 to 113.6811

In both cases the 6th digit is correct recognized and the shift in the 7th shouldn't trigger a change in 6th as the last recognized value was a 7 on 7th. The 7th is after 01:07 o'clock only NaN.

**Comment by jomjol** [comment] 2021-07-28 04:57
I assume, you have the `CheckDigitIncreaseConsistency` turned on (true). This consistency check only works, if between two readings the change in the value is not more than 1 digit. In this case it start to correct the "wrong" values. This algo is supposed to check the digits on a mixed meter (e.g. my water meter with digit digits and analog pointers).
If the digits are changed more than 1, than the algorithm might do some weired things. I suggest to turn this off. I will put your digits in the next version of the cnn.

**Comment by friedpa** [comment] 2021-07-28 05:01
Can you explain the problem again: the value at 04:31 is 00113.579. The recognized value is 111.5943 (by the way, where is the last digit 3 coming from?) The 7 and the 9 will not be recognized and should give a N. At 04:34 "only" the 5 is not detected which is clear to me as the 5 is too close to the left border (and makes therefore the reading random) of the frame which closes the 5 on the left side and makes it to a 6. My recommandation would be to set the left border on digit 6 (counted from the left side) a little bit more away from the left border. Please post also your alignment setting (the pictures with the red frames around the digits)

**Comment by Kev0123** [comment] 2021-07-28 06:29
The last digit is from analog. As this doesnt give me such a big issue I currently ignored it. Here is the alignment:
![alg_roi](https://user-images.githubusercontent.com/19821853/127273855-7ee03943-3b87-47f9-9111-55538e4c9b45.jpg)

@friedpa did you mean to shift the 6th to the right?

@jomjol  Shoudn't the algorithm check only the last "valid" value, e.g. @01:07 the 7th was a known 7, afterwards N. As I understand, with the `CheckDigitIncreaseConsistency` True the N will be considered?

**Comment by friedpa** [comment] 2021-07-28 08:49
No, I mean for the sixth digit the aligment should look like this:

![grafik](https://user-images.githubusercontent.com/42890695/127292984-388812f8-235c-4cde-aee1-ae2233ce8030.png)

The inner frame should be very close around the digits so that no border is disturbing the recognition.

**Comment by Kev0123** [comment] 2021-07-28 10:14
Its already close on the left side
![Screenshot_20210728-121332](https://user-images.githubusercontent.com/19821853/127305852-606d916e-09da-4223-ba7c-0b750b83b1d8.png)

**Comment by jomjol** [comment] 2021-07-28 18:34
@Kev0123 The algorithm works as follows
1. Replace the "N" with the last know value from PreValue
2. Check if this new reading is consistent. This means if for e.g. it reads: 12.49 --> 12.**4**0 it will assume, that there was a zero crossing in the last digit and corrects the 12.40 --> 12.50
This naturally fails, if the last digits does not show all values. Because than the zero crossing cannot be detected in any cases.

**Comment by jomjol** [comment] 2021-07-28 20:07
Habe gerade das neue tflite-File erzeugt. Du kannst es hier runterladen und testen: https://github.com/jomjol/neural-network-digital-counter-readout/blob/master/dig1110s1q.tflite

Ich habe es aber selbst noch nicht getest. Bei mir läuft es über das WE und dann lade ich es ggf. in die Rolling hoch.

**Comment by Kev0123** [comment] 2021-07-29 07:00
After investigating a bit I found that the algorithm acts a bit strange. 
True                    Read                       Output
113.7290           113.7290               113.7290
113.73(0)8         113.72NaN8        113.7298
113.7353           113.7353               113.7298  (no negatives allowed) --> wrong output. The last value was correct identified multiple times over hours.

(0) means not really a 0 
![10_8_20210729-065150](https://user-images.githubusercontent.com/19821853/127446026-374eedcc-a296-4b18-8930-80483ea9c5e0.jpg)

Is the only chance to correct this behaviour to enable negatives?
Is there a chance maybe to implement a counter, if x-times a lower value  after a NaN is detected it will be used?

The new model is recognizing just fine!

**Comment by wokkeltje13** [comment] 2021-07-31 07:22
Thanks for the nice work you did, but I also have some misreadings (some numbers are alwasy wrong like the 5 on a black background reads as a 6 or the transition between the 7 and 8 (red background) that shows as a 4. I have attached the numbers in both collor combinations and also some misreadings (in the errr folder). I hope you can add them to the database. 
let me know if you need more
[Numbers.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6910836/Numbers.zip)
<img width="749" alt="Electriciteitsmeter-Error2" src="https://user-images.githubusercontent.com/57153640/127732200-73ea397b-7b80-4d95-9e37-8261b4d92452.png">
<img width="301" alt="Electriciteitsmeter-Error3" src="https://user-images.githubusercontent.com/57153640/127732300-fee24a61-aa90-4b4c-99d5-45b8943d8753.png">
In Belgium our electricity meter is turning back if you have PV panels on the roof. But this is working in the module

**Comment by Kev0123** [comment] 2021-07-31 07:30
Another info, wich may help is that most of the times I get this wrong reading after a random reboot. Right after start the picture is all over the place and I think the time after boot until making a picture is to short. The system seems to strugle with other things and the first picture is always messed up. 
I'm testing a longer time period between measurements. First it was 3min wich seems to lead the esp in random rebboots every few hours.
Now with 5min it seems to be better, but I just tested this since last evening.

**Comment by jomjol** [comment] 2021-08-01 06:45
The timing of the start should not be the problem. At least not, if you run it without access through the server. The initialization routine and the first recognition are time sequentially. Changing the time period only affects the second measurement. 

Thanks for the number, I will incorporate your numbers in the next training!

**Comment by wokkeltje13** [comment] 2021-08-02 15:40
The issue just after a restart seems to be visible on my setup also, but not always. Below is caused by the reboot after an OTA
Recognition is probably done before rotation of the image causing a strange result.
![image](https://user-images.githubusercontent.com/57153640/127887172-bf023684-d445-424b-b570-50c49fe2f4da.png)
Next reading is back OK.

**Comment by jomjol** [comment] 2021-08-02 17:21
@wokkeltje13 a reading before the alignment is not possible, as this is a linear flow from taking the image over rotation, alignment, ... . It can happen, that you just access the web server, if it is somewhere between the steps, so you might see a non rotated image. There is the plan to give a warning, that this is an intermediate image, but not implemented yet.
If you see the rotation after the final processing, this means, that the alignment did not work. So the alignmentmarks are not detected.

**Comment by andreashergert1984** [comment] 2021-08-04 18:46
> The issue just after a restart seems to be visible on my setup also, but not always. Below is caused by the reboot after an OTA
> Recognition is probably done before rotation of the image causing a strange result.
> ![image](https://user-images.githubusercontent.com/57153640/127887172-bf023684-d445-424b-b570-50c49fe2f4da.png)
> Next reading is back OK.

i got the same strange behavior on 8.0.5:
after reboot: 
![image](https://user-images.githubusercontent.com/36455093/128236036-f6e4e2bc-579a-4e26-b143-4b0965f2164f.png)
but in alignment config it´s fine:
![image](https://user-images.githubusercontent.com/36455093/128236128-8c0445a7-0e06-46f5-aba6-8eac41a7a022.png)
but even after next runs: wrongly rotated:
![image](https://user-images.githubusercontent.com/36455093/128237419-28594671-ce5c-487d-b2cc-fc08279f2b21.png)

**Comment by Kev0123** [comment] 2021-08-09 11:31
Now there was another issue with the transmitted value.
The mqtt send only empty messages 
![Screenshot_20210809-132843](https://user-images.githubusercontent.com/19821853/128699711-241b0f58-cd68-4252-b9fb-88425f040d1b.png)
After reboot it was fine. The log said it was connected all the time.

**Comment by jomjol** [comment] 2021-08-09 19:33
In the current version, there is a problem in case there is a consistency error. Then the mqtt contains text, which is a problem for a number based version. In the new rolling this has been removed.

Please test this version.

**Comment by Kev0123** [comment] 2021-08-09 19:44
I'm currently on 8.0.5 which version do you mean with "new rolling" ?

**Comment by jomjol** [comment] 2021-08-09 19:46
https://github.com/jomjol/AI-on-the-edge-device/tree/rolling

**Comment by Kev0123** [comment] 2021-08-09 20:02
No difference there still "null" in ioBroker

**Comment by jomjol** [comment] 2021-08-10 18:03
Can you send a screenshot of the homepage and the logfile?

**Comment by Kev0123** [comment] 2021-08-10 18:26
![Screenshot_20210810-202558](https://user-images.githubusercontent.com/19821853/128914726-9f9d9eb8-bf9a-43e2-85e3-5f4e03725c24.png)
![Screenshot_20210810-202510](https://user-images.githubusercontent.com/19821853/128914740-6a2ebbd9-9259-4af7-b3d5-2475087de494.png)

**Comment by jomjol** [comment] 2021-08-10 20:13
For me it looks, like the problem is in the iobroker. This is all looking okay.

**Comment by Kev0123** [comment] 2021-08-11 06:18
Its the wrong type of data
![Screenshot_20210811-081512](https://user-images.githubusercontent.com/19821853/128979078-61930698-c4a4-4f2d-a774-630f047e5cb7.png)
Its a string not a number

**Comment by jomjol** [comment] 2021-08-11 16:03
This could be the problem of the version 8.0.5 - where the mqtt value is sometimes a string (in case of error message).
In the current rolling this has been corrected. But you need to delete the string values manually to the rid of this problem.

**Comment by Kev0123** [comment] 2021-08-11 16:10
Shouldn't be ever new value be written as a number?
This is not the case.

**Comment by wokkeltje13** [comment] 2021-08-11 17:02
> The timing of the start should not be the problem. At least not, if you run it without access through the server. The initialization routine and the first recognition are time sequentially. Changing the time period only affects the second measurement.
> 
> Thanks for the number, I will incorporate your numbers in the next training!

Any idea when my numbers will be integrated? Everything is working ok, but it would be better if the reading of my numbers would be better. thanks

**Comment by jomjol** [comment] 2021-08-11 18:40
@Kev0123: sorry did not understand what you mean: "Shouldn't be ever new value be written as a number?"

**Comment by jomjol** [comment] 2021-08-11 18:55
Bei mir war es leider so, dass ich zwei identische Werte, einmal als number und einmal als string hatte. Die Stringwerte habe ich manuell löschen müssen.

**Comment by jomjol** [comment] 2021-08-11 19:40
@wokkeltje13 I have trained them meanwhile, but this is not running stabile on my system. Therefore I have not published it yet. Currently I'm on holiday, but you can test by yourself: [dig1200s1q.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6970966/dig1200s1q.zip)

**Comment by jomjol** [comment] 2021-08-12 05:29
@wokkeltje13 - tested it over night. Seems working and is now integrated in the newest release (v8.1.0)

Also the bug with the string in the "value" has been correct.

**Closed by jomjol** 2021-08-12 05:29 UTC
