### ISSUE TITLE
boot in setup mode

### ISSUE THREAD

**Issue by lucaobermaier** [jomjol/AI-on-the-edge-device#1475] opened 2022-12-03 22:09 UTC
### The Problem

ESP reboots always in setup mode.
*edit*
after setting config setup to false and rebooting the complete config file is delete. 

### Version

13.0.3

### Logfile

```shell
[      32] 2022-12-03T20:21:44	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      32] 2022-12-03T20:21:44	<INF>	[MQTT INTERFACE] Init successful
[      37] 2022-12-03T21:21:49	<ERR>	[MQTT INTERFACE] Failed to publish topic 'wasserzaehler/status', skipping all MQTT publishings in this round!
[       4] 2022-12-03T20:22:02	<INF>	[MAIN] =================================================
[       4] 2022-12-03T20:22:02	<INF>	[MAIN] ==================== Startup ====================
[       4] 2022-12-03T20:22:02	<INF>	[MAIN] =================================================
[       4] 2022-12-03T20:22:02	<INF>	[MAIN] Branch: 'HEAD', Revision: e9e1358+, Date/Time: 2022-12-02 21:22, Web UI: Release: v13.0.3 (Commit: e9e1358+) 
[       4] 2022-12-03T20:22:02	<INF>	[MAIN] Reset reason: Via esp_restart
[       8] 2022-12-03T20:22:06	<INF>	[MAIN] =================================================
[       8] 2022-12-03T20:22:06	<INF>	[MAIN] ================== Main Started =================
[       8] 2022-12-03T20:22:06	<INF>	[MAIN] =================================================
[       8] 2022-12-03T20:22:06	<WRN>	[MAIN] Web UI version (e9e1358) does not match firmware version (e9e1358+) !
[      10] 2022-12-03T20:22:08	<INF>	[MAIN] Initialization completed successfully!
[      14] 2022-12-03T20:22:13	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      14] 2022-12-03T20:22:13	<INF>	[MQTT INTERFACE] URI: mqtt://IP-ADRESS:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      14] 2022-12-03T20:22:13	<INF>	[MQTT INTERFACE] Init
[      14] 2022-12-03T20:22:13	<INF>	[MQTT INTERFACE] Init successful
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<INF>	[MQTT INTERFACE] URI: mqtt://IP-ADRESS:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      14] 2022-12-03T20:22:13	<INF>	[MQTT INTERFACE] Init
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      14] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:13	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      15] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Disconnected! Going to re-connect...
[      16] 2022-12-03T20:22:14	<WRN>	[MQTT INTERFACE] Could not start client (ret=-1), retrying...
[      16] 2022-12-03T20:22:14	<INF>	[MQTT INTERFACE] Init successful
[      27] 2022-12-03T21:22:25	<ERR>	[MQTT INTERFACE] Failed to publish topic 'wasserzaehler/status', skipping all MQTT publishings in this round!
[      10] 2022-12-03T20:25:12	<INF>	[SNTP] NTP Status OK
[      10] 2022-12-03T21:25:12	<INF>	[SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[      10] 2022-12-03T21:25:12	<INF>	[MAIN] =================================================
[      10] 2022-12-03T21:25:12	<INF>	[MAIN] ================== Main Started =================
[      10] 2022-12-03T21:25:12	<INF>	[MAIN] =================================================
[      10] 2022-12-03T21:25:12	<WRN>	[MAIN] Web UI version (e9e1358) does not match firmware version (e9e1358+) !
[      12] 2022-12-03T21:25:14	<INF>	[MAIN] Initialization completed successfully!
[      16] 2022-12-03T21:25:19	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      16] 2022-12-03T21:25:19	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      16] 2022-12-03T21:25:19	<INF>	[MQTT INTERFACE] Init
[      16] 2022-12-03T21:25:19	<INF>	[MQTT INTERFACE] Init successful
[      16] 2022-12-03T21:25:19	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      16] 2022-12-03T21:25:19	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      16] 2022-12-03T21:25:19	<INF>	[MQTT INTERFACE] Init
[      17] 2022-12-03T21:25:19	<INF>	[MQTT INTERFACE] Connected
[      17] 2022-12-03T21:25:19	<INF>	[MQTT SERVER] MQTT - Sending Homeassistant Discovery Topics (Meter Type: water, Value Unit: m³ , Rate Unit: m³/h)...
[      18] 2022-12-03T21:25:21	<INF>	[MQTT SERVER] Publishing static MQTT topics...
[      18] 2022-12-03T21:25:21	<INF>	[MQTT SERVER] Publishing system MQTT topics...
[      18] 2022-12-03T21:25:21	<INF>	[MQTT INTERFACE] Init successful
[      13] 2022-12-03T20:25:38	<INF>	[SNTP] NTP Status OK
[      13] 2022-12-03T21:25:38	<INF>	[SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[      13] 2022-12-03T21:25:38	<INF>	[MAIN] =================================================
[      13] 2022-12-03T21:25:38	<INF>	[MAIN] ================== Main Started =================
[      13] 2022-12-03T21:25:38	<INF>	[MAIN] =================================================
[      13] 2022-12-03T21:25:38	<WRN>	[MAIN] Web UI version (e9e1358) does not match firmware version (e9e1358+) !
[      15] 2022-12-03T21:25:40	<INF>	[MAIN] Initialization completed successfully!
[      20] 2022-12-03T21:25:45	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      20] 2022-12-03T21:25:45	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      20] 2022-12-03T21:25:45	<INF>	[MQTT INTERFACE] Init
[      20] 2022-12-03T21:25:45	<INF>	[MQTT INTERFACE] Init successful
[      20] 2022-12-03T21:25:45	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      20] 2022-12-03T21:25:45	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      20] 2022-12-03T21:25:45	<INF>	[MQTT INTERFACE] Init
[      20] 2022-12-03T21:25:45	<INF>	[MQTT INTERFACE] Connected
[      20] 2022-12-03T21:25:45	<INF>	[MQTT SERVER] MQTT - Sending Homeassistant Discovery Topics (Meter Type: water, Value Unit: m³ , Rate Unit: m³/h)...
[      20] 2022-12-03T21:25:45	<INF>	[MQTT SERVER] Publishing static MQTT topics...
[      20] 2022-12-03T21:25:45	<INF>	[MQTT SERVER] Publishing system MQTT topics...
[      21] 2022-12-03T21:25:46	<WRN>	[MQTT INTERFACE] Could not start client (ret=-1), retrying...
[      21] 2022-12-03T21:25:46	<INF>	[MQTT INTERFACE] Init successful
[      21] 2022-12-03T21:25:46	<ERR>	[MQTT INTERFACE] Could not start client (ret=-1)!
[       4] 2022-12-03T20:27:12	<INF>	[MAIN] =================================================
[       4] 2022-12-03T20:27:12	<INF>	[MAIN] ==================== Startup ====================
[       4] 2022-12-03T20:27:12	<INF>	[MAIN] =================================================
[       4] 2022-12-03T20:27:12	<INF>	[MAIN] Branch: 'HEAD', Revision: e9e1358+, Date/Time: 2022-12-02 21:22, Web UI: Release: v13.0.3 (Commit: e9e1358+) 
[       4] 2022-12-03T20:27:12	<INF>	[MAIN] Reset reason: Via esp_restart
[       8] 2022-12-03T20:27:16	<INF>	[MAIN] =================================================
[       8] 2022-12-03T20:27:16	<INF>	[MAIN] ================== Main Started =================
[       8] 2022-12-03T20:27:16	<INF>	[MAIN] =================================================
[       8] 2022-12-03T20:27:16	<WRN>	[MAIN] Web UI version (e9e1358) does not match firmware version (e9e1358+) !
[      10] 2022-12-03T20:27:18	<INF>	[MAIN] Initialization completed successfully!
[      14] 2022-12-03T20:27:23	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      14] 2022-12-03T20:27:23	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      14] 2022-12-03T20:27:23	<INF>	[MQTT INTERFACE] Init
[      14] 2022-12-03T20:27:23	<INF>	[MQTT INTERFACE] Init successful
[      14] 2022-12-03T20:27:23	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      14] 2022-12-03T20:27:23	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      14] 2022-12-03T20:27:23	<INF>	[MQTT INTERFACE] Init
[      14] 2022-12-03T20:27:23	<INF>	[MQTT SERVER] Publishing static MQTT topics...
[      14] 2022-12-03T20:27:23	<INF>	[MQTT SERVER] Publishing system MQTT topics...
[      14] 2022-12-03T20:27:23	<INF>	[MQTT INTERFACE] Init successful
[      15] 2022-12-03T20:27:23	<ERR>	[MQTT INTERFACE] Could not start client (ret=-1)!
[      12] 2022-12-03T21:02:43	<INF>	[SNTP] NTP Status OK
[      12] 2022-12-03T22:02:43	<INF>	[SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[      12] 2022-12-03T22:02:43	<INF>	[MAIN] =================================================
[      12] 2022-12-03T22:02:43	<INF>	[MAIN] ================== Main Started =================
[      12] 2022-12-03T22:02:43	<INF>	[MAIN] =================================================
[      12] 2022-12-03T22:02:43	<WRN>	[MAIN] Web UI version (e9e1358) does not match firmware version (e9e1358+) !
[      14] 2022-12-03T22:02:45	<INF>	[MAIN] Initialization completed successfully!
[      18] 2022-12-03T22:02:49	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      18] 2022-12-03T22:02:49	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      18] 2022-12-03T22:02:49	<INF>	[MQTT INTERFACE] Init
[      18] 2022-12-03T22:02:49	<INF>	[MQTT INTERFACE] Init successful
[      18] 2022-12-03T22:02:49	<INF>	[FLOW MQTT] Digitizer interval is 5.0 minutes => setting MQTT LWT timeout to 12.5 minutes.
[      18] 2022-12-03T22:02:49	<INF>	[MQTT INTERFACE] URI: mqtt://192.168.1.253:1883, clientname: wasser, user: luca, password: XXXXXXXX, maintopic: wasserzaehler, last-will-topic: wasserzaehler/connection, keepAlive: 750
[      18] 2022-12-03T22:02:49	<INF>	[MQTT INTERFACE] Init
[      18] 2022-12-03T22:02:49	<INF>	[MQTT SERVER] Publishing static MQTT topics...
[      18] 2022-12-03T22:02:50	<INF>	[MQTT SERVER] Publishing system MQTT topics...
[      19] 2022-12-03T22:02:50	<INF>	[MQTT INTERFACE] Init successful
[      20] 2022-12-03T22:02:51	<ERR>	[MQTT INTERFACE] Could not start client (ret=-1)!
[    1563] 2022-12-03T22:28:34	<ERR>	[MQTT INTERFACE] Failed to publish topic 'homeassistant/sensor/wasserzaehler/CPUtemp/config', skipping all MQTT publishings in this round!
```

**Comment by caco3** [comment] 2022-12-10 16:11
I think this was caused by one of the MQTT issues we had and should no longer be a problem with the latest version.
So I close it for now.

**Closed by caco3** 2022-12-10 16:11 UTC
Labels: bug
