### ISSUE TITLE
192.168.0.xxx refused to connect.

### ISSUE THREAD

**Issue by Varkzor** [jomjol/AI-on-the-edge-device#948] opened 2022-08-26 08:22 UTC
Hi everyone,

I tried to set-up a device for a home monitoring project.
I uploaded with success the software and followed the steps.
How-ever when i connect the device i get mixed results.
Sometimes after a reset (without any configuration done yet), it boots, triggers the 5 short red light flashes for wifi setup, and then 3 red flashes when connection was made. In such a case, it doesn't allow me to connect to the configuration website.

Sometimes after a reset (still without full config done), it boots, triggers 5 red flashes, triggers the camera-flashlight, and then 3 red flashes.
In this case i actually can connect to the website to do the configuration.

I can't re-enact when/how to make either case happen, it's pure coincidence it seems...

I will try to reflash the device again.
But if anyone would have any idea on this behavior, all help would be welcome!

Best regards
/A

**Comment by Varkzor** [comment] 2022-08-26 08:41
Quick update, reflashing the device and reloading the data to the SD card as a 'fresh' install, didn't trigger the full availability of the web-page (and triggering the camera flash at first boot-up)...

**Comment by pos-ei-don** [comment] 2022-08-26 08:44
Try a different Webbrowser, especially a mobile Browser works better, sometimes.

**Comment by Varkzor** [comment] 2022-08-26 08:47
Tried 2 browsers, now tried my phone also, it's really an issue with the the website not being accessible. The device does show up in my router with it's IP address.
However the IP gives strange results as described above.
So far in the last 12 hours roughly, I only managed to open the configuration web page 2 times, after numerous resets and 2 reinstalls... :-(

**Comment by Matzebhv** [comment] 2022-08-26 08:50
Try a different SD-Card. I have 2 cards here which wont work. If the flashlight does not come up during boot the device is not fully startet. I recommend small sandisc.

**Comment by Varkzor** [comment] 2022-08-26 09:01
Hmm i use a 2gb Samsung card.
Is there a way to know/see in logs what the issue could be?
(not sure how to connect to the logs of the device, and if i.e. this is possibla via OTA? like with ESPHOME?)

**Comment by Matzebhv** [comment] 2022-08-26 09:21
This is the part fom the documantation:
Due to the limited availability of GPIOs (OV2640, Flash-Light, PSRAM & SD-Card) the communication mode to the SD card is limited to 1-line SD-Mode. It showed up, that this results in problems with very large SD-Cards (64GB, sometimes 32 GB) and some no name low cost SD-cards.
---
As flashing and configuring is absolut straight forward you seem to have a faulty esp or the esp can not read your sd-card. I have had simmilar problems with 2 cheap cards fom amazon. I recommend to try a different sd-card.

**Comment by Matzebhv** [comment] 2022-08-26 09:26
You should check your powersupply also. If you have a ps wich is to weak and drops voltage during flashlight on, this wont work too.

**Comment by Varkzor** [comment] 2022-08-26 11:50
maybe i made an issue with the cluster size? i used Rufus, set it to FAT32, but cluster size 32k cannot be selected.
Maybe that is the whole root-cause of the issue?

How do you assign the correct clustersize with the formatting event?

**Comment by Varkzor** [comment] 2022-08-26 11:51
checked alternate powersupply by the way, no advance :(

**Comment by Matzebhv** [comment] 2022-08-26 15:17
> maybe i made an issue with the cluster size? i used Rufus, set it to FAT32, but cluster size 32k cannot be selected. Maybe that is the whole root-cause of the issue?
> 
> How do you assign the correct clustersize with the formatting event?

i have formatted the card under windows as fat32

**Comment by Varkzor** [comment] 2022-08-26 15:30
Oh and abig thanks by the way for trying to help!!!
I found 1 more 32Gig card at home and will try with that one also.

**Comment by Varkzor** [comment] 2022-08-26 15:52
Tried with 2nd SD card no luck, now trying to reflash the device with the 32G SD card.
Will load the files again after i re-format the SD card once again

**Comment by Varkzor** [comment] 2022-08-26 16:08
Well, same result...
not sure what is wrong, but without debugging option this is a pretty lost cause.
With the smaller SD card it worked 2 times in about 4 hours or so, now it doesn't, no clear reason or pointer to why it is not working.
Anyone else who knows how to actually debug this thing to see what is the root cause so i can fix it?

**Comment by pos-ei-don** [comment] 2022-08-26 16:20
Zum formatieren selbst kann ich nur
Diesen hier empfehlen. 
Der hat sich quasi als Standard etabliert. 
Er kann auch Partitons alignment, etc. 

Ob er Das ergebnis verbessert, kann ich nicht einschätzen. 

https://www.sdcard.org/downloads/formatter/

**Comment by Varkzor** [comment] 2022-08-26 16:27
ich habe windows gebraucht, rufus, ich habe 2 karten gebraucht...

Ich bleibe dabei, bei die 1ste karte, hat das 2 mahl functioniert dass ich auf der website kam und die configuration starten könnte.
Weil das am buro war bin ich zu die garage gegehen und das wirktte nicht mehr.
Danach hab ich versucht alles wieder neu zu flashen fur einer frischer start, aber hat nur noch 1 mahl marchiert, zeitwegen nicht mehr...

Wifi marchiert, der software macht verbindung, aber der website offent nicht.
Auch hab ich gesehen dass er die 2 mahl dass er functioniert hat, dass die 2 mahl er nach 5 'flashen' die camera-led activiert hat, die andere mahlen hat der camera-flash niemahls activiert...

Niemand derr wiss wie man logs nachsehen kann?
via OTA? (over the air) vielleicht?

**Comment by Varkzor** [comment] 2022-08-26 16:33
![IP address](https://user-images.githubusercontent.com/50747528/186951154-83de7ca8-f490-4787-b953-40e92aa6568c.PNG)

So the software does make connection with the wifi.
But why i can't access the web page is not clear and no idea how to debug what the issue is:

![web page](https://user-images.githubusercontent.com/50747528/186951332-10228e9e-ba61-4777-934a-27b137e145ed.PNG)

**Comment by caco3** [comment] 2022-08-26 19:30
A logfile can be accessed direcly throg the following URL: `http://<IP>/fileserver/log/message/log_2022-08-26.txt`.
Make sure to select the current date (or an older one).

How ever:
 - I am not sure if on your issue already a log file is available.
 - The device might not yet have the word time since the NTP client might not be up yet, not sure what date it then has.

Does the device respond to pings?

**Comment by Varkzor** [comment] 2022-08-26 23:06
Good point, i didn't try that yet, but i did just now and the ping was successful:

![image](https://user-images.githubusercontent.com/50747528/187001350-25667f6c-e264-4e23-9708-29a0b19989ee.png)

I will try to see nw if i can access any logs

**Comment by Varkzor** [comment] 2022-08-26 23:09
Tried to access the logfiles, but same issue as with configuration page access:

![image](https://user-images.githubusercontent.com/50747528/187001542-cdd6a315-8566-4315-9046-0baf1636e3ea.png)

P.S. Thanks again for trying to help me with this, very much appreciated guys!!!
Have a good weekend!
Hopefully i can somehow get this to work in the coming 2 days 👍

**Comment by Varkzor** [comment] 2022-08-27 09:45
@jomjol , any chance you might be able to help me?
Sorry for asking, but i'm totally lost, have no idea why it wouldn't work.
Certainly since out of the different installs it did connect to the web page, and the other 100s of times it didn't.

**Comment by Varkzor** [comment] 2022-08-27 09:52
oh and @jomjol excellent project by the way, very very nicely done! :)

**Comment by pos-ei-don** [comment] 2022-08-27 10:01
Maybe, someone can you sell a working esp with sd card, but I do not syany other possibility to help you.

Anyway, would try to reformat the sd card with my proposed Tool. Windows is known to not ideally Format sd cards. That exactly is the purpose of such a Tool.

**Comment by caco3** [comment] 2022-08-27 10:07
I did not have problems with the standard Windows formating tool!

You also could check the system log through the UART, eg. using PUTTY.

Also, run ping with `-n 99999` appended **while** you try to access the web interface.
When my Wifi connection was not good enough (only internal antenna used), the ping was fine **until** I started to try to reach the web interface.

**Comment by Varkzor** [comment] 2022-08-27 10:34
> Maybe, someone can you sell a working esp with sd card, but I do not syany other possibility to help you.
> 
> Anyway, would try to reformat the sd card with my proposed Tool. Windows is known to not ideally Format sd cards. That exactly is the purpose of such a Tool.

I really doubt it has to do with the SD card, it actually worked twice and it's i.e. reading the wifi config etc.

Yu still might be right, but in my mind this seems odd as an issue, then also i would have never been able to access the web interface at all before i would guess.

**Comment by pos-ei-don** [comment] 2022-08-27 10:35
> I did not have problems with the standard Windows formating tool!

It Depends, if the Partition and Cluster size is already correct before you format. If you had a different filesystem on the card (like ext4), it is probably not.

**Comment by Varkzor** [comment] 2022-08-27 10:35
> I did not have problems with the standard Windows formating tool!
> 
> You also could check the system log through the UART, eg. using PUTTY.
> 
> Also, run ping with `-n 99999` appended **while** you try to access the web interface. When my Wifi connection was not good enough (only internal antenna used), the ping was fine **until** I started to try to reach the web interface.

Any info on how to access system log using Putty?

Ping still works even when i make web-calls

**Comment by Varkzor** [comment] 2022-08-27 10:40
![image](https://user-images.githubusercontent.com/50747528/187026612-f54139f6-a53a-4b42-bb86-abb894282d5b.png)

never going above 140ms ping when refreshing the webpage. Seems still OK to me.

**Comment by caco3** [comment] 2022-08-27 10:44
ping and connectivity seem to be ok.

I would need to check with putty this evening since I dont use windows myself and am away now.

**Comment by Varkzor** [comment] 2022-08-27 10:54
The only thing which keeps catching my analysis about the issue is that when resetting, the following options were visible:

2 times the website access worked:
> Reset -> Quick red light blink -> 5 times longer blink for web initiation -> camera flashlight went on -> Website was accessible.

all other times i couldn't access the website:
> Reset -> Quick red light blink -> 4 times blink -> quick red light blink -> 3 times blink
> OR: Reset -> Quick red light blink -> 3 times blink -> quick red light blink -> 3 times blink
> OR: Reset -> Quick red light blink -> 5 times blink -> quick red light blink -> 3 times blink

What I wonder now is if the 'quick red light blink' here means it's continuously re-initiating the whole set-up procedure and it's hanging there?
That would explain why it's not going 1 step further.

**Comment by Varkzor** [comment] 2022-08-27 10:57
> ping and connectivity seem to be ok.
> 
> I would need to check with putty this evening since I dont use windows myself and am away now.

Thanks in advance Caco3!
And again big thanks for trying to clear up my mystery :-D

**Comment by Varkzor** [comment] 2022-08-27 12:16
Ok quick update, i did a 500th reset lol.
i unplugged the device, plugged back in the sd card, pushed it back in the power, and now it's the 3rd time it initiated the camera, website again accessibe...

Unfortunately it's on my desk, so not at my watermeter :-P
Still not ideal.
I have to set up this device at a remote location, so i need to be able to install & config the device in let's say 1 hour or so, so not really workable yet for me.

I'll do - another - try now at the watermeter, deplugging, pulling out SD card, and putting everything together again.

**Comment by Varkzor** [comment] 2022-08-27 12:22
And, no success...
Plugging it at the water meter for testing: no camera initiation again.
removed the files from sd card, copied the initial files again.
put back the sd card and plugged it back into the power:

And again no camera intiation :-(

Pffffffff - i guess i'll have to put my foot on the device at some point...

**Comment by Kalli01** [comment] 2022-08-27 13:34
I don't know if it helps you with your problem.

I have 3 modules in use. The web interface is better accessible via my cell phone than via the computer.
In the basement the wifi is very weak. Through a reapeter I could improve the wifi strength. Now the interface is better reachable.
Maybe you can try to improve the wifi.

**Comment by cbho** [comment] 2022-08-27 14:09
Have you tried attaching an external antenna to the esp?
I've had trouble with a device that led me to reflash it a zillion times, reformat sd-card, repeating setup etc - adding an external antenna changed everything (even though it was pretty close to an access point and the connection looked good in the routers statistics...)

**Comment by jomjol** [comment] 2022-08-27 16:17
Firstly be sure, the device is working correctly by installing it direct next to a good wlan access point. By this you can exclude hardware failures. The setup will also work with rubish images from a wall. Just go once through every step.

If you already have problems in this step:
1) ensure a good power supply (5V!, >1000mA) 
2) have a lock in the serial interface (e.g. with putty). Maybe you can post it. There you can see much more exactly at which step it fails.

If this is okay and it is not working in the basement, you most propaply have a weak wifi connection. Remember, that this device has only a very limited server onboard, that might be not error tolerant enough for a very weak connection.

**Comment by Varkzor** [comment] 2022-08-27 22:29
Thanks a lot for the info guys,
Since at several trials it was really on top of the access point, i guess the only thing could be is the lack of mili-amps, i think the one at my water meter is 800mA, i'll see if i can find a higher one.

The last time it worked it was at my desk on a usb-C connector. Not sure how many miliAmps that gives by default.

BR
Varkzor

**Comment by Varkzor** [comment] 2022-08-27 22:33
on the USB 3.0 it only worked once, it failed every other reset again.
Just for info.

Thanks at everyone giving input, i still hope i can make the device work.
For the future install i will put a power socket wifi signal in the basement just next to the device, that was the goal as there is barely any wifi in the place where it will be installed.

i will try to find a 1000+ mAmp charger tomorrow, if that doesn't fix it, then putty is the only option i guess.
I just don't know how to connect with Putty to the device, i'll see if i can look into that somehow.
if anone has info how to get into those loggings, that would be really helpful!

**Comment by Varkzor** [comment] 2022-08-28 08:42
Tried again this morning, not success.
Reflashed the device, deleted and reloaded the files on the SD card, connected it to a 2000mA 5v charger.

result: quick red blink, 5 red blinks, no camera-flash initiation...

Now my question really is, how do i get into a Putty?
I checked online, but most refer to connecting it via Serial, but then i'm stuck using the microusb connector bord i use, and that one will (unless mistaken) only feed 500mA to a USB device? Or does this also depend to usb 1.0, 2.0 or 3.0. All them ports i think are minimum USB2.0.

Over USB cable i wonder if i can easily do it with the arduino program perhaps, but never done it without loading the software over arduino.

/A

**Comment by Varkzor** [comment] 2022-08-28 08:46
Was able to access the logger via Arduino, i'll analyze it and get back with my findings.

BR
Alex

**Comment by Varkzor** [comment] 2022-08-28 09:17
10:45:21.518 -> [0;32mI (9761) sntp: Time is not set yet. Connecting to WiFi and getting time over NTP.[0m
10:45:21.518 -> [0;32mI (9761) sntp: Initializing SNTP[0m
10:45:21.518 -> [0;32mI (9761) sntp: Waiting for system time to be set... (1/10)[0m
10:45:23.520 -> [0;32mI (11761) sntp: Waiting for system time to be set... (2/10)[0m
10:45:24.564 -> W (12781) wifi:<ba-add>idx:1 (ifx:0, 34:2c:c4:38:1c:0e), tid:0, ssn:2, winSize:64
10:45:25.529 -> [0;32mI (13761) sntp: Waiting for system time to be set... (3/10)[0m
10:45:27.502 -> TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
10:45:27.502 -> Logfile opened: /sdcard/log/message/log_2022-08-28.txt
10:45:27.549 -> [0;32mI (15781) sntp: The current date/time in Berlin is: Sun Aug 28 10:45:27 2022[0m
10:45:27.549 -> [0;32mI (15781) sntp: The current date/time in Berlin is: 2022-08-28_10:45[0m
10:45:27.549 -> timeist 20220828-104527
10:45:27.549 -> Logfile opened: /sdcard/log/message/log_2022-08-28.txt
10:45:27.597 -> Logfile opened: /sdcard/log/message/log_2022-08-28.txt
10:45:27.597 -> Logfile opened: /sdcard/log/message/log_2022-08-28.txt
10:45:27.644 -> time 20220828-104527
10:45:29.512 -> [0;32mI (17751) BLINK: Blinken - done[0m
10:45:31.614 -> [0;33mW (19871) cam_hal: Failed to get the frame on time![0m
10:45:31.614 -> [0;31mE (19871) main: esp_camera_fb_get: Camera Capture Failed[0m
10:45:31.614 -> Logfile opened: /sdcard/log/message/log_2022-08-28.txt
10:45:31.661 -> [0;32mI (19891) server_ota: Reboot in 5sec[0m

So conclusion so far: The camera initialization is going wrong, but why is not clear :-(

**Comment by Varkzor** [comment] 2022-08-28 09:20
For the rest it kind of seems things are OK:

10:45:13.653 -> [0;32mI (1871) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
10:45:15.613 -> Init Camera
10:45:15.613 -> [0;32mI (3881) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:2 [0m
10:45:15.660 -> [0;32mI (3881) cam_hal: cam init ok[0m
10:45:15.660 -> [0;32mI (3881) sccb: pin_sda 26 pin_scl 27[0m
10:45:15.660 -> [0;32mI (3881) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
10:45:15.660 -> [0;32mI (3921) camera: Detected camera at address=0x30[0m
10:45:15.660 -> [0;32mI (3921) camera: Detected OV2640 camera[0m
10:45:15.660 -> [0;32mI (3921) camera: Camera PID=0x26 VER=0x42 MIDL=0x7f MIDH=0xa2[0m
10:45:15.754 -> [0;32mI (4001) cam_hal: buffer_size: 32768, half_buffer_size: 4096, node_buffer_size: 2048, node_cnt: 16, total_cnt: 15[0m
10:45:15.754 -> [0;32mI (4001) cam_hal: Allocating 61440 Byte frame buffer in PSRAM[0m
10:45:15.801 -> [0;32mI (4011) cam_hal: cam config ok[0m
10:45:15.801 -> [0;32mI (4011) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8[0m
10:45:15.848 -> Internal Flash-LED turn off PWM
10:45:15.848 -> nach init camera: sleep for : 200ms

**Comment by Varkzor** [comment] 2022-08-28 09:22
And then even worse, why does it exceptionally work.
rather a hardware issue then?

**Comment by Varkzor** [comment] 2022-08-28 09:36
Ok... you can close the issue i think...........

The issue was: the camera was not solid enough mounted inside the slide slot.
It was not deep enough.......

Hence it worked 3 times by luck and 10000 times without luck.

Oh boy...

Apologies for all who wasted time on this! :-(

**Comment by friedpa** [comment] 2022-08-28 10:29
It is also a learning curve for the community, we all learned something out of it....
@jomjol: is it possible to write some critical stages of the initialisation to a "Boot" LOG? Reason: as we have seen now over the last two years the Serial Log clears up a lot of failures, but for the most users the Serial Log usage is a problem....

**Comment by Varkzor** [comment] 2022-08-28 10:48
Also 1 more question, is it possible to completely redo the initial reconfiguration from the web page?
I have to remount it now for testing, and will remount it when i  am on-site in the remote location where it will end up in the future.

1 more thing, i'm not a very experienced user in ESP32, the biggest issue was the camera mounting on my side, i didn't follow a crucial step of opening the lid to put in the camera, i thought it was a slide-in connector, but it's actially some kind of 'open and clip down' connector.

Issue totally on my side, hard to prevent from programmer/development side.

**Comment by Matzebhv** [comment] 2022-08-28 11:09
For initial configuration set

SetupMode = true

in your config.ini

**Comment by Varkzor** [comment] 2022-08-28 12:46
Thanks guys,
Another additional question, is there a way to help the device to better learn the reference values?

Example - on my side it's totally off right now :)

![image](https://user-images.githubusercontent.com/50747528/187074787-766fc1f8-7d54-4c5e-a9a8-2757180f1753.png)

**Comment by Matzebhv** [comment] 2022-08-28 13:03
You should try out a 100 class training modell -> dig-class100*

I would also recommend to put some type of alignment marks on your meter. And it seems that your rois are to big and also not good aligned.

**Comment by Varkzor** [comment] 2022-08-28 14:36
So change this:

[Digits]
Model = /config/dig-class11_1411_s2_q.tflite

to this:

[Digits]
Model = /config/dig-class100_s1d-md-v1.0_q.tflite

or
[Digits]
Model = /config/dig-class100_0120_s2_q.tflite

?

**Comment by Varkzor** [comment] 2022-08-28 14:48
few hours later, seems to work better very suddenly:

![image](https://user-images.githubusercontent.com/50747528/187080063-e5000da1-040b-491f-8410-232ffdd53818.png)

**Comment by Matzebhv** [comment] 2022-08-28 14:57
> So change this:
> 
> [Digits] Model = /config/dig-class11_1411_s2_q.tflite
> 
> to this:
> 
> [Digits] Model = /config/dig-class100_s1d-md-v1.0_q.tflite
> 
> or [Digits] Model = /config/dig-class100_0120_s2_q.tflite
> 
> ?

Yes, you can try both and look which one works better for you.
I also would move all rois one pixel to the left as they are slightly missaligned. And you should delete your analog roi, your meter has no analog digit.

**Comment by Varkzor** [comment] 2022-08-28 15:06
i will try that thanks Matze.during config when deleting all 4 it said it would remove all of the dig and ana's..

**Comment by Matzebhv** [comment] 2022-08-28 15:11
Uncheck this one, then delete all rois.

![Screenshot 2022-08-28 171053](https://user-images.githubusercontent.com/20025244/187081112-0eb69793-76f0-4452-993c-5c909ca06de5.png)

**Comment by jomjol** [comment] 2022-08-28 16:23
> 

Sure - what type of topics are suggested?
What is already present (see main.cpp)
- Not enough PSRAM (< 4 MB)
- Camera could not be initated

What else is recommeded?
- SD-Card is not possible
- Some info about the WLAN?

**Comment by friedpa** [comment] 2022-08-28 16:58
Hallo Josef,
Deine Entscheidung :o) Aber ich denke, dass obere reicht für einen Quick Erstcheck und würde viele Stunden ersparen .... 
Liebe Grüße
Paul

**Comment by jomjol** [comment] 2022-08-28 17:12
Hallo Paul,

ergänze das gerne. Habe noch nicht verstanden, was du mit "das obere" meinst.

**Comment by Varkzor** [comment] 2022-08-28 18:25
Hey JomJol,
Einde idee dass ich noch denken kann zum beispiel ist andere signalen mit die roten led machen.
zum beispiel: 2 schnelle flashen = algemeine software config error (sd carte nicht gut, files nicht vorhanden, keine richtige interne configuration...)
3 schnelle flashen= algemeine hardware problemen: camera initialization nicht gut, Flash drive issues, ...

Nur eine idee. Gibt vielleicht mehrere optionene.


Und dann noch ein mahl, wass ein super tool dass du gemacht habe! Vielen dank, der wirkt jetzt supergut!

Mfg,
Alex

**Comment by friedpa** [comment] 2022-08-28 18:34
Das "obere" meinte Deinen Vorschlag der 4 Punkte, denke mehr ist eigentlich nicht ntwendig.
Liebe Grüße
Paul

**Comment by Varkzor** [comment] 2022-08-29 10:43
Excellent guys :-)

![image](https://user-images.githubusercontent.com/50747528/187183751-86a18b7f-07a0-40e2-8ea2-ba64d0cf4a87.png)

Last hurdle on my side: i configured it to send to MQTT but it won't load into home assistant.
I guess it has to do with my configuration.yaml which i couldn't set-up properly.
Need to do some more digging...

By the way, is there a way to see if the message was sent successfully from the device to the MQTT broker?

BR
Alex

**Comment by Matzebhv** [comment] 2022-08-29 11:25
Turn on debug -> logfile -> true.

2022-08-26T00:04:01: sent publish successful in MQTTPublish, msg_id=23855, wasserzaehler/connection, connected
2022-08-26T00:04:01: sent publish successful in MQTTPublish, msg_id=56266, wasserzaehler/uptime, 37308
2022-08-26T00:04:01: sent publish successful in MQTTPublish, msg_id=34278, wasserzaehler/freeMem, 3152867
2022-08-26T00:04:01: sent publish successful in MQTTPublish, msg_id=22098, wasserzaehler/wifiRSSI, -78
2022-08-26T00:04:01: sent publish successful in MQTTPublish, msg_id=34109, wasserzaehler/main/value, 704.529
2022-08-26T00:04:01: sent publish successful in MQTTPublish, msg_id=45903, wasserzaehler/main/error, no error
2022-08-26T00:04:01: sent publish successful in MQTTPublish, msg_id=58610, wasserzaehler/main/rate, 0.000000
2022-08-26T00:04:02: sent publish successful in MQTTPublish, msg_id=45803, wasserzaehler/main/changeabsolut, 0.000
2022-08-26T00:04:02: sent publish successful in MQTTPublish, msg_id=2895, wasserzaehler/main/raw, 00704.529
2022-08-26T00:04:02: sent publish successful in MQTTPublish, msg_id=41137, wasserzaehler/main/timestamp, 2022-08-26T00:03:18
2022-08-26T00:04:02: sent publish successful in MQTTPublish, msg_id=41115, wasserzaehler/main/json, {"value":704.529,"raw":"00704.529","error":"no error","rate":0.000000,"timestamp":"2022-08-26T00:03:18"}

**Comment by Varkzor** [comment] 2022-08-29 11:53
Thanks Matze,
I do seem to get some issues towards my Home Assistant config:
![image](https://user-images.githubusercontent.com/50747528/187195184-bf72789a-1387-4e6d-84ac-1543cab27b53.png)

**Comment by Varkzor** [comment] 2022-08-29 20:53
Hmm,
think my config is ok, however i don't see mqtt connecting in the logs like it does with you Matze:

2022-08-29T22:48:58: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-08-29T22:48:58: =============================================================================================
2022-08-29T22:48:58: =================================== Main Started ============================================
2022-08-29T22:48:58: =============================================================================================
2022-08-29T22:49:02: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-08-29T22:49:03: task_autodoFlow - next round - Round #1
2022-08-29T22:49:03: 	FlowControll.doFlow - ClassFlowMakeImage
2022-08-29T22:49:11: 	FlowControll.doFlow - ClassFlowAlignment
2022-08-29T22:50:04: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-29T22:50:07: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-29T22:50:07: Cannot load model
2022-08-29T22:50:07: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-08-29T22:50:07: 	FlowControll.doFlow - ClassFlowMQTT
2022-08-29T22:50:08: task_autodoFlow - round done
2022-08-29T22:50:08: CPU Temperature: 62.2
2022-08-29T22:51:34: 	handler_wasserzaehler - Start
2022-08-29T22:51:34: 	handler_wasserzaehler - Start
2022-08-29T22:51:34: 	handler_wasserzaehler - Start
2022-08-29T22:51:34: 	handler_wasserzaehler - Start
2022-08-29T22:51:34: 	handler_prevalue - Start
2022-08-29T22:51:34: 	handler_prevalue - Start
2022-08-29T22:51:34: info_get_handler
2022-08-29T22:51:36: 	handler_prevalue - Start
2022-08-29T22:51:36: 	handler_prevalue - Start
2022-08-29T22:51:38: download_get_handler
2022-08-29T22:51:40: download_get_handler

**Comment by Varkzor** [comment] 2022-08-29 21:23
Device doesn't seem to trigger the MQTT part, although it's activated in the config.
Nothing received on the MQTT side either.

[MQTT]
Uri = mqtt://core-mosquitto:1883
MainTopic = watermeter
ClientID = water
user = ******
password = ******
SetRetainFlag = true

**Comment by Varkzor** [comment] 2022-08-29 21:53
maybe it won't work because i never seem to get a "value"?
The raw readings are excellent for what i need though:
![image](https://user-images.githubusercontent.com/50747528/187305752-1814e077-9006-494b-b199-29bdd97013f2.png)

**Comment by Matzebhv** [comment] 2022-08-30 07:28
The system sends mqtt messages at every intervall. Have you seen this issue? 
https://github.com/jomjol/AI-on-the-edge-device/issues/953

And, you have set your "MaxRateValue" and your "DecimalShift" wrong. The reading should be 1996.618

**Comment by Matzebhv** [comment] 2022-08-30 07:54
I see you have posted in the other issue also.
Uri = mqtt://core-mosquitto:1883 is wrong, you have to use the ip of your mosquitto instaed.

**Comment by Varkzor** [comment] 2022-08-30 10:56
Thanks for the info Matze, before i used the IP, didn't work either.

I will test the IP setup again.

**Comment by Matzebhv** [comment] 2022-08-30 11:21
I think the problem is at your mqtt backend. Perhaps you can try this tool to test your mqtt server -> http://mqtt-explorer.com/

To clarify @jomjol : does your software only log successfull mqtt transmissions? As in the provided log i can not even see the attempt to send any messages.

**Comment by jomjol** [comment] 2022-08-30 18:18
If the mqtt could not connect during startup, it will be deactivated and not try to send anything.

**Comment by Varkzor** [comment] 2022-08-30 20:03
Yeah it worked, i was unfortnately using a wrong IP address, now it's sending data.
It's not being received in the Home Assistant side, but i guess it has to do with the set-up configuration on that end for some reason..

I hope to figure it further out.
Big thanks again to everyone for helping to make this work.

Very interesting and useful project.

**Comment by jomjol** [comment] 2022-08-31 17:34
Then I close this issue!

**Closed by jomjol** 2022-08-31 17:34 UTC
