### ISSUE TITLE
Improve recognition for Gas meter

### ISSUE THREAD

**Issue by emmrichd** [jomjol/AI-on-the-edge-device#206] opened 2021-05-02 18:36 UTC
Hello,
thank you very much for this project and the article in the maker magazine!
I build a (hopefully) nice remix of your STL file for my gas meter, see thingiverse.
I still have an issue with the recognition - it is not as good as for my water meter.
[https://familie-emmrich.de/Gas.PNG](url)
Is there room to improve my configuration? 
Regards, Dieter

**Comment by jomjol** [comment] 2021-05-03 05:43
Hello Dieter,
the problem is, that in the case of your gas meter the numbers are not fully in the middle of the windows and partially covered (see especially the "9" and the "0"). Especially the "0" with the missing botton can easily be interpreted as a line and therefore very similar to a "1".
If you collect examples of your numbers (0 .. 9, red/black, 2 images each), I could do a specially trained network for you. The effort is not too big.
Best regards,
  jomjol

**Comment by emmrichd** [comment] 2021-05-03 06:35
Hello,

thank you for the quick reply. Is there a feature to collect these pictures? I have a 16GB SD Card, so space would be plenty.
This would be better than "number hunting".
Regards, Dieter

**Comment by jomjol** [comment] 2021-05-03 17:17
You can turn on the logging in the config file and then you will find in the directory `/log/digit` the cut out image of the digits. There you can select the represenative ones

**Comment by emmrichd** [comment] 2021-05-04 06:00
Hello,
yes, thanks,  I started the data collection. 
NB: with the latest firmware (6.7.1), the recognition seems to have improved. The html file does not seem to indicate the right version number in the information.

**Comment by jomjol** [comment] 2021-05-04 17:05
The html version might be different to the main version, as they are not always chaning in parallel.
I close this issue, until you have collected the numbers. Please feel free to reopen.

**Closed by jomjol** 2021-05-04 17:05 UTC

**Comment by emmrichd** [comment] 2021-05-07 06:02
How would you like the data, to train it automatically (Format/Naming)
Please note, that the names are sometimes wrong, because the recognition was wrong.
(Like filename "8" but numer "3")

**Comment by jomjol** [comment] 2021-05-07 15:36
I would need 2-3 typical pictures of each digit. The naming does not matter. Just put them in different folders (0, 1, 2, ... 9, NaN) in which they correctly belong.
