### ISSUE TITLE
Failed to read existing file

### ISSUE THREAD

**Issue by haverland** [jomjol/AI-on-the-edge-device#1424] opened 2022-11-28 21:18 UTC
### The Problem

After Update to 13.0.1 the URL http://watermeter1/index.html# is not working any more. 

It shows "Failed to read existing file" instead of picture of the meter.

Klick on "Overview" is a workaround.

### Version

13.0.1

### Logfile

```shell
no logging
```

### Screenshots

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/412645/204382602-e5ca7a8c-971e-4e77-ac13-c1e67545e124.png">

**Comment by Crajs20** [comment] 2022-11-28 22:13
Have the same issue when I try to set the actual value.
It written als current value.

**Comment by caco3** [comment] 2022-11-29 07:27
That might be a refreshing issue of the web browser.
But also after startup the device sometimes fails to serve all REST calls.

A refresh of the page usually solves it.

**Comment by maurcabezas** [comment] 2022-11-29 11:30
I have the same issue. but I still have version 12.0.1.. should I update the version to 13.0.1?

**Comment by PetrMa** [comment] 2022-12-01 07:28
The same issue after update from 12.0.1.to 13.0.1

**Comment by caco3** [comment] 2022-12-01 07:30
also after a page refresh?

**Comment by PetrMa** [comment] 2022-12-01 07:33
Refresh does not help. Only click to Owerview helps me. All refresh methods ends with the error message.
I have the same issue as @haverland

**Comment by caco3** [comment] 2022-12-01 07:36
does a force refresh help?
see https://fabricdigital.co.nz/assets/How-to-hard-refresh-browser-infographic.jpg

**Comment by PetrMa** [comment] 2022-12-01 07:51
No, this does not help, but I made some tests and it seems it is a specific issue depends on browser.
tested on:
Edge on Windows - OK
Chrome on Android - OK
Chrome on Windows 108.0.5359.72 - same issue until I delete all cookies. Then the page works fine for first load but next refresh is with error because all cookies are back. It is interesting that Owerview click work fine every time but refresh or first access not.

**Comment by Sandworm-of-Dune** [comment] 2022-12-01 19:21
Hi,
I have the same issue on one of my three devices. I’am on all devices on version 12.0.1
Perhaps the workaround is also working on 13.0.1

I found out that if this message appears the files on the SDcard are really missing. So the message is correct 😉
Workaround: I “solved” it on version 12.0.1 with the command:  [http://<IP>/ota?task=update&file=html.zip](http://%3cIP%3e/ota?task=update&file=html.zip). So the files are written again.
Then it works but after about 5 to 10 reboots it happens again. So I have to run the command again.
It seems something is deleting the content of the html folder from time to time.

**Comment by caco3** [comment] 2022-12-01 22:14
> I found out that if this message appears the files on the SDcard are really missing. 

Are you really sure about this, did you check with the build in file manager and also with the SD-Card in a PC?

> It seems something is deleting the content of the html folder from time to time.

That would be really bad and I do not see why that (sporadically) should happen!

**Comment by Sandworm-of-Dune** [comment] 2022-12-01 22:22
I checked it with the internal filemanager. 
The folder \html\ was empty. All other folders had still files included.
Yes, I also find this behaviour strange.

**Comment by caco3** [comment] 2022-12-01 22:25
> Chrome on Windows 108.0.5359.72

Thanks for trying to trace it down!

First of all, we renamed the overview page, maybe the old link is still in a cache. But its odd that you can reproduce it.
I tested it with Chrome on Windows (107.0.5304.123) in normal as well as Incognito Mode. Also I tested it with Chrome on Linux, but none of them showed an error!

Could you open the developer tools and provide screenshots from the Console and Network after you had the issue?
![grafik](https://user-images.githubusercontent.com/1783586/205171918-b42b2a43-a6f9-4f35-8d03-a7ccd22db735.png)

To open the developer tools see https://balsamiq.com/support/faqs/browserconsole/

**Comment by caco3** [comment] 2022-12-01 22:27
> The folder \html\ was empty. All other folders had still files included.

That looks like if some OTA process got started. That deletes all files in that folder first and then creates the new ones.

Can you enable the debug logging and provide logs when it happens again?

**Comment by PetrMa** [comment] 2022-12-02 19:38
Hi @caco3 

I tried to use developer tools and I´ve got error 500 when the error message displayed. It seems there is some issue with cookie.

Request URL: http://192.168.1.5/__utmc=90629594;%20__utmz=90629594.1669880781.1.1.utmcsr=(direct)%7Cutmccn=(direct)%7Cutmcmd=(none);%20__utma=90629594.1142900770.1669880781.1669880781.1670008166.2;%20__utmt=1;%20arp_scroll_position=54.400001525878906;%20__utmb=90629594.5.10.1670008166;%20overview.html
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 192.168.1.5:80
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 28
Content-Type: text/html
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: cs,en-US;q=0.9,en;q=0.8,cs-CZ;q=0.7
Connection: keep-alive
Cookie: __utmc=90629594; __utmz=90629594.1669880781.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=90629594.1142900770.1669880781.1669880781.1670008166.2; __utmt=1; arp_scroll_position=54.400001525878906; __utmb=90629594.5.10.1670008166; overview.html
DNT: 1
Host: 192.168.1.5
Referer: http://192.168.1.5/index.html
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

![image](https://user-images.githubusercontent.com/24729480/205371903-e59cb158-d277-47cc-93e4-93d56cb9aa05.png)

When I click to Overview button, I´ve got this result ..... there are no cookie records if I good understand the result

![image](https://user-images.githubusercontent.com/24729480/205372771-f39676ed-fc20-498b-b7ce-bc145ba0b9cc.png)

**Comment by caco3** [comment] 2022-12-02 19:55
That URL call to the cookie is somehow triggered by your browser, it clearly is not from the device's UI!
See https://cookiedatabase.org/cookie/google-analytics/__utmc/ for details about this cookie

Here my list if I call it from Firefox:
![grafik](https://user-images.githubusercontent.com/1783586/205374710-6658a290-3682-4d09-8f0f-94a2de11c537.png)

Also on Chrome I do not see such an URL call.

When I call the google cookie on my device I also get an error 500, maybe the device can not cope with such long URLs.

**Comment by PetrMa** [comment] 2022-12-03 11:26
H @caco3,

I found the issue. The problem depends on this specific extension https://chrome.google.com/webstore/detail/auto-refresh-plus-page-mo/hgeljhfekpckiiplhkigfehkdpldcggm

The extension creates the cookies mentioned above. If I disable the extension and delete all jomjol site cookies, everything works fine on next refresh.

There are two questions:
1) whats changed in version 13.x.x ? On v12.x.x there was no issue
2) why there is no issue when I click to Overview link, only on site refresh.

**Comment by caco3** [comment] 2022-12-03 11:34
Thats great.
Form device side it should be ok to have that cookie call, it will just return error 500.

1. See change logs on https://github.com/jomjol/AI-on-the-edge-device/releases There are quite some changes from 12 to 13.
2. When you click, it just loads the new html page. when you refresh it loads everything again. Just have a look with the dev tools

**Comment by caco3** [comment] 2022-12-03 11:35
closing as it is not a firmware issue

**Closed by caco3** 2022-12-03 11:35 UTC
Labels: bug

**Comment by PetrMa** [comment] 2022-12-03 11:39
Hi @caco3 

this does not answer my question why there is this issue in v 13 and not in v12. The extension does not changed, I´am using this extension few years so something was changed on jomjol firmware.
Sure, I understand that this is specific issue but it was changed on your side, not on my side.

Is there any way how can I fix it? I mean something other than disable this extension!

**Comment by caco3** [comment] 2022-12-03 11:47
I do not know what should have got broken!

I just installed that extension in my chrome and activated it to reload every 5s, but I do not such a cookie call, what else would I have to to to reproduce it?

BTW, since you auto reload it to see the current information:
- Use http://192.168.1.151/overview.html instead if you don't need the menu
- This buts quite some load onto the device and could cause unwanted restarts!

**Comment by PetrMa** [comment] 2022-12-03 11:54
Hmmm, 

it is very interesting. I tried to reset the extension settings and now the cookies is not created on jomjol site anymore.
So it seems the problem is solved on my side. Hope this help other users with the similar issue.

Thanks. Have a nice weekend.

**Comment by parhedberg** [comment] 2022-12-05 11:49
I have same issue and do not have that chrome extension.. (i have actually tested and have the same results both in firefox and edge)

**Comment by parhedberg** [comment] 2022-12-05 11:52
Sorry, i have to strike that. Only Chrome (my go to browser) has this issue.. It can be related to something being cached from previous visits..

**Comment by parhedberg** [comment] 2022-12-05 11:53
Chrome in inkognito mode does not have this issue.. So it is definitely something with cached data..

**Comment by PetrMa** [comment] 2022-12-05 11:53
Check the site cookies and delete them.

**Comment by parhedberg** [comment] 2022-12-05 11:57
Yes! Found a cookie with the name "_delighted_web=" (that the page tried to access).. 
(have no idea where that came from)

When i deleted it, the page loaded correctly...

**Comment by PetrMa** [comment] 2022-12-05 11:59
OK, back to the add-ons. I tried to enable-disable on-by-one and everytime I check the cookies. 
But again ..... it is very interesting, that this issues comes with version 13.x.x.

**Comment by parhedberg** [comment] 2022-12-05 12:00
The cookie I got seems to be set by UniFi routers.. and it is nothing new with that.. So something has changed in the application that makes the cookie part of the requested URL

**Comment by PetrMa** [comment] 2022-12-05 12:03
Yes, I agree that something changed in jomjol application.

**Comment by caco3** [comment] 2022-12-05 12:13
> Yes, I agree that something changed in jomjol application.

The failed loading indeed is something we have to investigate in https://github.com/jomjol/AI-on-the-edge-device/issues/1425

And the 500 instead of the 404 also.

But it is not in our hands what the webbrowser wants to send (and maybe overload) the webserver on the device!

**Comment by caco3** [comment] 2022-12-05 20:55
Yes, beginning with 13.0.1 I added a cookie to store the selected page so it does not always go to the overview on a page reload (https://github.com/jomjol/AI-on-the-edge-device/pull/1406).

@parhedberg Thank you for improving the cookie usage, I did not really think that I could use it wrong :)

**Comment by PetrMa** [comment] 2022-12-08 08:09
@caco3 It seems the issue was fixed in 13.0.5, right?

**Comment by caco3** [comment] 2022-12-08 16:10
> @caco3 It seems the issue was fixed in 13.0.5, right?

yes, we hope so
