### ISSUE TITLE
How to deal with leading digit not displayed

### ISSUE THREAD

**Issue by liflitz** [jomjol/AI-on-the-edge-device#1007] opened 2022-09-12 06:20 UTC
Hi jomjol,

In one of my two devices I am reading digitally displayed temperatures. How do I deal with single digit temperatures not showing a first (from the left) digit at all? Tonight I got consistently the reading "7" on the totally empty field. 

Thanks for your help and best wishes,

liflitz

**Comment by stefanbode** [comment] 2022-09-12 15:31
Please try to use the following tensor class: dig-class11_1411_s2_q.tflite

**Comment by liflitz** [comment] 2022-09-12 16:36
This is the one I have been using already.

**Comment by stefanbode** [comment] 2022-09-12 18:38
Can you post your config.ini without the WLAN password please. Want to see the other settings. Normally it should recognize NaN. Also debug log and the log from reading is helpful to find the root cause.

**Comment by liflitz** [comment] 2022-09-12 20:02
Hiere my settings. Note that last night I still had main.IgnoreLeadingNaN = false and next I will test it with true. However, as you can see from the log, some blank fields were assigned 10;

![image](https://user-images.githubusercontent.com/84687915/189743625-9dc53702-03f5-4ece-89ef-54d3fa98fdec.png)

and others to 7:

![image](https://user-images.githubusercontent.com/84687915/189743677-90e1bc43-5189-4a97-aa39-a47a3a643442.png)

I don't understand how a blank image can result in 7. Will training the blank image as 0 help?

[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
LogfileRetentionInDays = 7
Brightness = 0
Contrast = 0
Saturation = -1
LEDIntensity = 5
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 349
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 336 149
/config/ref1.jpg 180 172

[Digits]
Model = /config/dig-class11_1411_s2_q.tflite
LogImageLocation = /log/digit
LogfileRetentionInDays = 7
ModelInputSize = 20 32
main.dig1 367 198 45 75
main.dig2 408 198 45 75
main.dig3 448 198 45 75

;[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32

[PostProcessing]
main.DecimalShift = -1
PreValueUse = false
PreValueAgeStartup = 720
AllowNegativeRates = true
;main.MaxRateValue = 
main.MaxRateType = AbsoluteChange
main.ExtendedResolution = false
main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
<deleted>

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 5

[Debug]
Logfile = true
LogfileRetentionInDays = 7

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeServer = 216.239.35.0
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false


2 relevant rounds from the message directory:

2022-09-12T06:07:03: task_autodoFlow - next round - Round #925
2022-09-12T06:07:03: 	FlowControll.doFlow - ClassFlowMakeImage
2022-09-12T06:07:13: 	FlowControll.doFlow - ClassFlowAlignment
2022-09-12T06:07:44: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-09-12T06:07:49: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-09-12T06:07:49: PostProcessing - Raw: 79.7 Value: 79.7 Error: no error
2022-09-12T06:07:49: 	FlowControll.doFlow - ClassFlowMQTT
2022-09-12T06:07:49: sent publish successful in MQTTPublish, msg_id=11255, solarthermieregler/connection, connected
2022-09-12T06:07:49: sent publish successful in MQTTPublish, msg_id=27872, solarthermieregler/uptime, 1662955644
2022-09-12T06:07:49: sent publish successful in MQTTPublish, msg_id=18975, solarthermieregler/freeMem, 3156747
2022-09-12T06:07:49: sent publish successful in MQTTPublish, msg_id=59275, solarthermieregler/wifiRSSI, -65
2022-09-12T06:07:50: sent publish successful in MQTTPublish, msg_id=16127, solarthermieregler/main/value, 79.7
2022-09-12T06:07:50: sent publish successful in MQTTPublish, msg_id=54960, solarthermieregler/main/error, no error
2022-09-12T06:07:50: sent publish successful in MQTTPublish, msg_id=17508, solarthermieregler/main/rate, -0.010001
2022-09-12T06:07:50: sent publish successful in MQTTPublish, msg_id=53576, solarthermieregler/main/raw, 79.7
2022-09-12T06:07:50: sent publish successful in MQTTPublish, msg_id=51047, solarthermieregler/main/timestamp, 2022-09-12T06:07:11
2022-09-12T06:07:50: sent publish successful in MQTTPublish, msg_id=6543, solarthermieregler/main/json, {"value":79.7,"raw":"79.7","error":"no error","rate":-0.010001,"timestamp":"2022-09-12T06:07:11"}
2022-09-12T06:07:50: task_autodoFlow - round done
2022-09-12T06:07:50: CPU Temperature: 35.6
2022-09-12T06:12:03: task_autodoFlow - next round - Round #926
2022-09-12T06:12:03: 	FlowControll.doFlow - ClassFlowMakeImage
2022-09-12T06:12:13: 	FlowControll.doFlow - ClassFlowAlignment
2022-09-12T06:12:44: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-09-12T06:12:49: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-09-12T06:12:49: 	FlowControll.doFlow - ClassFlowMQTT
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=59244, solarthermieregler/connection, connected
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=64762, solarthermieregler/uptime, 1662955944
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=35874, solarthermieregler/freeMem, 3156751
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=25940, solarthermieregler/wifiRSSI, -67
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=9700, solarthermieregler/main/value, N9.7
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=17964, solarthermieregler/main/raw, N9.7
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=57835, solarthermieregler/main/timestamp, 2022-09-12T06:07:11
2022-09-12T06:12:49: sent publish successful in MQTTPublish, msg_id=36414, solarthermieregler/main/json, {"value":N9.7,"raw":"N9.7","error":"","rate":"","timestamp":"2022-09-12T06:07:11"}
2022-09-12T06:12:49: task_autodoFlow - round done
2022-09-12T06:12:49: CPU Temperature: 35.0

Where do I find the 2 log files you mentioned? The Log Viewer seems to show the same.

Thanks for your help!!!

**Comment by liflitz** [comment] 2022-09-12 20:06
Somewhat related question: once temperature will drop below 0, does your system allow recognition of "-" for negative values?

**Comment by jomjol** [comment] 2022-09-12 20:45
1) I cannot train the blank digit as a zero, because then other reading will fail. 
2) a "-" will not be recognized at all, bcause it is not part of the training

I looks like your system would need special adoptions within the internal logic.

**Comment by liflitz** [comment] 2022-09-13 17:09
I was afraid this would be the answer - thanks a lot for all your effort and support!!

**Comment by jomjol** [comment] 2022-09-13 18:13
Okay - sorry for this, but then I close the issue, you can still post and I will respond

**Closed by jomjol** 2022-09-13 18:13 UTC
