### ISSUE TITLE
[CAM] is not working anymore (CaptureToBasisImage) 

### ISSUE THREAD

**Issue by backupandforkacc** [jomjol/AI-on-the-edge-device#2417] opened 2023-05-18 18:19 UTC
### The Problem

I keep getting the error:
`<ERR>	[CAM] is not working anymore (CaptureToBasisImage) - most probably caused by a hardware problem (instablility, ...). System will reboot.`

I can take and set the reference image without any problem. I also flashed another software to get a video with the ESP32-cam, which also worked. And yet I get this error.

What happens:
1. I flash the ESP32-cam
2. I write the content of the SD card folder to the SD card
3. adapt the wifi settings
4. Set the reference image, alignement and up to digital ROI. I have not analog ROI. 
5. The ESP-32 keeps starting over with the error. The webserver serves me the configuration menu again and again. 

What I tried:
* I have reformatted the SD card, used another SD card, flashed the ESP32 again. Still the same problem.

### Version

15.2.4

### Logfile

```shell
I (14520) WIFI: Connected to: FritzBox7412, RSSI: -59
I (14530) wifi:<ba-add>idx:0 (ifx:0, 44:4e:6d:75:2f:75), tid:6, ssn:2, winSize:64
I (14550) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (15520) esp_netif_handlers: sta ip: 192.168.103.59, mask: 255.255.255.0, gw: 192.168.103.1
I (15520) WIFI: Assigned IP: 192.168.103.59
I (15880) wifi:<ba-add>idx:1 (ifx:0, 44:4e:6d:75:2f:75), tid:0, ssn:0, winSize:64
I (15980) SNTP: Time is synced with NTP Server pool.ntp.org: 2023-05-18 20:19:56
I (17350) MAIN: Device info: CPU cores: 2, Chip revision: 100
I (17360) MAIN: SD card info: Name: SD08G, Capacity: 7456MB, Free: 7431MB
I (19370) MAIN SERVER: Starting server on port: '80'
I (19370) MAIN SERVER: Registering URI handlers
I (19370) MAINCTRL: server_main_flow_task - Registering URI handlers
I (19370) OTA: Registering URI handlers
I (19370) GPIO: start GpioHandler
I (19380) GPIO: register GPIO Uri
I (19380) GPIO: server_GPIO - Registering URI handlers
W (19390) MAIN: Initialization completed with non-critical errors!
I (19420) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8
I (21700) LOGFILE: Set log level to ERROR
I (21720) GPIO: read GPIO config and init GPIO
I (21730) GPIO: GPIO init completed, handler is disabled
I (21740) MQTT IF: Init
I (21750) MQTT IF: Client started, waiting for established connection...
I (21750) MAINCTRL: We are in Setup Mode -> Not starting Auto Flow!
I (21790) MQTT IF: Connected to broker
W (32320) cam_hal: Failed to get the frame on time!
W (36320) cam_hal: Failed to get the frame on time!
E (36320) CAM: is not working anymore (CaptureToBasisImage) - most probably caused by a hardware problem (instablility, ...). System will reboot.
I (36330) OTA: Reboot triggered by Software (5s)
W (36330) OTA: Reboot in 5sec
I (39350) mqtt_client: Client asked to disconnect
W (39360) mqtt_client: Client asked to stop, but was not started

```

### Expected Behavior

Should give me the number on the watermeter

### Screenshots

not applicable

### Additional Context

none

**Comment by A380Coding** [comment] 2023-05-19 20:00
I get the same issue on one of my device. I happened to find out that a manual reboot helps for some time.

`[0d00h00m49s] 2023-05-19T21:51:40 <ERR> [CAM] is not working anymore (CaptureToBasisImage) - most probably caused by a hardware problem (instablility, ...). System will reboot.
[0d00h00m00s] 2023-05-19T19:51:48 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-19T19:51:48 <INF> [MAIN] ==================== Start ======================
[0d00h00m00s] 2023-05-19T19:51:48 <INF> [MAIN] =================================================
[0d00h00m00s] 2023-05-19T19:51:48 <INF> [MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m00s] 2023-05-19T19:51:48 <INF> [MAIN] Total heap: 4377083 byte
[0d00h00m08s] 2023-05-19T19:51:56 <ERR> [MAIN] Camera framebuffer check failed
[0d00h00m08s] 2023-05-19T19:51:56 <ERR> [HELPER] New System Status: 0x00000100`

**Comment by jomjol** [comment] 2023-05-20 07:06
Pretty sure, that this is a hardware problem. The ESP32CAM module seems to be very sensitive. I already had devices, that did frequently a reboot, with one and the same firmware and setting, than another running for day without any issues. 
Or a camera module, that was working on one module, but not on another.
Sometimes it helps to check for the interconnections, but not always.

I will close this issue, as it is a very individual problem, not related to the firmware.

**Closed by jomjol** 2023-05-20 07:06 UTC
Labels: bug
