### ISSUE TITLE
No image on html

### ISSUE THREAD

**Issue by Alex-Smart** [jomjol/AI-on-the-edge-device#796] opened 2022-05-04 09:48 UTC
Things seemed fine at first - but there is no image on html, and plenty of errors showed up in html debugger when I pressed buttons
![изображение](https://user-images.githubusercontent.com/27426226/166659291-74d2f58f-85a8-4b14-aea3-64f1287cdea4.png)

**Comment by Alex-Smart** [comment] 2022-05-04 11:42
Here is terminal output
![изображение](https://user-images.githubusercontent.com/27426226/166674614-e642e7ca-95ef-4861-bc73-0570490ed3d4.png)

**Comment by jomjol** [comment] 2022-05-04 18:04
What brower are you using?
It has only been tested with Firefox, might also work with Chrome.

**Comment by Alex-Smart** [comment] 2022-05-05 07:07
Tried Firefox, Chrome and even Internet explorer. Looks terrible in Chrome but still same on the image part. No image...

**Comment by Alex-Smart** [comment] 2022-05-05 14:53
log file /log/message/.. seems to small:
```
2022-05-05T16:21:02: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-05-05T16:21:02: =============================================================================================
2022-05-05T16:21:02: =================================== Main Started ============================================
2022-05-05T16:21:02: =============================================================================================
2022-05-05T16:21:06: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
```
even though 
Logfile = true 
is set in config.ini

**Comment by jomjol** [comment] 2022-05-05 16:46
That looks like a very early frequent reboot. You need to check the serial log of the debugger interface to find the point, where it reboots.

**Comment by Alex-Smart** [comment] 2022-05-05 18:44
Looks pretty normal to me...
`
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6604
ho 0 tail 12 room 4
load:0x40078000,len:14780
load:0x40080400,len:3792
entry 0x40080694
I (28) boot: ESP-IDF v4.4 2nd stage bootloader
I (28) boot: compile time 14:34:51
I (28) boot: chip revision: 1
I (31) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (38) boot.esp32: SPI Speed      : 40MHz
I (43) boot.esp32: SPI Mode       : DIO
I (47) boot.esp32: SPI Flash Size : 4MB
I (52) boot: Enabling RNG early entropy source...
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (83) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (90) boot:  3 ota_0            OTA app          00 10 00010000 001db000
I (98) boot:  4 ota_1            OTA app          00 11 001f0000 001db000
I (105) boot: End of partition table
I (110) boot_comm: chip revision: 1, min. application chip revision: 0
I (117) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=5070ch (329484)
 map
I (245) esp_image: segment 1: paddr=00060734 vaddr=3ffb0000 size=0503ch ( 20540)
 load
I (253) esp_image: segment 2: paddr=00065778 vaddr=40080000 size=0a8a0h ( 43168)
 load
I (271) esp_image: segment 3: paddr=00070020 vaddr=400d0020 size=149ad4h (135035
6) map
I (760) esp_image: segment 4: paddr=001b9afc vaddr=4008a8a0 size=109bch ( 68028)
 load
I (788) esp_image: segment 5: paddr=001ca4c0 vaddr=50000000 size=00010h (    16)
 load
I (802) boot: Loaded app from partition at offset 0x10000
I (802) boot: Disabling RNG early entropy source...
I (814) psram: This chip is ESP32-D0WD
I (814) spiram: Found 64MBit SPI RAM device
I (814) spiram: SPI RAM mode: flash 40m sram 40m
I (819) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (826) cpu_start: Pro cpu up.
I (830) cpu_start: Starting app cpu, entry point is 0x4008176c
I (0) cpu_start: App cpu up.
I (1724) spiram: SPI SRAM memory test OK
I (1732) cpu_start: Pro cpu start user code
I (1732) cpu_start: cpu freq: 240000000
I (1732) cpu_start: Application information:
I (1735) cpu_start: Project name:     esp32cam-server-only
I (1741) cpu_start: App version:      0.0.9.3
I (1746) cpu_start: Compile time:     May  4 2022 14:34:30
I (1752) cpu_start: ELF file SHA256:  e35b25522a4c2a91...
I (1759) cpu_start: ESP-IDF:          v4.4
I (1764) heap_init: Initializing. RAM available for dynamic allocation:
I (1771) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1777) heap_init: At 3FFC0BE8 len 0001F418 (125 KiB): DRAM
I (1783) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1790) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1796) heap_init: At 4009B25C len 00004DA4 (19 KiB): IRAM
I (1803) spiram: Adding pool of 4095K of external SPI memory to heap allocator
I (1811) spi_flash: detected chip: generic
I (1815) spi_flash: flash io: dio
I (1824) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1830) spiram: Reserving pool of 32K of internal memory for DMA/internal alloc
ations
I (1840) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulld
own: 0| Intr:0
Init Camera
I (3850) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulld
own: 0| Intr:2
I (3850) cam_hal: cam init ok
I (3850) sccb: pin_sda 26 pin_scl 27
I (3850) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulld
own: 0| Intr:0
I (3890) camera: Detected camera at address=0x30
I (3890) camera: Detected OV2640 camera
I (3890) camera: Camera PID=0x26 VER=0x42 MIDL=0x7f MIDH=0xa2
I (3960) cam_hal: buffer_size: 32768, half_buffer_size: 4096, node_buffer_size:
2048, node_cnt: 16, total_cnt: 15
I (3960) cam_hal: Allocating 61440 Byte frame buffer in PSRAM
I (3970) cam_hal: cam config ok
I (3970) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8
Internal Flash-LED turn off PWM
nach init camera: sleep for : 200ms
I (6060) main: Using SDMMC peripheral
Name: 00000
Type: SDSC
Speed: 20 MHz
Size: 1876MB
I (6100) server_ota: Start CheckOTAUpdateCheck ...
Start CheckOTAUpdateCheck ...
I (6110) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3
dd3ac3462e1e73286bcd31b689060c91de06fa3a
I (6110) server_ota: SHA-256 for bootloader: : 5bafba9f777a7a55790400cfba7c0f50b
6ca804e95d796ad065ae1296f222b99
I (6120) server_ota: SHA-256 for current firmware: : 3d25bb2a0adc4dc98e300fdd4ee
706eccc67597ebd19233a8a72f6b6e1d1dc4a
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: *********, *********
Hostename: gasmeter
I (6180) wifi:wifi driver task: 3ffdacf0, prio:23, stack:6656, core=0
I (6180) system_api: Base MAC address is not set
I (6180) system_api: read default base MAC address from EFUSE
I (6200) wifi:wifi firmware version: 7679c42
I (6200) wifi:wifi certification version: v7.0
I (6200) wifi:config NVS flash: enabled
I (6200) wifi:config nano formating: disabled
I (6200) wifi:Init data frame dynamic rx buffer num: 16
I (6210) wifi:Init management frame dynamic rx buffer num: 16
I (6210) wifi:Init management short buffer num: 32
I (6220) wifi:Init static tx buffer num: 8
I (6220) wifi:Init tx cache buffer num: 16
I (6230) wifi:Init static rx buffer size: 1600
I (6230) wifi:Init static rx buffer num: 10
I (6230) wifi:Init dynamic rx buffer num: 16
I (6240) wifi_init: rx ba win: 6
I (6240) wifi_init: tcpip mbox: 32
I (6250) wifi_init: udp mbox: 6
I (6250) wifi_init: tcp mbox: 6
I (6250) wifi_init: tcp tx win: 5744
I (6260) wifi_init: tcp rx win: 5744
I (6260) wifi_init: tcp mss: 1440
I (6270) wifi_init: WiFi/LWIP prefer SPIRAM
I (6270) wifi_init: WiFi IRAM OP enabled
I (6270) wifi_init: WiFi RX IRAM OP enabled
I (6280) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (6370) wifi:mode : sta (e8:68:e7:26:f2:40)
I (6370) wifi:enable tsf
I (6380) BLINK: Blinken - start
E (6380) wifi station: Set Hostname to:gasmeter
I (6380) wifi station: wifi_init_sta finished.
I (6390) wifi:new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
I (6390) wifi:state: init -> auth (b0)
I (6410) wifi:state: auth -> assoc (0)
I (6420) wifi:state: assoc -> run (10)
I (6460) wifi:connected with HomeNetwork, aid = 6, channel 6, BW20, bssid = 74:8
3:c2:c4:7f:36
I (6460) wifi:security: WPA2-PSK, phy: bgn, rssi: -77
I (6460) wifi:pm start, type: 1

W (6480) wifi:<ba-add>idx:0 (ifx:0, 74:83:c2:c4:7f:36), tid:0, ssn:0, winSize:64

I (6530) wifi:AP's beacon interval = 102400 us, DTIM period = 3
I (6580) BLINK: Blinken - done
I (8670) esp_netif_handlers: sta ip: 192.168.198.73, mask: 255.255.255.0, gw: 19
2.168.198.1
I (8670) wifi station: got ip:192.168.198.73
I (8670) BLINK: Blinken - start
I (8670) wifi station: connected to ap SSID:********* password:*********
main: sleep for : 200ms
I (10680) sntp: Time is not set yet. Connecting to WiFi and getting time over NT
P.
I (10680) sntp: Initializing SNTP
I (10680) sntp: Waiting for system time to be set... (1/10)
W (11900) wifi:<ba-add>idx:1 (ifx:0, 74:83:c2:c4:7f:36), tid:6, ssn:2, winSize:6
4
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
Logfile opened: /sdcard/log/message/log_2022-05-05.txt
I (12690) sntp: The current date/time in Berlin is: Thu May  5 20:41:21 2022
I (12690) sntp: The current date/time in Berlin is: 2022-05-05_20:41
timeist 20220505-204121
Logfile opened: /sdcard/log/message/log_2022-05-05.txt
Logfile opened: /sdcard/log/message/log_2022-05-05.txt
Logfile opened: /sdcard/log/message/log_2022-05-05.txt
time 20220505-204121
Internal Flash-LED turn off PWM
main: sleep for : 2000ms
starting server
I (14720) server-main: Starting server on port: '80'
I (14720) server-main: Registering URI handlers
I (14720) server_tflite: server_part_camera - Registering URI handlers
I (14720) server_ota: server_ota - Registering URI handlers
I (14730) server_GPIO: start GpioHandler
I (14730) server_GPIO: register GPIO Uri
I (14740) server_GPIO: server_GPIO - Registering URI handlers
vor reg server main
vor dotautostart
task_autodoFlow configMINIMAL_STACK_SIZE: 768
getESPHeapInfo:  Heap: 4163554 Min Free: 4161926 larg. Block:  4063232 SPI Heap:
 4071347 NOT_SPI Heap: 92207 Internal Heap: 92207 Internal Min Heap free: 91963
task_autodoFlow: start
getESPHeapInfo:  Heap: 4136330 Min Free: 4134446 larg. Block:  4063232 SPI Heap:
 4071347 NOT_SPI Heap: 64983 Internal Heap: 64983 Internal Min Heap free: 64483
Start tfliteflow.InitFlow(config);
open file /sdcard/config/config.ini in mode r
[MakeImage]
Start ReadParameter ([MakeImage]
)
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 50
Set led_intensity to 4095 of 8191
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
I (14830) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8
Start ReadParameter ([Alignment])
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
Start ReadParameter ([Digits])
Model = /config/dig-s2-q-20220211.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
GetGENERAL - GENERAL main - roi dig1
main.dig2 343 126 30 54
GetGENERAL - GENERAL main - roi dig2
main.dig3 391 126 30 54
GetGENERAL - GENERAL main - roi dig3

[Analog]
Start ReadParameter ([Analog])
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
GetGENERAL - GENERAL main - roi ana1
main.ana2 379 332 92 92
GetGENERAL - GENERAL main - roi ana2
main.ana3 283 374 92 92
GetGENERAL - GENERAL main - roi ana3
main.ana4 155 328 92 92
GetGENERAL - GENERAL main - roi ana4

[PostProcessing]
Start ReadParameter ([PostProcessing])
Anzahl NUMBERS: 1 - DIGITS: 1, ANALOG: 1
Number main, Anz DIG: 3, Anz ANA 4
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
ErrorMessage = true
CheckDigitIncreaseConsistency = false

;[MQTT]
Read Zeile Prevalue.ini: main   1918-11-04T00:05:36     42.0134
Read: ;Uri = mqtt://IP-ADRESS:1883
Read: ;MainTopic = wasserzaehler
Read: ;ClientID = wasser
Read: ;user = USERNAME
Read: ;password = PASSWORD
Read:
Read: ;[GPIO]
Read: ;MainTopicMQTT = wasserzaehler/GPIO
Read: ;IO0 = input disabled 10 false false
Read: ;IO1 = input disabled 10 false false
Read: ;IO3 = input disabled 10 false false
Read: ;IO4 = built-in-led disabled 10 false false
Read: ;IO12 = input-pullup disabled 10 false false
Read: ;IO13 = input-pullup disabled 10 false false
Read: LEDType = WS2812
Read: LEDNumbers = 2
Read: LEDColor = 150 150 150
Read:
Read: [AutoTimer]
Start ReadParameter ([AutoTimer]
)
AutoStart = true
Intervall = 4.85

[Debug]
Start ReadParameter ([Debug])
Logfile = true
LogfileRetentionInDays = 3

[System]
Start ReadParameter ([System])
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
Logfile opened: /sdcard/log/message/log_2022-05-05.txt
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
END OF FILE
Finished tfliteflow.InitFlow(config);
*************** Start GPIOHandler_Init *****************
I (16550) server_GPIO: read GPIO config and init GPIO
open file /sdcard/config/config.ini in mode r
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 50
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
Model = /config/dig-s2-q-20220211.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
main.dig2 343 126 30 54
main.dig3 391 126 30 54

[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
ErrorMessage = true
CheckDigitIncreaseConsistency = false

;[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

;[GPIO]
;MainTopicMQTT = wasserzaehler/GPIO
;IO0 = input disabled 10 false false
;IO1 = input disabled 10 false false
;IO3 = input disabled 10 false false
;IO4 = built-in-led disabled 10 false false
;IO12 = input-pullup disabled 10 false false
;IO13 = input-pullup disabled 10 false false
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
I (16730) server_GPIO: GPIO init comleted, handler is disabled
Flashdauer: 5000
Internal Flash-LED turn on with PWM 4095
I (18670) BLINK: Blinken - done
Internal Flash-LED turn off PWM
Image loaded from memory: 640, 480, 3
uri: /
1 uri: /, filename: , filepath: /sdcard
System ist im Setupmodus --> index.html --> setup.htmlFilename:
File requested: /sdcard/html/setup.html
open file /sdcard/html/setup.html in mode r
I (60610) serverhelp: Sending file : /sdcard/html/setup.html ...
I (60620) serverhelp: File sending complete
uri: /edit_explain_0.html
1 uri: /edit_explain_0.html, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/edit_explain_0.html
open file /sdcard/html/edit_explain_0.html in mode r
I (62110) serverhelp: Sending file : /sdcard/html/edit_explain_0.html ...
I (62150) serverhelp: File sending complete
uri: /flow_overview.jpg
1 uri: /flow_overview.jpg, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/flow_overview.jpg
open file /sdcard/html/flow_overview.jpg in mode r
I (62200) serverhelp: Sending file : /sdcard/html/flow_overview.jpg ...
I (62460) serverhelp: File sending complete
uri: /cnn_images.jpg
1 uri: /cnn_images.jpg, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/cnn_images.jpg
open file /sdcard/html/cnn_images.jpg in mode r
I (62480) serverhelp: Sending file : /sdcard/html/cnn_images.jpg ...
I (62620) serverhelp: File sending complete
uri: /explain_1.html
1 uri: /explain_1.html, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/explain_1.html
open file /sdcard/html/explain_1.html in mode r
I (67960) serverhelp: Sending file : /sdcard/html/explain_1.html ...
I (67970) serverhelp: File sending complete
uri: /edit_reference.html
1 uri: /edit_reference.html, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/edit_reference.html
open file /sdcard/html/edit_reference.html in mode r
I (67990) serverhelp: Sending file : /sdcard/html/edit_reference.html ...
I (68120) serverhelp: File sending complete
uri: /gethost.js
1 uri: /gethost.js, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/gethost.js
open file /sdcard/html/gethost.js in mode r
I (68140) serverhelp: Sending file : /sdcard/html/gethost.js ...
I (68150) serverhelp: File sending complete
uri: /readconfigcommon.js
1 uri: /readconfigcommon.js, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/readconfigcommon.js
open file /sdcard/html/readconfigcommon.js in mode r
I (68180) serverhelp: Sending file : /sdcard/html/readconfigcommon.js ...
I (68210) serverhelp: File sending complete
uri: /readconfigparam.js
1 uri: /readconfigparam.js, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/readconfigparam.js
open file /sdcard/html/readconfigparam.js in mode r
I (68240) serverhelp: Sending file : /sdcard/html/readconfigparam.js ...
I (68390) serverhelp: File sending complete
`

**Comment by jomjol** [comment] 2022-05-07 08:28
Yes, looks pretty nornal. But up to this point no image has been taken, so maybe the camera is the problem. Can you make a serial of the booting up to the point where the image is taken (Flash LED is on and off), whithout html access during that time (maybe up to 30-40 seconds).

**Comment by Alex-Smart** [comment] 2022-05-07 08:40
well this is the log, from booting up to image taking point, then I tried to access module via html

isnt it this point?
```

Internal Flash-LED turn on with PWM 4095
I (18670) BLINK: Blinken - done
Internal Flash-LED turn off PWM
Image loaded from memory: 640, 480, 3
```

I tried simple streaming example from 
https://randomnerdtutorials.com/esp32-cam-video-streaming-web-server-camera-home-assistant/
and it works perfect, so I assume that hardware is ok

**Comment by jomjol** [comment] 2022-05-07 08:44
Well, than I have no further idea. At most of the others it works. There are some rare reports about blocking virus scanners for parts of the html page (there is js-code loaded). 

Anyway, if the camera is okay (you tested with other software), the system is booting up to the image taking (log files is showing this) and you still don't get an image on the html page, I have no idea, that I could test with remote debugging. :-(

**Comment by Alex-Smart** [comment] 2022-05-07 09:28
My guess that it is definetely html problem, as in my original post there is a plenty of errors when accessing html
![зображення](https://user-images.githubusercontent.com/27426226/167248136-9967ed39-304b-46f3-bdfd-68cc9addc081.png)
almost all functions are not defined (while they are obviuosly defined) error. Im not that good with html side, so have no idea how to debug this issue...

**Comment by kapet** [comment] 2022-05-07 09:46
Just a hunch: maybe the adblocker is interfering?

**Comment by jomjol** [comment] 2022-05-07 11:03
Same thought: or there is a javascript blocker? There are several js-functions inside the html as well as loaded from the server

**Comment by Alex-Smart** [comment] 2022-05-07 12:47
Thought of that, disabled everything, same result

**Comment by Alex-Smart** [comment] 2022-05-07 13:10
Interestingly, when I open edit_reference.html locally, all functions are seen as defined, I can step through with debugger, etc.

**Comment by Alex-Smart** [comment] 2022-05-07 13:27
and html loaded in a weird way from time to time, I got a warning in debugger, and here is what I saw in RAW view
![image](https://user-images.githubusercontent.com/27426226/167256361-38f91673-2fdd-4cc2-8ae3-ce8e85ca6789.png)

**Comment by s0170071** [comment] 2022-05-07 19:42
Try different SD card ...

**Comment by Giacomo72** [comment] 2022-05-07 20:55
Unsubscribe me

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alex-Smart** [comment] 2022-05-07 21:25
> Try different SD card ...

Just did, same result

**Comment by s0170071** [comment] 2022-05-08 10:11
I find it odd that there is "0" at the top and "2000" which is 200 Http OK and "0"

**Comment by Alex-Smart** [comment] 2022-05-08 10:25
it is very odd, because there should be no extra text in html above <!DOCTYPE html>, this extra text present in various forms after refresh. It seems that this is html transmit error from server to client - I see no other explanation

**Comment by pixeldoc2000** [comment] 2022-05-13 21:17
@Alex-Smart try to start Firefox in Safe Mode (hold Shift Key while starting Firefox) or try maybe test a portable Firefox Version with default Settings.

Are you using any form of Anti Virtus Software doing some sort of Webfiltering (Proxy) or VPN?

**Comment by Alex-Smart** [comment] 2022-05-13 22:18
> @Alex-Smart try to start Firefox in Safe Mode (hold Shift Key while starting Firefox) or try maybe test a portable Firefox Version with default Settings.
> 
> Are you using any form of Anti Virtus Software doing some sort of Webfiltering (Proxy) or VPN?

Firefox in safe mode - no changes, Antivirus - off, VPN - off

**Comment by pixeldoc2000** [comment] 2022-05-17 09:14
@Alex-Smart 
Did you test it with a browser on your smartphone?

**Comment by jomjol** [comment] 2022-05-20 15:10
Here only a manual debugging with the device on side can really help.

**Comment by Alex-Smart** [comment] 2022-05-22 06:39
Can you give me a hint on where to start on debugging this issue?

**Comment by jomjol** [comment] 2022-05-22 06:57
I assume, that 
1) the hardware has very rare defect ?
2) the problem is in the local network setup

In order to distinguish this, you would need to run the device at another user, that has a running module.

With all this discription, I really don't know how to help remote anymore. I'm really sorry for this.

**Comment by s0170071** [comment] 2022-05-22 07:04
You can set up a mobile hotspot with your mobile phone connect the espcam 
to it. Access it from your phone. If there error persists, it is in your 
espcam.


Am 22. Mai 2022 08:40:13 schrieb Alex ***@***.***>:

**Comment by Alex-Smart** [comment] 2022-05-22 13:22
> @Alex-Smart Did you test it with a browser on your smartphone / other Device?

Damn, its working. Ill keep digging to find out what is the reason it does not work on my PC

**Comment by jomjol** [comment] 2022-05-22 13:44
Then I will close this issue - but you still can post the reason, maybe it helps others.

**Closed by jomjol** 2022-05-22 13:44 UTC

**Comment by Alex-Smart** [comment] 2022-05-25 07:47
If somebody wonders, what the hell, it is the antivirus. Drweb in my case - it can not by turned off completely, disabling all its features does not work. Only adding web browser to exclusions worked.

**Comment by RangeOfGlitching** [comment] 2022-07-07 01:16
After disable AdBlocker I can use chrome and Edge to browse page. However fireFox won't work for me.
