### ISSUE TITLE
Feature Request: Add a timestamp to the photo taken

### ISSUE THREAD

**Issue by pardofelis** [jomjol/AI-on-the-edge-device#2794] opened 2024-01-08 13:25 UTC
### The Feature

Hi folks, hi jomjol,

I hope you are allright.
If you allow me to explain my feature request:
> Currently it is possible to get the image by an REST-API request. Thereby it is possible to obtain the image of the last flow.
> However, the request results in an image to be shown, but does not specify, when exactly the photo was taken.

Is it possible to add an option to have the timestamp of the photo stamped onto  the photo?

To the background of my question:
I have created a webpage using iobroker-vis to show me different values for the case I have to submit the watermeter's reading to my supplier. To be able to check whether the reading is correct, I have also added an image which is obtained with the REST API hyperlink. But as it doesn't show the time when it was taken, the last flow and therefore the image could be way more in the past.

Many thanks for reading this far.
Sincerely
pardofelis

**Comment by caco3** [comment] 2024-02-12 23:39
Duplicate of https://github.com/jomjol/AI-on-the-edge-device/issues/1187

**Closed by caco3** 2024-02-12 23:39 UTC
Labels: enhancement
