### ISSUE TITLE
Questions regarding  inconsistend recognition

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#923] opened 2022-08-20 08:55 UTC
Hi all

Thanks for this really nice project!
I have a couple of questions:
1. It seems as if one of the analogue ROIs simply does not get updated anymore. I did several re-configuration and restarts, but it still sticks to an old image (`2.2`, 2nd analogue pointer from the left):
![Screenshot_20220820_104630](https://user-images.githubusercontent.com/1783586/185737097-04847199-f6ed-4efb-b7dc-e64f45328fb9.png)
1. As you can see in above image, the most-right digital digit recognized gets detected as `1.7`. How ever on the Overview Screen resp. RAW value), it still gets shown as `2`:
![Screenshot_20220820_104613](https://user-images.githubusercontent.com/1783586/185737191-952cc92b-bb0d-4457-bb5f-fdfec33b2148.png)
How to fix this?

**Comment by haverland** [comment] 2022-08-20 09:58
Could you add recognititions of (x.01) between 8-9.9, your last digit and the raw value?

You digit has an early transition.

**Comment by haverland** [comment] 2022-08-20 10:05
To your first question: Any error in log? Could be possibly a sd-card problem.

**Comment by caco3** [comment] 2022-08-20 10:08
> To your first question: Any error in log? Could be possibly a sd-card problem.

I don't see any errors (beside the expected `rate error`):
```

2022-08-20T11:59:26: task_autodoFlow - next round - Round #5
2022-08-20T11:59:26: 	FlowControll.doFlow - ClassFlowMakeImage
2022-08-20T11:59:34: 	FlowControll.doFlow - ClassFlowAlignment
2022-08-20T12:00:20: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-20T12:00:24: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-20T12:00:35: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-08-20T12:00:35: 	FlowControll.doFlow - ClassFlowMQTT
2022-08-20T12:00:35: sent publish successful in MQTTPublish, msg_id=1391, wasserzaehler/connection, connected
2022-08-20T12:00:35: sent publish successful in MQTTPublish, msg_id=53745, wasserzaehler/uptime, 1660989609
2022-08-20T12:00:35: sent publish successful in MQTTPublish, msg_id=37246, wasserzaehler/freeMem, 3003959
2022-08-20T12:00:35: sent publish successful in MQTTPublish, msg_id=42779, wasserzaehler/wifiRSSI, -75
2022-08-20T12:00:35: sent publish successful in MQTTPublish, msg_id=35757, wasserzaehler/Wasser/error, Rate too high - Read: 502.7810 - Pre: 501.7750
2022-08-20T12:00:36: sent publish successful in MQTTPublish, msg_id=2261, wasserzaehler/Wasser/raw, 502.7810
2022-08-20T12:00:36: sent publish successful in MQTTPublish, msg_id=22408, wasserzaehler/Wasser/json, {"value":"","raw":"502.7810","error":"Rate too high - Read: 502.7810 - Pre: 501.7750","rate":"","timestamp":""}
2022-08-20T12:00:36: task_autodoFlow - round done
2022-08-20T12:00:36: CPU Temperature: 68.3
2022-08-20T12:02:26: task_autodoFlow - next round - Round #6
2022-08-20T12:02:26: 	FlowControll.doFlow - ClassFlowMakeImage
2022-08-20T12:02:34: 	FlowControll.doFlow - ClassFlowAlignment
2022-08-20T12:03:20: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-20T12:03:24: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-20T12:03:35: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-08-20T12:03:35: 	FlowControll.doFlow - ClassFlowMQTT
2022-08-20T12:03:35: sent publish successful in MQTTPublish, msg_id=41666, wasserzaehler/connection, connected
2022-08-20T12:03:35: sent publish successful in MQTTPublish, msg_id=57483, wasserzaehler/uptime, 1660989789
2022-08-20T12:03:35: sent publish successful in MQTTPublish, msg_id=42746, wasserzaehler/freeMem, 3003959
2022-08-20T12:03:35: sent publish successful in MQTTPublish, msg_id=18712, wasserzaehler/wifiRSSI, -75
2022-08-20T12:03:35: sent publish successful in MQTTPublish, msg_id=9673, wasserzaehler/Wasser/error, Rate too high - Read: 502.7810 - Pre: 501.7750
2022-08-20T12:03:36: sent publish successful in MQTTPublish, msg_id=15500, wasserzaehler/Wasser/raw, 502.7810
2022-08-20T12:03:36: sent publish successful in MQTTPublish, msg_id=45190, wasserzaehler/Wasser/json, {"value":"","raw":"502.7810","error":"Rate too high - Read: 502.7810 - Pre: 501.7750","rate":"","timestamp":""}
2022-08-20T12:03:36: task_autodoFlow - round done
2022-08-20T12:03:36: CPU Temperature: 68.3
2022-08-20T12:05:26: task_autodoFlow - next round - Round #7
2022-08-20T12:05:26: 	FlowControll.doFlow - ClassFlowMakeImage
2022-08-20T12:05:34: 	FlowControll.doFlow - ClassFlowAlignment
2022-08-20T12:06:20: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-20T12:06:24: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-08-20T12:06:35: 	FlowControll.doFlow - ClassFlowPostProcessing
2022-08-20T12:06:35: 	FlowControll.doFlow - ClassFlowMQTT
2022-08-20T12:06:35: sent publish successful in MQTTPublish, msg_id=11892, wasserzaehler/connection, connected
2022-08-20T12:06:35: sent publish successful in MQTTPublish, msg_id=40490, wasserzaehler/uptime, 1660989969
2022-08-20T12:06:35: sent publish successful in MQTTPublish, msg_id=57926, wasserzaehler/freeMem, 3003775
2022-08-20T12:06:36: sent publish successful in MQTTPublish, msg_id=63739, wasserzaehler/wifiRSSI, -75
2022-08-20T12:06:36: sent publish successful in MQTTPublish, msg_id=57757, wasserzaehler/Wasser/error, Rate too high - Read: 502.7810 - Pre: 501.7750
2022-08-20T12:06:36: sent publish successful in MQTTPublish, msg_id=27999, wasserzaehler/Wasser/raw, 502.7810
2022-08-20T12:06:36: sent publish successful in MQTTPublish, msg_id=19704, wasserzaehler/Wasser/json, {"value":"","raw":"502.7810","error":"Rate too high - Read: 502.7810 - Pre: 501.7750","rate":"","timestamp":""}
2022-08-20T12:06:36: task_autodoFlow - round done
```

**Comment by caco3** [comment] 2022-08-20 10:09
> Could you add recognititions of (x.01) between 8-9.9, your last digit and the raw value?
> 
> You digit has an early transition.

Not sure what you mean. Should i provide training data? Or adjust my configuration?

**Comment by caco3** [comment] 2022-08-20 13:36
I took a new SD card and started from scratch, but again same issue:
![grafik](https://user-images.githubusercontent.com/1783586/185748622-c1d88842-664e-47d3-9bd5-7992b4d469b7.png)

**Comment by haverland** [comment] 2022-08-20 19:22
I haven't seen such. Could you check if img_tmp/main_ana3.bmp (depends on you naming of the pointers) if it is the shown image?

I wonder if it could depend on the ROIs out of the image.

**Comment by caco3** [comment] 2022-08-20 19:25
> I wonder if it could depend on the ROIs out of the image.

Yes, that was also my thought. I now rotated the ESP32-CAM to avoid this. And indeed, it seems to be ok now.
The recognition still is bad, so i am going to collect training data.

**Comment by haverland** [comment] 2022-08-20 19:40
You could reduce the LED intensity (Expert mode in configuration)

**Comment by caco3** [comment] 2022-08-20 19:49
> You could reduce the LED intensity (Expert mode in configuration)

Whats the difference to the `LEDIntensity` in the setup? I lowered that already to `5`.

**Comment by s0170071** [comment] 2022-08-20 21:49
I had a similar issue with the digital recognition. One of my ROIs was partly outside the image which resulted in a garbled image for that ROI. Moved it back into the image- that fixed it. Can't reproduce it now.

**Comment by jomjol** [comment] 2022-08-21 14:40
I can confirm, that images out of the roated image are a problem. Error handling is poor on that, might be an issue for some further versions. I will put it on the request list - but currently no time to handle that.

I recommend, that you make a new issue, as soon as you have training data - therefore I would close this issue for now. Okay?

**Comment by caco3** [comment] 2022-08-21 15:04
> I recommend, that you make a new issue, as soon as you have training data - therefore I would close this issue for now. Okay?

I am already recording training data and will create create a new issue with that data.

The other point is the rounding of he last digital digit (a `2` is recognized as `1.7` but then rounded up to `2`). There are several reports for a similar issue but I am not sure if it is really the same as https://github.com/jomjol/AI-on-the-edge-device/issues/921

**Comment by jomjol** [comment] 2022-08-21 15:09
Either this or a one time false reading and therefore a "2", now locked by negative rate.
I'm about to compile a new rolling to test the new algo of haverland. Just have a look into the rolling version. It should be out within in this day.

**Closed by jomjol** 2022-08-21 15:09 UTC
